// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 The OpenOSV Contributors
//
// OfxCuda.cpp - driver-API launch of the OpenFX reframe kernel (OfxCuda.h).

#include "OfxCuda.h"

#include "OfxGpuPipeline.h"  // [WP-V-GPU] releaseDevicePools()

#include "PluginLog.h"

#if defined(_WIN32)
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <windows.h>
#endif

#if defined(OSV_OFX_HAVE_CUDA)
#include <cuda.h>
#endif

#include <cstddef>
#include <mutex>
#include <vector>

#if defined(OSV_OFX_HAVE_CUDA)
// ===========================================================================
//  The embedded fatbin
//
//  Generated by cmake/EmbedKernelScript.cmake from the fatbin nvcc built out
//  of OfxReframeKernel.cu.  Global scope with C++ linkage, like the Premiere
//  effect's (an anonymous namespace would make the link fail).
// ===========================================================================
extern const unsigned char kOsvOfxReframeFatbin[];
extern const std::size_t kOsvOfxReframeFatbin_size;
#endif

namespace osv::ofx::cuda {

using osv::premiere::PluginLog;

bool driverPresent() noexcept {
#if !defined(_WIN32)
    // CUDA render is an NVIDIA-on-Windows path here; a Mac has no driver.
    return false;
#else
    // Already in the process: the host (Resolve on an NVIDIA machine) loaded
    // it, which is the case that matters - a CUDA render cannot happen
    // without it.
    if (::GetModuleHandleW(L"nvcuda.dll")) {
        return true;
    }
    // Otherwise look for it where the driver installs it, WITHOUT loading
    // anything from the plug-in folder or the host's directory.
    HMODULE probe = ::LoadLibraryExW(L"nvcuda.dll", nullptr, LOAD_LIBRARY_SEARCH_SYSTEM32);
    if (!probe) {
        return false;
    }
    // Keep it loaded: the delay-load stub will bind to this very module on
    // the first driver call, and unloading it now would only make that call
    // load it again.
    return true;
#endif
}

#if defined(OSV_OFX_HAVE_CUDA)

bool driverInitialised(std::string* why) noexcept {
    if (!driverPresent()) {
        if (why) {
            *why = "no NVIDIA driver (nvcuda.dll)";
        }
        return false;
    }
    // Idempotent and cheap after the first call.
    const CUresult r = cuInit(0);
    if (r != CUDA_SUCCESS) {
        if (why) {
            const char* name = nullptr;
            (void)cuGetErrorName(r, &name);
            *why = std::string("cuInit failed: ") + (name ? name : "CUDA_ERROR_UNKNOWN");
        }
        return false;
    }
    return true;
}

namespace {

/// One loaded copy of the fatbin, in one context.
struct ContextModule {
    CUcontext context = nullptr;
    unsigned long long contextId = 0;  ///< cuCtxGetId, 0 when the driver cannot say.
    CUmodule module = nullptr;
    CUfunction kernel = nullptr;
    // [WP-V-GPU] the own-GPU path's kernels, from the same module.
    CUfunction viewFloat = nullptr;  ///< OSV_OFX_VIEW_KERNEL_NAME.
    CUfunction viewByte = nullptr;   ///< OSV_OFX_VIEW_BYTE_KERNEL_NAME.
    CUfunction equirect = nullptr;   ///< OSV_OFX_EQUIRECT_KERNEL_NAME.
};

/// The driver's unique id of a context (cuCtxGetId, CUDA 12.0+), or 0.
///
/// WHY: a context's HANDLE is only an address, and a host that destroys a
/// context and creates a new one can get the very same address back - a
/// cache keyed by the handle alone then launches a kernel handle from the
/// DEAD context (seen in the tests as CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES).
/// The id is never reused within a process, so handle + id is exact.
///
/// Resolved with GetProcAddress rather than imported: a driver older than
/// CUDA 12 has no cuCtxGetId, and a delay-loaded import of a missing export
/// would raise an exception on first use instead of simply answering 0.
unsigned long long contextIdOf(CUcontext context) noexcept {
    using GetIdFn = CUresult(CUDAAPI*)(CUcontext, unsigned long long*);
    static const GetIdFn getId = [] {
        HMODULE driver = ::GetModuleHandleW(L"nvcuda.dll");
        return driver ? reinterpret_cast<GetIdFn>(::GetProcAddress(driver, "cuCtxGetId")) : nullptr;
    }();
    unsigned long long id = 0;
    if (!getId || !context || getId(context, &id) != CUDA_SUCCESS) {
        return 0;
    }
    return id;
}

std::mutex g_moduleMutex;
std::vector<ContextModule> g_modules;

/// Upper bound on remembered contexts.  A host keeps one per GPU; anything
/// beyond a handful means contexts are being recreated, and the stale
/// entries (whose contexts are gone) are simply dropped from the front.
constexpr std::size_t kMaxContexts = 16;

/// "cuModuleLoadData: CUDA_ERROR_... (text)".
std::string cudaMessage(const char* what, CUresult result) {
    const char* name = nullptr;
    const char* text = nullptr;
    cuGetErrorName(result, &name);
    cuGetErrorString(result, &text);
    std::string s(what ? what : "cuda");
    s += ": ";
    s += name ? name : "CUDA_ERROR_UNKNOWN";
    if (text) {
        s += " (";
        s += text;
        s += ")";
    }
    return s;
}

/// The module for `context` (current on this thread) - every kernel of the
/// fatbin - loading it on first use.  False with `error` set on failure.
bool moduleFor(CUcontext context, ContextModule& out, std::string& error) {
    if (!context) {
        error = "no CUDA context to load the kernels into";
        return false;
    }
    const unsigned long long id = contextIdOf(context);
    std::lock_guard<std::mutex> lock(g_moduleMutex);
    for (auto it = g_modules.begin(); it != g_modules.end(); ++it) {
        if (it->context != context) {
            continue;
        }
        if (it->contextId == id && it->kernel) {
            out = *it;
            return true;
        }
        // Same address, different context: the old one was destroyed and its
        // module went with it.  Forget it (never unload into a dead context).
        g_modules.erase(it);
        break;
    }
    if (kOsvOfxReframeFatbin_size == 0) {
        error = "the embedded fatbin is empty (the build did not run nvcc)";
        return false;
    }
    // cuModuleLoadFatBinary loads into the CURRENT context, which is the
    // host's: exactly where its images live.
    CUmodule module = nullptr;
    CUresult r = cuModuleLoadFatBinary(&module, kOsvOfxReframeFatbin);
    if (r != CUDA_SUCCESS || !module) {
        error = cudaMessage("cuModuleLoadFatBinary", r);
        return false;
    }
    // Every kernel of the fatbin, looked up once: a module that lacks one is
    // a build mismatch, refused as a whole rather than half used.
    ContextModule loaded{context, id, module};
    const struct {
        CUfunction* slot;
        const char* name;
    } wanted[] = {
        {&loaded.kernel, OSV_OFX_REFRAME_KERNEL_NAME},
        {&loaded.viewFloat, OSV_OFX_VIEW_KERNEL_NAME},       // [WP-V-GPU]
        {&loaded.viewByte, OSV_OFX_VIEW_BYTE_KERNEL_NAME},   // [WP-V-GPU]
        {&loaded.equirect, OSV_OFX_EQUIRECT_KERNEL_NAME},    // [WP-V-GPU]
    };
    for (const auto& w : wanted) {
        r = cuModuleGetFunction(w.slot, module, w.name);
        if (r != CUDA_SUCCESS || !*w.slot) {
            error = cudaMessage("cuModuleGetFunction", r) + " for " + w.name;
            cuModuleUnload(module);
            return false;
        }
    }
    if (g_modules.size() >= kMaxContexts) {
        // Oldest first; its context is almost certainly gone, so it is
        // forgotten rather than unloaded (see releaseModules()).
        g_modules.erase(g_modules.begin());
    }
    g_modules.push_back(loaded);
    PluginLog::info("ofx/cuda: loaded the reframe kernels into context {} ({} bytes of fatbin)",
                    static_cast<const void*>(context), kOsvOfxReframeFatbin_size);
    out = loaded;
    return true;
}

/// The reframe kernel for `context` (current on this thread), loading the
/// module on first use.  Null with `error` set on failure.
CUfunction kernelFor(CUcontext context, std::string& error) {
    ContextModule module;
    return moduleFor(context, module, error) ? module.kernel : nullptr;
}

}  // namespace

bool launchReframe(const OsvReframeParams& params, const OsvRgbaSource& source, const void* sourceRow0, void* dstData,
                   const OsvOfxTarget& target, void* stream, std::string& error) noexcept {
    try {
        if (!sourceRow0 || !dstData) {
            error = "null device image";
            return false;
        }
        if (target.windowW <= 0 || target.windowH <= 0) {
            return true;  // an empty window renders nothing, successfully
        }
        if (!driverPresent()) {
            error = "the host asked for a CUDA render but nvcuda.dll is not available";
            return false;
        }
        // The context the host's images live in.  The output pointer itself
        // says which one that is (unified addressing, always on for 64-bit
        // processes), which is exact even when the host has not made its
        // context current on this thread; the current context is the answer
        // when the pointer cannot be asked.
        CUcontext current = nullptr;
        (void)cuCtxGetCurrent(&current);
        CUcontext owner = nullptr;
        if (cuPointerGetAttribute(&owner, CU_POINTER_ATTRIBUTE_CONTEXT,
                                  reinterpret_cast<CUdeviceptr>(dstData)) != CUDA_SUCCESS) {
            owner = nullptr;
        }
        CUcontext context = owner ? owner : current;
        if (!context) {
            error = "no CUDA context owns the output image and none is current";
            return false;
        }
        // Launch in the owner's context, and leave this thread exactly as
        // the host had it.
        const bool push = (context != current);
        CUresult r = CUDA_SUCCESS;
        if (push) {
            r = cuCtxPushCurrent(context);
            if (r != CUDA_SUCCESS) {
                error = cudaMessage("cuCtxPushCurrent", r);
                return false;
            }
        }
        struct PopOnExit {
            bool active;
            ~PopOnExit() {
                if (active) {
                    CUcontext popped = nullptr;
                    cuCtxPopCurrent(&popped);
                }
            }
        } popOnExit{push};

        CUfunction kernel = kernelFor(context, error);
        if (!kernel) {
            return false;
        }

        // Grid over the render window, rounded up to whole blocks.
        const unsigned gridX = static_cast<unsigned>((target.windowW + OSV_OFX_BLOCK_X - 1) / OSV_OFX_BLOCK_X);
        const unsigned gridY = static_cast<unsigned>((target.windowH + OSV_OFX_BLOCK_Y - 1) / OSV_OFX_BLOCK_Y);

        // cuLaunchKernel copies every argument before it returns, so these
        // locals may go out of scope as soon as it has.
        OsvReframeParams p = params;
        OsvRgbaSource s = source;
        const void* src = sourceRow0;
        void* dst = dstData;
        OsvOfxTarget t = target;
        void* args[] = {&p, &s, &src, &dst, &t};

        CUstream cuStream = static_cast<CUstream>(stream);
        r = cuLaunchKernel(kernel, gridX, gridY, 1u, OSV_OFX_BLOCK_X, OSV_OFX_BLOCK_Y, 1u, 0u, cuStream, args,
                           nullptr);
        if (r != CUDA_SUCCESS) {
            error = cudaMessage("cuLaunchKernel", r);
            return false;
        }
        if (!cuStream) {
            // No stream from the host: the work must be finished before the
            // render action returns (ofxGPURender.h, kOfxImageEffectPropCudaStream).
            r = cuStreamSynchronize(nullptr);
            if (r != CUDA_SUCCESS) {
                error = cudaMessage("cuStreamSynchronize", r);
                return false;
            }
        }
        return true;
    } catch (...) {
        error = "exception while launching the reframe kernel";
        return false;
    }
}

void releaseModules() noexcept {
    // [WP-V-GPU] The own-GPU path's pools first: they unload what they loaded
    // into their own (retained, so certainly alive) primary contexts, which
    // takes g_moduleMutex - so it is not held here yet.
    gpu::releaseDevicePools();
    std::lock_guard<std::mutex> lock(g_moduleMutex);
    g_modules.clear();
}

// ---------------------------------------------------------------------------
//  [WP-V-GPU] The own-GPU path's kernels
// ---------------------------------------------------------------------------

bool ownKernels(void* context, OwnKernels& out, std::string& error) noexcept {
    try {
        out = OwnKernels{};
        ContextModule module;
        if (!moduleFor(static_cast<CUcontext>(context), module, error)) {
            return false;
        }
        out.viewFloat = module.viewFloat;
        out.viewByte = module.viewByte;
        out.equirect = module.equirect;
        return true;
    } catch (...) {
        // std::vector growth in the cache is the only thing that can throw.
        error = "exception while loading the own-GPU kernels";
        out = OwnKernels{};
        return false;
    }
}

void unloadModulesIn(void* context) noexcept {
    if (!context) {
        return;
    }
    const CUcontext target = static_cast<CUcontext>(context);
    const unsigned long long id = contextIdOf(target);
    std::lock_guard<std::mutex> lock(g_moduleMutex);
    for (auto it = g_modules.begin(); it != g_modules.end();) {
        if (it->context != target) {
            ++it;
            continue;
        }
        // Only a module of THIS context (same id) is unloaded; an entry for a
        // dead context that happened to have the same address is merely
        // forgotten, as everywhere else in this cache.
        if (it->contextId == id && it->module) {
            (void)cuModuleUnload(it->module);
        }
        it = g_modules.erase(it);
    }
}

CurrentContextGuard::CurrentContextGuard() noexcept {
    // Only when the driver is ALREADY in the process: a host with no CUDA
    // has no context to protect, and calling into a delay-loaded nvcuda.dll
    // that is not there would raise a structured exception.
    if (!::GetModuleHandleW(L"nvcuda.dll")) {
        return;
    }
    CUcontext saved = nullptr;
    if (cuCtxGetCurrent(&saved) != CUDA_SUCCESS) {
        return;  // not initialised in this process: nothing is current
    }
    m_saved = saved;
    m_active = true;
}

CurrentContextGuard::~CurrentContextGuard() {
    if (!m_active) {
        return;
    }
    CUcontext now = nullptr;
    if (cuCtxGetCurrent(&now) == CUDA_SUCCESS && now != static_cast<CUcontext>(m_saved)) {
        cuCtxSetCurrent(static_cast<CUcontext>(m_saved));
    }
}

#else  // !OSV_OFX_HAVE_CUDA

bool driverInitialised(std::string* why) noexcept {
    if (why) {
        *why = "this build of OpenOSV.ofx has no CUDA kernel";
    }
    return false;
}

bool launchReframe(const OsvReframeParams&, const OsvRgbaSource&, const void*, void*, const OsvOfxTarget&, void*,
                   std::string& error) noexcept {
    error = "this build of OpenOSV.ofx has no CUDA kernel";
    return false;
}

void releaseModules() noexcept {}

bool ownKernels(void*, OwnKernels& out, std::string& error) noexcept {
    out = OwnKernels{};
    error = "this build of OpenOSV.ofx has no CUDA kernel";
    return false;
}

void unloadModulesIn(void*) noexcept {}

CurrentContextGuard::CurrentContextGuard() noexcept = default;
CurrentContextGuard::~CurrentContextGuard() = default;

#endif  // OSV_OFX_HAVE_CUDA

}  // namespace osv::ofx::cuda
