// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 The OpenOSV Contributors
//
// GpuFilter.cpp - the xGPUFilterEntry side of Open 360 Reframe.
//
// Premiere binds a GPU renderer to a software effect BY MATCH NAME: the
// module exports xGPUFilterEntry and reports PrGPUFilterInfo with a NULL
// match name, which binds it to the effect this module's own PiPL declares
// (registered by Premiere as "AE." + the PiPL match name - see the startup
// code for why spelling the name out broke that), and from then on every
// frame the host can accelerate is routed here instead of to PF_Cmd_RENDER.
//
// Deliberate design choices, each with its reason:
//
//   * The module glue is written here rather than taken from the SDK's
//     GPUVideoFilter/Utils/PrGPUFilterModule.h.  That header pulls in
//     Boost.Preprocessor (through PrGPU/KernelSupport) and unconditionally
//     acquires PF_TransitionSuite, neither of which an effect needs; it is
//     also a C++ class hierarchy that would force our state into its shape.
//     The five function pointers of PrGPUFilter are trivial to fill by hand.
//
//   * CUDA is used STRICTLY through the driver API (cuda.h, nvcuda.dll).
//     The SDK guide ranks that first for compatibility (12.1.2) and it means
//     the .aex never loads a cudart DLL, so it cannot collide with the copy
//     Premiere itself ships.  The kernel comes from an embedded fatbin, not
//     from a linked device object, for the same reason.
//
//   * The host's CUcontext is pushed around every driver call.  The GPU
//     Device Suite says exclusive access is always held for a "full GPU
//     plug-in" and that the context is current on the render thread, but
//     CreateInstance is NOT documented to run on a render thread, and
//     pushing an already-current context is cheap and always correct.
//
//   * Modules are cached per device in a mutex-guarded static table, because
//     CreateInstance is called again on EVERY parameter change and loading a
//     fatbin per keyframe would dominate the render.
//
// Every extern "C" boundary catches (...): an exception unwinding into
// Premiere's C call stack is undefined behaviour and would take the host
// down with it.

#include "DirectPath.h"
#include "ReframeCpu.h"
#include "ReframeParams.h"

#include "PluginLog.h"

// Adobe headers are #pragma pack(push, 1); nothing of ours is declared while
// they are open.
#include "PrSDKColorManagementSuite.h"
#include "PrSDKGPUDeviceSuite.h"
#include "PrSDKGPUFilter.h"
#include "PrSDKMemoryManagerSuite.h"
#include "PrSDKPPix2Suite.h"
#include "PrSDKPPixSuite.h"
#include "PrSDKSequenceInfoSuite.h"
#include "PrSDKVideoSegmentSuite.h"

#include <cuda.h>

#include <algorithm>
#include <atomic>
#include <cstring>
#include <mutex>
#include <thread>
#include <new>
#include <string>

// ===========================================================================
//  The embedded fatbin
//
//  Generated by cmake/EmbedKernelScript.cmake from the fatbin nvcc produced
//  out of ReframeKernel.cu.  The generated translation unit defines these at
//  global scope with ordinary C++ linkage, so the declarations here are at
//  global scope too (an anonymous namespace would give them internal linkage
//  and the link would fail with an unresolved symbol).
// ===========================================================================
extern const unsigned char kOsvReframeFatbin[];
extern const std::size_t kOsvReframeFatbin_size;

namespace {

using osv::premiere::PluginLog;
using namespace osv::reframe;

/// Name the kernel is exported under (extern "C" in the .cu, so no
/// mangling).  A mismatch here is caught by the GPU test at load time.
constexpr const char* kKernelName = "osvReframeEquirectKernel";

/// Thread-block geometry.  16x16 is what every Adobe GPU sample uses and it
/// keeps a warp's 32 threads on two adjacent rows of the output, which is
/// the access pattern the equirect sampler likes.
constexpr unsigned kBlockDimX = 16;
constexpr unsigned kBlockDimY = 16;

/// Largest device table we keep.  Premiere enumerates at most a handful of
/// GPUs; 16 is generous and bounds the static state.
constexpr unsigned kMaxDevices = 16;

/// Largest sequence edge we will believe from the Sequence Info Suite.  See
/// the identical constant in EffectMain.cpp: a corrupt rectangle must become
/// "unknown", not a camera dimension.
constexpr long long kMaxSequenceEdge = 65536;

// ===========================================================================
//  Small helpers
// ===========================================================================

/// Turn a CUresult into something a log line can carry.
std::string cudaMessage(const char* what, CUresult result) {
    const char* name = nullptr;
    const char* text = nullptr;
    cuGetErrorName(result, &name);
    cuGetErrorString(result, &text);
    std::string s(what ? what : "cuda");
    s += ": ";
    s += name ? name : "CUDA_ERROR_UNKNOWN";
    if (text) {
        s += " (";
        s += text;
        s += ")";
    }
    return s;
}

/// RAII push/pop of a CUcontext.  Pushing the context that is already
/// current is legal and cheap; popping in the destructor guarantees the
/// thread is left exactly as Premiere handed it to us even on an early
/// return or an exception.
class ContextScope {
public:
    explicit ContextScope(CUcontext context) noexcept {
        if (!context) {
            return;
        }
        m_pushed = (cuCtxPushCurrent(context) == CUDA_SUCCESS);
    }
    ~ContextScope() {
        if (m_pushed) {
            CUcontext popped = nullptr;
            cuCtxPopCurrent(&popped);
        }
    }
    ContextScope(const ContextScope&) = delete;
    ContextScope& operator=(const ContextScope&) = delete;

    [[nodiscard]] bool ok() const noexcept { return m_pushed; }

private:
    bool m_pushed = false;
};

// ===========================================================================
//  Per-device module cache
//
//  cuModuleLoadFatBinary is expensive (it JITs for the device if no matching
//  cubin is present) and CreateInstance runs on every parameter change, so
//  one module per device is loaded once and kept until Shutdown.  The table
//  is keyed by the CUcontext as well as the device index: a host that
//  recreated its context would otherwise hand us a module belonging to a
//  destroyed context, which is undefined behaviour.
// ===========================================================================
struct DeviceModule {
    CUcontext context = nullptr;
    CUmodule module = nullptr;
    CUfunction kernel = nullptr;
    /// The direct path's fused fisheye -> view kernel, from the same fatbin.
    /// Null only if this build's fatbin lacks it; the equirect path is then
    /// the only one, exactly as before the direct path existed.
    CUfunction direct = nullptr;
    bool valid = false;
};

std::mutex g_moduleMutex;
DeviceModule g_modules[kMaxDevices];

/// Load (or fetch) the module for a device.  Caller must NOT hold the
/// context pushed - this function pushes it itself.  Returns nullptr on
/// failure, having logged the reason.
CUfunction acquireKernel(csSDK_uint32 deviceIndex, CUcontext context) noexcept {
    if (deviceIndex >= kMaxDevices || !context) {
        PluginLog::error("reframe/gpu: device index {} or context unusable", deviceIndex);
        return nullptr;
    }
    if (kOsvReframeFatbin_size == 0) {
        PluginLog::error("reframe/gpu: the embedded fatbin is empty - the build did not run nvcc");
        return nullptr;
    }

    std::lock_guard<std::mutex> lock(g_moduleMutex);
    DeviceModule& slot = g_modules[deviceIndex];
    if (slot.valid && slot.context == context && slot.kernel) {
        return slot.kernel;
    }

    // A stale entry (different context) is dropped without unloading: the
    // context it belonged to is gone, so cuModuleUnload would fail or worse.
    if (slot.valid && slot.context != context) {
        PluginLog::warn("reframe/gpu: device {} changed context, reloading the module", deviceIndex);
        slot = DeviceModule{};
    }

    ContextScope scope(context);
    if (!scope.ok()) {
        PluginLog::error("reframe/gpu: cuCtxPushCurrent failed for device {}", deviceIndex);
        return nullptr;
    }

    CUmodule module = nullptr;
    CUresult r = cuModuleLoadFatBinary(&module, kOsvReframeFatbin);
    if (r != CUDA_SUCCESS || !module) {
        PluginLog::error("reframe/gpu: {}", cudaMessage("cuModuleLoadFatBinary", r));
        return nullptr;
    }

    CUfunction kernel = nullptr;
    r = cuModuleGetFunction(&kernel, module, kKernelName);
    if (r != CUDA_SUCCESS || !kernel) {
        PluginLog::error("reframe/gpu: {}", cudaMessage("cuModuleGetFunction", r));
        cuModuleUnload(module);
        return nullptr;
    }

    // The fused kernel is optional: failing to find it only switches the
    // direct path off, never the effect.
    CUfunction direct = nullptr;
    r = cuModuleGetFunction(&direct, module, kDirectKernelName);
    if (r != CUDA_SUCCESS || !direct) {
        PluginLog::warn("reframe/gpu: the fused direct kernel is missing from the fatbin ({}); rendering from the "
                        "equirect only",
                        cudaMessage("cuModuleGetFunction", r));
        direct = nullptr;
    }

    slot.context = context;
    slot.module = module;
    slot.kernel = kernel;
    slot.direct = direct;
    slot.valid = true;
    PluginLog::info("reframe/gpu: loaded the reframe kernel on device {} ({} bytes of fatbin)", deviceIndex,
                    kOsvReframeFatbin_size);
    return kernel;
}

/// The fused direct kernel for a device and context, or null when the module
/// is not loaded for that context (acquireKernel() loads it) or lacks it.
CUfunction directKernelFor(csSDK_uint32 deviceIndex, CUcontext context) noexcept {
    if (deviceIndex >= kMaxDevices || !context) {
        return nullptr;
    }
    std::lock_guard<std::mutex> lock(g_moduleMutex);
    const DeviceModule& slot = g_modules[deviceIndex];
    return (slot.valid && slot.context == context) ? slot.direct : nullptr;
}

/// Unload every cached module.  Called from the entry point's shutdown
/// phase, which is the only moment the host guarantees the contexts are
/// still alive and no render is in flight.
void releaseKernels() noexcept {
    std::lock_guard<std::mutex> lock(g_moduleMutex);
    for (DeviceModule& slot : g_modules) {
        if (slot.valid && slot.module && slot.context) {
            ContextScope scope(slot.context);
            if (scope.ok()) {
                cuModuleUnload(slot.module);
            }
        }
        slot = DeviceModule{};
    }
}

// ===========================================================================
//  Per-instance state (PrGPUFilterInstance::ioPrivatePluginData)
// ===========================================================================
struct Instance {
    /// Magic word so a corrupted or already-disposed pointer is detected
    /// rather than dereferenced.
    static constexpr std::uint32_t kMagic = 0x4F534756u;  // 'OSGV'
    std::uint32_t magic = kMagic;

    piSuitesPtr suites = nullptr;
    SPBasicSuite* basic = nullptr;

    // Suites.  Raw pointers with explicit releases in the destructor: the
    // RAII SuiteHandle in plugins/common is typed for the importer's set and
    // these are only ever held by one object with a well defined lifetime.
    const PrSDKGPUDeviceSuite* gpu = nullptr;
    const PrSDKPPixSuite* ppix = nullptr;
    const PrSDKVideoSegmentSuite* segment = nullptr;
    int segmentVersion = 0;
    const PrSDKSequenceInfoSuite* sequence = nullptr;
    int sequenceVersion = 0;

    csSDK_uint32 deviceIndex = 0;
    PrTimelineID timelineId = 0;
    csSDK_int32 nodeId = 0;

    CUcontext context = nullptr;
    CUstream stream = nullptr;
    CUfunction kernel = nullptr;

    /// AE index -> host GetParam index, discovered once in CreateInstance by
    /// probeParams().  Constructed with the static mapping so every read is
    /// well defined even if the probe never runs (no suite, a host that
    /// refuses GetParamCount, an exception on the way in).
    HostParamMap paramMap{};

    /// False until probeParams() has positively identified the host's index
    /// space.  The probe reads parameters through GetParam, which fails
    /// intermittently on a freshly created node, so a single failed attempt
    /// at CreateInstance must not condemn the instance to the static mapping
    /// for its whole life: Render retries while this is false.  Rendering a
    /// frame proves the node is ready, which is exactly when a retry works.
    bool paramMapProbed = false;

    /// [WP-CAMERA] How this host numbers popup entries on the GPU side
    /// (PopupBase in ReframeParams.h), learned from the values readSettings()
    /// sees: Premiere 26.2.2 counts from 0, After Effects and the mock host
    /// from 1.  Atomic because Render may run on several threads for one
    /// instance; the value only ever moves from Unknown to a settled base.
    /// Mutable because the readers take the instance const: learning the
    /// numbering is a cache of what the host says, not a change of state.
    mutable std::atomic<int> popupBase{static_cast<int>(PopupBase::Unknown)};

    // ---- the direct path (DirectPath.h) ---------------------------------
    /// The media file and owning clip node this instance renders; the node
    /// is acquired and released in DisposeInstance.
    osv::reframe::direct::SourceBinding source;
    /// OSV_TRANSFER_* of the sequence's working colour space, -1 when the
    /// direct path cannot produce it.
    int directTransfer = -1;
    /// Set after a failure that will not go away by itself (the file is not
    /// one the engine can open, the view cannot be expressed): the instance
    /// then stays on the equirect path instead of paying for the attempt on
    /// every frame.  A transient failure (a decode hiccup) does not set it.
    bool directDisabled = false;
    /// Failures logged so far for this instance (bounded, see render()).
    int directFailures = 0;

    Instance() noexcept { paramMap.setStatic(); }

    [[nodiscard]] bool alive() const noexcept { return magic == kMagic; }
};

/// Acquire a suite, returning nullptr instead of throwing.
template <class SuiteT>
const SuiteT* acquire(SPBasicSuite* basic, const char* name, int version) noexcept {
    if (!basic || !basic->AcquireSuite || !name) {
        return nullptr;
    }
    const void* suite = nullptr;
    if (basic->AcquireSuite(name, version, &suite) != kSPNoError || !suite) {
        return nullptr;
    }
    return static_cast<const SuiteT*>(suite);
}

/// Acquire the first version of a suite the host provides.  Used for the
/// Video Segment Suite (9 -> 8 -> 7 -> 6; only GetParam and GetNodeProperty
/// are used and both are v4 members) and the Sequence Info Suite.
template <class SuiteT>
const SuiteT* acquireFirst(SPBasicSuite* basic, const char* name, std::initializer_list<int> versions,
                           int* outVersion) noexcept {
    for (const int v : versions) {
        if (const SuiteT* suite = acquire<SuiteT>(basic, name, v)) {
            if (outVersion) {
                *outVersion = v;
            }
            return suite;
        }
    }
    if (outVersion) {
        *outVersion = 0;
    }
    return nullptr;
}

/// Release a suite if it was acquired.
void releaseSuite(SPBasicSuite* basic, const char* name, int version) noexcept {
    if (basic && basic->ReleaseSuite && name && version > 0) {
        basic->ReleaseSuite(name, version);
    }
}

// ===========================================================================
//  Reading the keyframed parameters
// ===========================================================================

/// One GetParam call.
///
/// `aeIndex` is the AE parameter index; the host index it maps to comes from
/// the instance's HostParamMap, which CreateInstance either probed from the
/// host or left at the static "AE index - 1" rule.  A control the host does
/// not expose maps to -1 and the read fails cleanly, so the caller uses that
/// control's default rather than a neighbour's value.
bool readParam(const Instance& inst, int aeIndex, PrTime time, PrParam* out) noexcept {
    if (!inst.segment || !inst.segment->GetParam || !out) {
        return false;
    }
    const int hostIndex = inst.paramMap[aeIndex];
    if (hostIndex < 0) {
        return false;
    }
    std::memset(out, 0, sizeof(*out));
    const prSuiteError err = inst.segment->GetParam(inst.nodeId, hostIndex, time, out);
    return err == suiteError_NoError;
}

/// Translate one PrParam variant into the dialect matchHostParams() speaks.
/// Anything we do not use maps to Unknown, which matches nothing.
[[nodiscard]] HostParamKind kindOf(const PrParam& p) noexcept {
    switch (p.mType) {
        case kPrParamType_Int32:   return HostParamKind::Int32;
        case kPrParamType_Float32: return HostParamKind::Float32;
        case kPrParamType_Float64: return HostParamKind::Float64;
        case kPrParamType_Bool:    return HostParamKind::Bool;
        default:                   return HostParamKind::Unknown;
    }
}

/// Discover the host's parameter index space, once per instance.
///
/// Asks GetParamCount how many entries there are, reads each one's TYPE at
/// time 0, and identifies the list as one of the two layouts Premiere has
/// been seen to use (matchVerbatimLayout() below, then matchHostParams()).
/// On a positive identification the instance's map is replaced; otherwise
/// the static map it was constructed with is kept.  Either way the function
/// is non-fatal - it only ever improves the mapping, never breaks it - and it
/// logs which of the two is in force so a log alone answers the question.
///
/// Cost: one GetParamCount plus at most kParamCount GetParam calls (a few
/// retries each for entries that do not answer), all at t = 0, on a code
/// path Premiere runs when an effect is applied or a parameter changes - not
/// per frame.
void probeParams(Instance& inst) noexcept;

// ---------------------------------------------------------------------------
//  The VERBATIM host layout
//
//  Premiere Pro 26.2.2 was seen to hand a GPU filter this effect's parameter
//  list exactly as After Effects built it, minus the input layer:
//
//      GetParamCount = 15 = OSV_REFRAME_PARAM_COUNT
//      [0]i32:0 [1]bool:0 [2]i32:3 [3]f32:0 [4]f32:0 [5]f32:0 [6]f64:120
//      [7]f64:15 [8]bool:0 [9]bool:0 [10]f32:0   (11..14 unreadable at t = 0)
//
//  i.e. host index = AE index - 1, and the four group markers (Camera start
//  and end, Source start and end) PRESENT, answering as Bool.  An older
//  session showed the same layout with the markers refusing to answer at
//  all.  This is the layout the static "AE index - 1" rule assumes, so the
//  static mapping was right - but the matcher only knew the COMPACT layout
//  (markers dropped, a collapsed group missing) and logged a false "types do
//  not match" error on every such host.  Worse, the old probe read only the
//  first kValueParamCount entries of a 15-entry list, and when the markers
//  refused to answer, the FOV/Distortion anchor "identified" that prefix at
//  a constant offset that is wrong past the first group marker: Source Roll
//  was read out of Source Pan's slot while Source Pan, Source Tilt, Smooth
//  Keyframes and Output Resolution were not read at all.
//
//  The expected layout is built from ReframeParams.h alone - every AE index
//  in kValueParamAeIndex carries kValueParamKind, every other index up to
//  kParamCount is a group marker - so a control appended there (a new id,
//  a new AE index, a new kind entry) is recognised here with no change to
//  this code.
// ---------------------------------------------------------------------------

/// The smallest number of value-carrying entries that must answer with the
/// expected type before a verbatim identification is believed.  Five is the
/// same bar the compact matcher's anchor applies: a list that answers less
/// than that is not identified but unreadable, so the static mapping (which
/// IS the verbatim mapping) stays in force, the log says so, and Render
/// retries the probe once the node answers.
constexpr int kVerbatimMinTypedValues = 5;

// The tables the verbatim layout is derived from must describe a list the
// host map can hold.  Checked at compile time so a table edit that breaks
// the invariant fails the build rather than the probe.
static_assert(kValueParamCount > 0 && kValueParamCount <= kParamCount,
              "ReframeParams.h: the value controls must be a subset of the AE parameter list");
static_assert(
    [] {
        for (int i = 0; i < kValueParamCount; ++i) {
            if (kValueParamAeIndex[i] < 1 || kValueParamAeIndex[i] > kParamCount) {
                return false;
            }
            for (int j = 0; j < i; ++j) {
                if (kValueParamAeIndex[j] == kValueParamAeIndex[i]) {
                    return false;
                }
            }
        }
        return true;
    }(),
    "ReframeParams.h: kValueParamAeIndex must name distinct AE indices in 1..kParamCount");

/// What the verbatim layout expects at host index `hostIndex`: the kind of
/// the value control whose AE index is hostIndex + 1, or `isMarker` = true
/// when that AE index belongs to no value control (a group start or end).
/// Returns false for an index outside the list.
[[nodiscard]] bool verbatimExpectation(int hostIndex, HostParamKind* kind, bool* isMarker) noexcept {
    if (!kind || !isMarker || hostIndex < 0 || hostIndex >= kParamCount) {
        return false;
    }
    const int aeIndex = hostIndex + 1;
    for (int i = 0; i < kValueParamCount; ++i) {
        if (kValueParamAeIndex[i] == aeIndex) {
            *kind = kValueParamKind[i];
            *isMarker = false;
            return true;
        }
    }
    *kind = HostParamKind::Unknown;
    *isMarker = true;
    return true;
}

/// Identify the host list as this effect's AE parameter list verbatim.
///
/// `kinds` holds what the host answered for indices 0 .. readCount-1
/// (Unknown for an entry that refused or carried a type we do not use) and
/// `hostCount` what GetParamCount said.  Rules, each one a guard against a
/// plausible-looking wrong answer:
///
///   1. the host must report exactly kParamCount entries - the one number
///      that separates this layout from the compact one (8 or 11 there);
///   2. every entry that DID answer must agree with its position: a value
///      control with its own kind, a group marker with Bool (Premiere's
///      answer for a marker) - one contradiction and the list is not ours;
///   3. an entry that did not answer contradicts nothing - Premiere 26.2.2
///      refuses the trailing entries of a freshly built node at t = 0 - but
///      it is not evidence either, so at least kVerbatimMinTypedValues value
///      controls must have answered with the right kind.
///
/// On success every value control is mapped to its position, INCLUDING the
/// ones that did not answer at t = 0: in this layout the index is known
/// from the list itself, not inferred from the answers, and a read that
/// fails at render time still falls back to the control's default in the
/// readers.  Group markers stay at -1 (they carry no value and are never
/// read).  On failure `outMap` is untouched.
[[nodiscard]] bool matchVerbatimLayout(const HostParamKind* kinds, int readCount, int hostCount,
                                       HostParamMap* outMap) noexcept {
    if (!kinds || !outMap || hostCount != kParamCount || readCount < 0 || readCount > kParamCount) {
        return false;
    }
    int typedValues = 0;
    for (int host = 0; host < readCount; ++host) {
        HostParamKind expected = HostParamKind::Unknown;
        bool isMarker = false;
        if (!verbatimExpectation(host, &expected, &isMarker)) {
            return false;
        }
        const HostParamKind got = kinds[host];
        if (got == HostParamKind::Unknown) {
            continue;  // rule 3: no answer, no contradiction, no evidence
        }
        if (isMarker) {
            if (got != HostParamKind::Bool) {
                return false;  // rule 2: a marker answering as a value
            }
            continue;
        }
        if (got != expected) {
            return false;  // rule 2: a value control of the wrong kind
        }
        ++typedValues;
    }
    if (typedValues < kVerbatimMinTypedValues) {
        return false;
    }

    // ---- positional map ------------------------------------------------------
    HostParamMap map{};
    for (int i = 0; i <= OSV_REFRAME_PARAM_COUNT; ++i) {
        map.hostIndex[i] = -1;
    }
    for (int i = 0; i < kValueParamCount; ++i) {
        const int aeIndex = kValueParamAeIndex[i];
        map.hostIndex[aeIndex] = gpuParamIndex(aeIndex);
    }
    map.probed = true;
    *outMap = map;
    return true;
}

// ===========================================================================
//  Source-graph probe (diagnostic, once per process)
//
//  Can the effect find the clip it is applied to?  If the effect node can
//  walk to its media node and read which file and which media time it is
//  rendering, the reframe can sample the two FISHEYES directly on the GPU -
//  one resampling instead of fisheye -> equirect -> view, and no 18 MP
//  equirect round trip through host memory at all.  The Video Segment Suite
//  documents the walk (operator -> owner clip node -> input media node ->
//  "MediaNode::MediaInstanceString" and friends) but not what the values
//  hold in practice, so the first instance in a process logs every property
//  it can reach.  It changes nothing about rendering.
// ===========================================================================

/// Collects IterateNodeProperties callbacks.  The callback's plug-in object
/// is a csSDK_int32 - too narrow for a pointer on 64-bit - so the
/// accumulator is thread-local; the iteration is synchronous on this thread.
thread_local std::string* t_propertySink = nullptr;

prSuiteError collectProperty(csSDK_int32, const char* key, const prUTF8Char* value) {
    if (!t_propertySink) {
        return suiteError_NoError;
    }
    std::string v = value ? reinterpret_cast<const char*>(value) : "<null>";
    // Values can be long XML blobs; the head is enough to identify them.
    constexpr std::size_t kMaxValue = 240;
    if (v.size() > kMaxValue) {
        v = v.substr(0, kMaxValue) + "...(" + std::to_string(v.size()) + " bytes)";
    }
    t_propertySink->append("\n    ").append(key ? key : "<null>").append(" = ").append(v);
    return suiteError_NoError;
}

/// Log one node's type and all of its properties.
void logNode(const PrSDKVideoSegmentSuite& s, csSDK_int32 node, const char* role) {
    char type[kMaxNodeTypeStringSize] = {};
    prPluginID hash{};
    csSDK_int32 flags = 0;
    if (s.GetNodeInfo) {
        (void)s.GetNodeInfo(node, type, &hash, &flags);
    }
    std::string props;
    if (s.IterateNodeProperties) {
        t_propertySink = &props;
        const prSuiteError err = s.IterateNodeProperties(node, &collectProperty, 0);
        t_propertySink = nullptr;
        if (err != suiteError_NoError) {
            props.append("\n    (IterateNodeProperties failed: ").append(std::to_string(err)).append(")");
        }
    }
    PluginLog::info("reframe/gpu/source: {} node {} type '{}' flags 0x{:x}{}", role, node, type,
                    static_cast<unsigned>(flags), props);
}

/// Log, once, whether the CUcontext Premiere hands GPU filters is its device's
/// PRIMARY context.  If it is, the importer's CUDA work (which runs on the
/// primary context through the runtime API) already shares an address space
/// with the effect, and one decoder + VRAM frame cache can serve both paths;
/// if not, device memory cannot cross between them and each needs its own.
///
/// cuDevicePrimaryCtxGetState is used first so the probe never CREATES a
/// primary context that was not already alive (that would cost VRAM); only
/// when one is active is it retained - briefly, to read its handle - and
/// released again.
void probeHostContext(CUcontext hostContext) noexcept {
    try {
        static std::atomic<bool> done{false};
        if (!hostContext || done.exchange(true)) {
            return;
        }
        ContextScope scope(hostContext);
        if (!scope.ok()) {
            return;
        }
        CUdevice device = 0;
        if (cuCtxGetDevice(&device) != CUDA_SUCCESS) {
            return;
        }
        unsigned int flags = 0;
        int active = 0;
        if (cuDevicePrimaryCtxGetState(device, &flags, &active) != CUDA_SUCCESS) {
            return;
        }
        unsigned int apiVersion = 0;
        (void)cuCtxGetApiVersion(hostContext, &apiVersion);
        if (!active) {
            PluginLog::info("reframe/gpu/source: host CUDA context {} on device {} (api {}); the device's primary "
                            "context is NOT active, so the host context is a private one",
                            static_cast<const void*>(hostContext), static_cast<int>(device), apiVersion);
            return;
        }
        CUcontext primary = nullptr;
        if (cuDevicePrimaryCtxRetain(&primary, device) != CUDA_SUCCESS) {
            return;
        }
        PluginLog::info("reframe/gpu/source: host CUDA context {} on device {} (api {}) {} the primary context {} "
                        "(flags 0x{:x})",
                        static_cast<const void*>(hostContext), static_cast<int>(device), apiVersion,
                        primary == hostContext ? "IS" : "is NOT", static_cast<const void*>(primary), flags);
        (void)cuDevicePrimaryCtxRelease(device);
    } catch (...) {
        // Diagnostics must never take the effect down.
    }
}

/// Log the sequence's working colour space - the space the frames an effect
/// receives, and must return, are expressed in.  A direct render from the
/// fisheyes bypasses Premiere's source -> working conversion, so it has to
/// produce this space itself: the SEI codes say which transfer and primaries,
/// and the graphics-white / tone-map / SDR-gamma settings say how Premiere
/// scales between HDR and SDR.  Diagnostic only.
void probeWorkingColorSpace(const Instance& inst) noexcept {
    try {
        // GetWorkingColorSpace and the three settings after it sit at the end
        // of the v9 function table; reading them from an older host's shorter
        // table would read past it.
        if (!inst.sequence || inst.sequenceVersion < 9 || !inst.sequence->GetWorkingColorSpace) {
            PluginLog::info("reframe/gpu/source: the Sequence Info Suite (v{}) cannot report the working colour space",
                            inst.sequenceVersion);
            return;
        }
        PrSDKColorSpaceID id{};
        const prSuiteError idErr = inst.sequence->GetWorkingColorSpace(inst.timelineId, &id);
        csSDK_uint32 white = 0;
        prBool toneMap = kPrFalse;
        csSDK_uint32 gamma = 0;
        const prSuiteError whiteErr =
            inst.sequence->GetGraphicsWhiteLuminance ? inst.sequence->GetGraphicsWhiteLuminance(inst.timelineId, &white)
                                                     : suiteError_NotImplemented;
        const prSuiteError toneErr =
            inst.sequence->GetAutoToneMapEnabled ? inst.sequence->GetAutoToneMapEnabled(inst.timelineId, &toneMap)
                                                 : suiteError_NotImplemented;
        const prSuiteError gammaErr = inst.sequence->GetSDRGamma ? inst.sequence->GetSDRGamma(inst.timelineId, &gamma)
                                                                 : suiteError_NotImplemented;

        // Resolve the opaque id through the Color Management Suite.
        PrSDKColorSpaceType type = kPrSDKColorSpaceType_Undefined;
        prSEIColorCodesRec sei;
        prSuiteError typeErr = suiteError_NotImplemented;
        prSuiteError seiErr = suiteError_NotImplemented;
        if (const PrSDKColorManagementSuite* cm = acquire<PrSDKColorManagementSuite>(
                inst.basic, kPrSDKColorManagementSuite, kPrSDKColorManagementSuiteVersion)) {
            if (idErr == suiteError_NoError && cm->GetColorSpaceTypeForColorSpace) {
                typeErr = cm->GetColorSpaceTypeForColorSpace(&id, &type);
            }
            if (idErr == suiteError_NoError && cm->GetSEIColorCodesForColorSpace) {
                seiErr = cm->GetSEIColorCodesForColorSpace(&id, &sei);
            }
            releaseSuite(inst.basic, kPrSDKColorManagementSuite, kPrSDKColorManagementSuiteVersion);
        }
        PluginLog::info("reframe/gpu/source: working colour space id err {} type {} (err {}); SEI primaries {} "
                        "transfer {} matrix {} bits {} full {} rgb {} scene {} (err {}); graphics white {} nits "
                        "(err {}), auto tone map {} (err {}), SDR gamma {} (err {})",
                        idErr, static_cast<int>(type), typeErr, sei.colorPrimariesCode,
                        sei.transferCharacteristicCode, sei.matrixEquationsCode, sei.bitDepth,
                        static_cast<int>(sei.isFullRange), static_cast<int>(sei.isRGB),
                        static_cast<int>(sei.isSceneReferred), seiErr, white, whiteErr, static_cast<int>(toneMap),
                        toneErr, gamma, gammaErr);
    } catch (...) {
        // Diagnostics must never take the effect down.
    }
}

void probeSourceGraph(const Instance& inst) noexcept {
    try {
        static std::atomic<bool> done{false};
        if (done.exchange(true)) {
            return;
        }
        const PrSDKVideoSegmentSuite* s = inst.segment;
        if (!s || inst.segmentVersion < kPrSDKVideoSegmentSuiteVersion6 || !s->AcquireOperatorOwnerNodeID ||
            !s->ReleaseVideoNodeID) {
            PluginLog::info("reframe/gpu/source: the Video Segment Suite (v{}) cannot walk to the owner node",
                            inst.segmentVersion);
            return;
        }
        logNode(*s, inst.nodeId, "effect");

        csSDK_int32 owner = 0;
        const prSuiteError ownerErr = s->AcquireOperatorOwnerNodeID(inst.nodeId, &owner);
        if (ownerErr != suiteError_NoError || owner == 0) {
            PluginLog::info("reframe/gpu/source: AcquireOperatorOwnerNodeID failed ({})", ownerErr);
            return;
        }
        logNode(*s, owner, "owner");

        // The owner's inputs: for a clip node, the media node.  Two levels
        // deep covers a clip whose input is itself wrapped (multicam, nest).
        csSDK_int32 inputs = 0;
        if (s->GetNodeInputCount && s->GetNodeInputCount(owner, &inputs) == suiteError_NoError &&
            s->AcquireInputNodeID) {
            for (csSDK_int32 i = 0; i < std::min<csSDK_int32>(inputs, 4); ++i) {
                PrTime offset = 0;
                csSDK_int32 input = 0;
                if (s->AcquireInputNodeID(owner, i, &offset, &input) != suiteError_NoError || input == 0) {
                    continue;
                }
                logNode(*s, input, "input");
                csSDK_int32 nested = 0;
                if (s->GetNodeInputCount && s->GetNodeInputCount(input, &nested) == suiteError_NoError) {
                    for (csSDK_int32 j = 0; j < std::min<csSDK_int32>(nested, 4); ++j) {
                        PrTime nestedOffset = 0;
                        csSDK_int32 grand = 0;
                        if (s->AcquireInputNodeID(input, j, &nestedOffset, &grand) == suiteError_NoError &&
                            grand != 0) {
                            logNode(*s, grand, "input-of-input");
                            s->ReleaseVideoNodeID(grand);
                        }
                    }
                }
                s->ReleaseVideoNodeID(input);
            }
        }
        // Clip time 0 through the owner's time transform: the media time the
        // first frame of the clip maps to (in point, speed, reverse applied).
        if (s->TransformNodeTime) {
            PrTime media = 0;
            const prSuiteError terr = s->TransformNodeTime(owner, 0, &media);
            PluginLog::info("reframe/gpu/source: TransformNodeTime(owner, 0) -> {} (err {})",
                            static_cast<long long>(media), terr);
        }
        s->ReleaseVideoNodeID(owner);

        probeWorkingColorSpace(inst);
    } catch (...) {
        // Diagnostics must never take the effect down.
    }
}

void probeParams(Instance& inst) noexcept {
    if (!inst.segment || !inst.segment->GetParamCount || !inst.segment->GetParam) {
        PluginLog::oncef("reframe/gpu/probe-nosuite", PluginLog::Level::Warn,
                         "reframe/gpu: the Video Segment Suite has no GetParamCount/GetParam; "
                         "using the static parameter mapping");
        return;
    }

    csSDK_int32 hostCount = 0;
    if (inst.segment->GetParamCount(inst.nodeId, &hostCount) != suiteError_NoError) {
        PluginLog::oncef("reframe/gpu/probe-count", PluginLog::Level::Warn,
                         "reframe/gpu: GetParamCount failed; using the static parameter mapping");
        return;
    }
    // Host-supplied, therefore validated: a negative count is garbage, and a
    // zero count is a node that exposes nothing to identify.
    if (hostCount <= 0) {
        PluginLog::oncef("reframe/gpu/probe-empty", PluginLog::Level::Warn,
                         "reframe/gpu: the host reports {} parameters; using the static parameter mapping",
                         hostCount);
        return;
    }

    // Read every entry the host admits to, but never more than our whole AE
    // list (group markers included) can account for: that is the longest
    // list either layout can be, so a longer one is not ours and there is no
    // reason to pay for the extra calls.  The array is sized by the same
    // constant, so the bound is structural.
    HostParamKind kinds[kParamCount] = {};
    const int probeCount = (hostCount > kParamCount) ? kParamCount : static_cast<int>(hostCount);
    std::string dump;
    dump.reserve(384);
    for (int i = 0; i < probeCount; ++i) {
        PrParam p{};
        // GetParam on a freshly created node fails INTERMITTENTLY: observed
        // on a live host (26.2.2) failing for a different subset of indices
        // on every CreateInstance, most often the angle controls, while the
        // same indices read fine moments later.  Treating one failure as a
        // type would poison the signature and send the whole effect back to
        // the static mapping - which is exactly what happened in the field:
        // playback (a lucky instance) animated while scrubbing (an unlucky
        // one) did not.  A few immediate retries cost nothing and turn an
        // intermittent read into a reliable one.
        constexpr int kReadAttempts = 8;
        prSuiteError readErr = suiteError_Fail;
        for (int attempt = 0; attempt < kReadAttempts; ++attempt) {
            std::memset(&p, 0, sizeof(p));
            readErr = inst.segment->GetParam(inst.nodeId, i, 0, &p);
            if (readErr == suiteError_NoError && kindOf(p) != HostParamKind::Unknown) {
                break;
            }
            // Yield rather than spin: whatever the host is still finishing
            // needs a moment, not CPU contention from this thread.
            std::this_thread::yield();
        }
        if (readErr != suiteError_NoError) {
            kinds[i] = HostParamKind::Unknown;
            dump += std::format("[{}]=<err> ", i);
            continue;
        }
        kinds[i] = kindOf(p);
        // The value is logged purely so a human reading the diagnostic can
        // sanity-check the identification; nothing here depends on it.
        switch (p.mType) {
            case kPrParamType_Float32: dump += std::format("[{}]f32:{:.3f} ", i, p.mFloat32); break;
            case kPrParamType_Float64: dump += std::format("[{}]f64:{:.3f} ", i, p.mFloat64); break;
            case kPrParamType_Int32:   dump += std::format("[{}]i32:{} ", i, p.mInt32); break;
            case kPrParamType_Bool:    dump += std::format("[{}]bool:{} ", i, p.mBool ? 1 : 0); break;
            default:                   dump += std::format("[{}]type{} ", i, static_cast<int>(p.mType)); break;
        }
    }

    // The one-time dump: the ground truth this whole mechanism was built
    // from.  Logged whatever the outcome, because it is just as useful when
    // the probe SUCCEEDS (it shows which controls the host hid) as when it
    // fails (it shows what to teach the matcher next).
    PluginLog::oncef("reframe/gpu/paramdump", PluginLog::Level::Info,
                     "reframe/gpu: host parameter dump at t=0 ({} of {} entries, we added {}): {}", probeCount,
                     hostCount, OSV_REFRAME_PARAM_COUNT, dump);

    // ---- identify the layout ---------------------------------------------------
    // The two layouts cannot be confused: the verbatim one is exactly
    // kParamCount entries long, the compact one at most kValueParamCount.
    // Anything else is a list nobody has seen yet, and guessing at it would
    // mean reading someone else's controls.
    HostParamMap probed{};
    const char* layout = nullptr;
    if (matchVerbatimLayout(kinds, probeCount, static_cast<int>(hostCount), &probed)) {
        layout = "verbatim (host index = AE index - 1, group markers included)";
    } else if (hostCount <= kValueParamCount && matchHostParams(kinds, probeCount, &probed)) {
        layout = "compact (group markers dropped)";
    }
    if (!layout) {
        PluginLog::oncef("reframe/gpu/probe-nomatch", PluginLog::Level::Error,
                         "reframe/gpu: the host reports {} parameters and their types do not match this effect's "
                         "signature ({} entries including group markers, {} without); falling back to the static "
                         "mapping (AE index - 1), which may read the wrong control",
                         hostCount, kParamCount, kValueParamCount);
        return;
    }

    inst.paramMap = probed;
    inst.paramMapProbed = true;

    // Which AE index reads which host entry, straight from the tables, so a
    // control added to ReframeParams.h shows up here without an edit.
    std::string pairs;
    pairs.reserve(8 * kValueParamCount);
    for (int i = 0; i < kValueParamCount; ++i) {
        const int aeIndex = kValueParamAeIndex[i];
        pairs += std::format("{}->{} ", aeIndex, probed[aeIndex]);
    }
    PluginLog::oncef("reframe/gpu/probe-ok", PluginLog::Level::Info,
                     "reframe/gpu: probed the host parameter mapping from {} entries, {} layout - AE index -> host "
                     "index: {}(-1 = not exposed by the host)",
                     hostCount, layout, pairs);
}

/// An angle control: PF_ADD_ANGLE arrives as mFloat32 degrees.  Other types
/// are accepted defensively (a host that changed its mind about the union
/// member must not silently give us zero).
double readAngle(const Instance& inst, int aeIndex, PrTime time, double fallback) noexcept {
    PrParam p{};
    if (!readParam(inst, aeIndex, time, &p)) {
        return fallback;
    }
    switch (p.mType) {
        case kPrParamType_Float32:
            return static_cast<double>(p.mFloat32);
        case kPrParamType_Float64:
            return p.mFloat64;
        case kPrParamType_Int32:
            return static_cast<double>(p.mInt32);
        default:
            return fallback;
    }
}

/// A float slider: PF_ADD_FLOAT_SLIDERX arrives as mFloat64.
double readFloat(const Instance& inst, int aeIndex, PrTime time, double fallback) noexcept {
    PrParam p{};
    if (!readParam(inst, aeIndex, time, &p)) {
        return fallback;
    }
    switch (p.mType) {
        case kPrParamType_Float64:
            return p.mFloat64;
        case kPrParamType_Float32:
            return static_cast<double>(p.mFloat32);
        default:
            return fallback;
    }
}

/// A popup: mInt32, as the host numbers it - which on the GPU side need not
/// be 1-based; readSettings() decodes it with decodeHostPopup().  Returns
/// false (and leaves `out` alone) when the host did not answer with an
/// integer, so a caller can tell a real reading from its own fallback: only
/// a real reading may be decoded or teach the instance anything.
bool readPopupRaw(const Instance& inst, int aeIndex, PrTime time, int* out) noexcept {
    if (!out) {
        return false;
    }
    PrParam p{};
    if (!readParam(inst, aeIndex, time, &p)) {
        return false;
    }
    switch (p.mType) {
        case kPrParamType_Int32:
            *out = p.mInt32;
            return true;
        case kPrParamType_Int16:
            *out = static_cast<int>(p.mInt16);
            return true;
        case kPrParamType_Int8:
            *out = static_cast<int>(p.mInt8);
            return true;
        default:
            return false;
    }
}

/// A checkbox: mBool.
bool readBool(const Instance& inst, int aeIndex, PrTime time, bool fallback) noexcept {
    PrParam p{};
    if (!readParam(inst, aeIndex, time, &p)) {
        return fallback;
    }
    switch (p.mType) {
        case kPrParamType_Bool:
            return p.mBool != 0;
        case kPrParamType_Int32:
            return p.mInt32 != 0;
        default:
            return fallback;
    }
}

/// Read every control at `time`, applying the "Smooth Keyframes" average
/// over t-1, t and t+1 frames to the six angle dials when it is on.
///
/// Averaging the ANGLES (not the frames) is what makes the smoothing cheap:
/// it needs no extra input frames, so GetFrameDependencies can keep saying
/// "only the current frame", and it produces the same numbers as the CPU
/// path, which does the same three-sample average through PF_CHECKOUT_PARAM.
Settings readSettings(const Instance& inst, PrTime clipTime, PrTime ticksPerFrame) noexcept {
    Settings s;

    // ---- the popups, in the host's own numbering -------------------------------
    // [WP-CAMERA] Premiere hands GPU filters popups numbered from 0 where the
    // CPU path (and the mock host) number them from 1 (PopupBase in
    // ReframeParams.h).  Both raw values are read FIRST and both are allowed
    // to settle the base before either is decoded, so a Preset reading 0 on
    // this very frame already corrects an ambiguous Output Resolution.  A
    // control the host did not answer takes its documented (1-based) default
    // directly: it was never in the host's numbering, so it is neither
    // decoded nor allowed to teach the instance anything.
    int rawResolution = 0;
    int rawPreset = 0;
    const bool haveResolution = readPopupRaw(inst, kIndexOutputResolution, clipTime, &rawResolution);
    const bool havePreset = readPopupRaw(inst, kIndexPreset, clipTime, &rawPreset);
    PopupBase base = static_cast<PopupBase>(inst.popupBase.load(std::memory_order_relaxed));
    if (haveResolution) {
        (void)decodeHostPopup(rawResolution, OSV_REFRAME_RESOLUTION_COUNT, &base);
    }
    if (havePreset) {
        (void)decodeHostPopup(rawPreset, OSV_REFRAME_PRESET_COUNT, &base);
    }
    const PopupBase learned = base;
    s.resolution = sanitiseResolution(haveResolution
                                          ? decodeHostPopup(rawResolution, OSV_REFRAME_RESOLUTION_COUNT, &base)
                                          : OSV_REFRAME_RESOLUTION_DEFAULT);
    s.preset = sanitisePreset(havePreset ? decodeHostPopup(rawPreset, OSV_REFRAME_PRESET_COUNT, &base)
                                         : OSV_REFRAME_PRESET_DEFAULT);
    if (learned != PopupBase::Unknown) {
        const int previous = inst.popupBase.exchange(static_cast<int>(learned), std::memory_order_relaxed);
        if (previous != static_cast<int>(learned)) {
            PluginLog::info("reframe/gpu: this host numbers popups from {} (Output Resolution read {}, Preset {})",
                            learned == PopupBase::Zero ? 0 : 1, rawResolution, rawPreset);
        }
    }

    s.fovDeg = readFloat(inst, kIndexFov, clipTime, OSV_REFRAME_FOV_DEFAULT);
    s.distortion = readFloat(inst, kIndexDistortion, clipTime, OSV_REFRAME_DISTORTION_DEFAULT);
    s.smoothKeyframes = readBool(inst, kIndexSmooth, clipTime, false);

    // ---- [WP-CAMERA] DJI's camera ----------------------------------------------
    // Camera Model is a checkbox, so it reads the same on every host; a host
    // that does not expose it (or a probe that mapped it to nothing) yields
    // Classic, the lens every project had before the control existed.  Zoom
    // and Drag Sensitivity are never rendered from but are read so the
    // Settings block is complete for the log line on a rejected setup.
    s.cameraModel = cameraModelFromCheckbox(
        readBool(inst, kIndexCameraModel, clipTime, OSV_REFRAME_CAMERA_MODEL_DEFAULT != 0) ? 1 : 0);
    s.zoomDeg = readFloat(inst, kIndexZoom, clipTime, OSV_REFRAME_ZOOM_DEFAULT);
    s.djiFovDeg = readFloat(inst, kIndexDjiFov, clipTime, OSV_REFRAME_DJI_FOV_DEFAULT);
    s.correction = readFloat(inst, kIndexCorrection, clipTime, OSV_REFRAME_CORRECTION_DEFAULT);
    s.dragSensitivity = readFloat(inst, kIndexDragSensitivity, clipTime, OSV_REFRAME_DRAG_SENSITIVITY_DEFAULT);

    // The six angles, either sampled once or averaged over three frames.
    const int angleIndices[6] = {kIndexPan,       kIndexTilt,       kIndexRoll,
                                 kIndexSourcePan, kIndexSourceTilt, kIndexSourceRoll};
    double angles[6] = {0, 0, 0, 0, 0, 0};

    // Smoothing needs a frame duration; without one (a host that could not
    // tell us) it degrades to no smoothing rather than to a wrong average.
    const bool smooth = s.smoothKeyframes && ticksPerFrame > 0;
    for (int i = 0; i < 6; ++i) {
        const double centre = readAngle(inst, angleIndices[i], clipTime, 0.0);
        if (!smooth) {
            angles[i] = centre;
            continue;
        }
        // Clamp the neighbours to non-negative clip time: asking before the
        // clip start returns the first keyframe on a real host, but a
        // negative PrTime is not something every host is happy with.
        const PrTime before = (clipTime > ticksPerFrame) ? (clipTime - ticksPerFrame) : 0;
        const PrTime after = clipTime + ticksPerFrame;
        const double prev = readAngle(inst, angleIndices[i], before, centre);
        const double next = readAngle(inst, angleIndices[i], after, centre);
        angles[i] = (prev + centre + next) / 3.0;
    }

    s.panDeg = angles[0];
    s.tiltDeg = angles[1];
    s.rollDeg = angles[2];
    s.sourcePanDeg = angles[3];
    s.sourceTiltDeg = angles[4];
    s.sourceRollDeg = angles[5];
    return s;
}

/// Pixel size of the sequence, or an invalid size when the suite cannot tell
/// us (the caller then falls back to the output frame's own size).
///
/// The GPU instance already holds the timeline id and the suite, so unlike
/// the CPU path this needs no acquire / release dance.
SizePx sequenceSize(const Instance& inst) noexcept {
    if (!inst.sequence || !inst.sequence->GetFrameRect) {
        return SizePx{};
    }
    prRect rect{};
    if (inst.sequence->GetFrameRect(inst.timelineId, &rect) != suiteError_NoError) {
        return SizePx{};
    }
    // Host-supplied, therefore validated: an inverted or absurd rectangle is
    // reported as "unknown" rather than carried into the camera.
    const long long w = static_cast<long long>(rect.right) - static_cast<long long>(rect.left);
    const long long h = static_cast<long long>(rect.bottom) - static_cast<long long>(rect.top);
    if (w <= 0 || h <= 0 || w > kMaxSequenceEdge || h > kMaxSequenceEdge) {
        return SizePx{};
    }
    return SizePx{static_cast<int>(w), static_cast<int>(h)};
}

// ===========================================================================
//  PPix inspection
// ===========================================================================

/// Everything we need to know about one GPU frame.
struct GpuFrame {
    void* data = nullptr;
    std::int32_t rowBytes = 0;
    int width = 0;
    int height = 0;
    bool isHalf = false;
    bool valid = false;
};

/// Query a GPU PPix through the PPix and GPU Device suites.
GpuFrame inspectFrame(const Instance& inst, PPixHand hand) noexcept {
    GpuFrame f;
    if (!hand || !inst.ppix || !inst.gpu) {
        return f;
    }
    if (!inst.ppix->GetBounds || !inst.ppix->GetRowBytes || !inst.ppix->GetPixelFormat || !inst.gpu->GetGPUPPixData) {
        return f;
    }

    void* data = nullptr;
    if (inst.gpu->GetGPUPPixData(hand, &data) != suiteError_NoError || !data) {
        return f;
    }
    csSDK_int32 rowBytes = 0;
    if (inst.ppix->GetRowBytes(hand, &rowBytes) != suiteError_NoError || rowBytes <= 0) {
        return f;
    }
    prRect bounds{};
    if (inst.ppix->GetBounds(hand, &bounds) != suiteError_NoError) {
        return f;
    }
    PrPixelFormat format = PrPixelFormat_Invalid;
    if (inst.ppix->GetPixelFormat(hand, &format) != suiteError_NoError) {
        return f;
    }
    if (format != PrPixelFormat_GPU_BGRA_4444_32f && format != PrPixelFormat_GPU_BGRA_4444_16f) {
        // "Result must be in the same pixel format as the input"
        // (PrSDKGPUFilter.h) and only these two GPU formats exist.
        return f;
    }

    f.data = data;
    f.rowBytes = static_cast<std::int32_t>(rowBytes);
    f.width = static_cast<int>(bounds.right - bounds.left);
    f.height = static_cast<int>(bounds.bottom - bounds.top);
    f.isHalf = (format == PrPixelFormat_GPU_BGRA_4444_16f);
    // A pitch that cannot hold one row means the header is wrong; refuse it
    // rather than walk off the allocation.
    const std::size_t bpp = f.isHalf ? 8u : 16u;
    f.valid = f.width > 0 && f.height > 0 &&
              static_cast<std::size_t>(f.rowBytes) >= static_cast<std::size_t>(f.width) * bpp;
    return f;
}

// ===========================================================================
//  PrGPUFilter callbacks
// ===========================================================================

prSuiteError createInstance(PrGPUFilterInstance* io) noexcept {
    try {
        if (!io || !io->piSuites || !io->piSuites->utilFuncs || !io->piSuites->utilFuncs->getSPBasicSuite) {
            return suiteError_InvalidParms;
        }
        SPBasicSuite* basic = io->piSuites->utilFuncs->getSPBasicSuite();
        if (!basic) {
            return suiteError_InvalidParms;
        }

        Instance* inst = new (std::nothrow) Instance();
        if (!inst) {
            return suiteError_OutOfMemory;
        }
        inst->suites = io->piSuites;
        inst->basic = basic;
        inst->deviceIndex = io->inDeviceIndex;
        inst->timelineId = io->inTimelineID;
        inst->nodeId = io->inNodeID;

        // ---- the device -------------------------------------------------
        inst->gpu = acquire<PrSDKGPUDeviceSuite>(basic, kPrSDKGPUDeviceSuite, kPrSDKGPUDeviceSuiteVersion);
        if (!inst->gpu || !inst->gpu->GetDeviceInfo) {
            PluginLog::warn("reframe/gpu: no GPU Device Suite; rendering in software");
            delete inst;
            return suiteError_Fail;
        }

        PrGPUDeviceInfo info{};
        if (inst->gpu->GetDeviceInfo(kPrSDKGPUDeviceSuiteVersion, io->inDeviceIndex, &info) != suiteError_NoError) {
            PluginLog::warn("reframe/gpu: GetDeviceInfo failed for device {}", io->inDeviceIndex);
            releaseSuite(basic, kPrSDKGPUDeviceSuite, kPrSDKGPUDeviceSuiteVersion);
            delete inst;
            return suiteError_Fail;
        }

        // CUDA only.  OpenCL was dropped by Premiere in 15.4, Metal is Mac
        // and DirectX is still unreleased for third parties; returning an
        // error here makes the host render this node in software, which is
        // exactly the documented fallback (PrSDKGPUFilter.h:167-170).
        if (info.outDeviceFramework != PrGPUDeviceFramework_CUDA) {
            PluginLog::info("reframe/gpu: device {} is not CUDA (framework {}); using the CPU path",
                            io->inDeviceIndex, static_cast<int>(info.outDeviceFramework));
            releaseSuite(basic, kPrSDKGPUDeviceSuite, kPrSDKGPUDeviceSuiteVersion);
            delete inst;
            return suiteError_Fail;
        }
        if (!info.outMeetsMinimumRequirementsForAcceleration) {
            PluginLog::info("reframe/gpu: device {} does not meet the acceleration minimum; using the CPU path",
                            io->inDeviceIndex);
            releaseSuite(basic, kPrSDKGPUDeviceSuite, kPrSDKGPUDeviceSuiteVersion);
            delete inst;
            return suiteError_Fail;
        }

        inst->context = static_cast<CUcontext>(info.outContextHandle);
        inst->stream = static_cast<CUstream>(info.outCommandQueueHandle);
        if (!inst->context) {
            PluginLog::warn("reframe/gpu: the host reported a CUDA device with no context");
            releaseSuite(basic, kPrSDKGPUDeviceSuite, kPrSDKGPUDeviceSuiteVersion);
            delete inst;
            return suiteError_Fail;
        }
        probeHostContext(inst->context);

        // ---- the kernel -------------------------------------------------
        inst->kernel = acquireKernel(io->inDeviceIndex, inst->context);
        if (!inst->kernel) {
            releaseSuite(basic, kPrSDKGPUDeviceSuite, kPrSDKGPUDeviceSuiteVersion);
            delete inst;
            return suiteError_Fail;
        }

        // ---- the remaining suites ---------------------------------------
        inst->ppix = acquire<PrSDKPPixSuite>(basic, kPrSDKPPixSuite, kPrSDKPPixSuiteVersion);
        if (!inst->ppix) {
            PluginLog::warn("reframe/gpu: no PPix Suite; rendering in software");
            releaseSuite(basic, kPrSDKGPUDeviceSuite, kPrSDKGPUDeviceSuiteVersion);
            delete inst;
            return suiteError_Fail;
        }

        // Only GetParam is used and it exists since v4; acquire the newest
        // the host has so a future host does not silently give us an old
        // table, but never fail over a missing high version.
        inst->segment = acquireFirst<PrSDKVideoSegmentSuite>(
            basic, kPrSDKVideoSegmentSuite,
            {kPrSDKVideoSegmentSuiteVersion9, kPrSDKVideoSegmentSuiteVersion8, kPrSDKVideoSegmentSuiteVersion7,
             kPrSDKVideoSegmentSuiteVersion6},
            &inst->segmentVersion);
        if (!inst->segment) {
            PluginLog::warn("reframe/gpu: no Video Segment Suite; parameters cannot be read, rendering in software");
            releaseSuite(basic, kPrSDKPPixSuite, kPrSDKPPixSuiteVersion);
            releaseSuite(basic, kPrSDKGPUDeviceSuite, kPrSDKGPUDeviceSuiteVersion);
            delete inst;
            return suiteError_Fail;
        }

        // Optional: without it "Match Sequence" falls back to 16:9.
        inst->sequence = acquireFirst<PrSDKSequenceInfoSuite>(basic, kPrSDKSequenceInfoSuite,
                                                              {kPrSDKSequenceInfoSuiteVersion, 8, 7, 6, 5},
                                                              &inst->sequenceVersion);

        // Discover the host's parameter index space, once per instance.
        //
        // gpuParamIndex() encodes the documented rule, "AE index - 1"
        // (PrGPUFilterModule.h:153), which assumes the host's GetParam index
        // space is the list After Effects built, group markers included.
        // Premiere Pro 26.2 disproves that: this effect adds 15 parameters
        // (11 controls + 4 group markers) and GetParamCount answers 8 - the
        // markers are dropped AND the three controls inside the collapsed
        // "Source" group are not exposed.  Under the static rule every read
        // past the first group landed on a neighbouring control, FOV came
        // back as garbage and the render bailed out entirely.
        //
        // probeParams() asks the host what it really has and identifies each
        // control by its PrParam type, so the mapping is measured rather than
        // assumed.  It is deliberately non-fatal: a host it cannot identify
        // leaves the static mapping in place, which is exactly the behaviour
        // that existed before, and says so in the log.
        probeParams(*inst);
        probeSourceGraph(*inst);

        // ---- the direct path ---------------------------------------------
        // Bind this instance to its source file and learn the working
        // colour space once, here, rather than per frame.  Everything is
        // best effort: an instance that cannot bind simply keeps rendering
        // from the equirect it is handed.
        if (osv::reframe::direct::engine().ok()) {
            inst->source = osv::reframe::direct::resolveSource(inst->segment, inst->segmentVersion, basic,
                                                              inst->nodeId);
            std::string colourReason;
            inst->directTransfer = osv::reframe::direct::workingTransfer(inst->sequence, inst->sequenceVersion, basic,
                                                                         inst->timelineId, colourReason);
            PluginLog::oncef("reframe/direct/bind", PluginLog::Level::Info,
                             "reframe/direct: source {} ({}); {} -> transfer {}",
                             inst->source.ok ? "bound" : "NOT bound",
                             inst->source.ok ? std::string("OSV clip") : inst->source.reason, colourReason,
                             inst->directTransfer);
        }

        io->ioPrivatePluginData = inst;
        // Reframing a 6K equirect into an HD frame is a couple of samples
        // per output pixel on the GPU; it plays back in real time.
        io->outIsRealtime = kPrTrue;

        PluginLog::info("reframe/gpu: instance on device {} (video segment v{}, sequence info v{})",
                        io->inDeviceIndex, inst->segmentVersion, inst->sequenceVersion);
        return suiteError_NoError;
    } catch (...) {
        // An exception must never cross back into Premiere's C stack.
        return suiteError_Fail;
    }
}

prSuiteError disposeInstance(PrGPUFilterInstance* io) noexcept {
    try {
        if (!io) {
            return suiteError_InvalidParms;
        }
        Instance* inst = static_cast<Instance*>(io->ioPrivatePluginData);
        io->ioPrivatePluginData = nullptr;
        if (!inst) {
            return suiteError_NoError;  // never created, or disposed twice
        }
        if (!inst->alive()) {
            PluginLog::error("reframe/gpu: DisposeInstance on a corrupt instance pointer");
            return suiteError_InvalidParms;
        }

        // Release exactly what was acquired, in reverse order.  The module
        // cache is NOT touched here: other instances on the same device
        // still use it and it is freed in the entry point's shutdown.
        SPBasicSuite* basic = inst->basic;
        if (inst->sequence) {
            releaseSuite(basic, kPrSDKSequenceInfoSuite, inst->sequenceVersion);
        }
        // The owner node the direct path holds must go back BEFORE the suite
        // it was acquired through.
        osv::reframe::direct::releaseSource(inst->segment, inst->source);
        if (inst->segment) {
            releaseSuite(basic, kPrSDKVideoSegmentSuite, inst->segmentVersion);
        }
        if (inst->ppix) {
            releaseSuite(basic, kPrSDKPPixSuite, kPrSDKPPixSuiteVersion);
        }
        if (inst->gpu) {
            releaseSuite(basic, kPrSDKGPUDeviceSuite, kPrSDKGPUDeviceSuiteVersion);
        }
        inst->magic = 0;
        delete inst;
        return suiteError_NoError;
    } catch (...) {
        return suiteError_Fail;
    }
}

/// We never need a frame other than the one at the current time: the
/// smoothing averages PARAMETERS, not pixels.  Returning NotImplemented is
/// how the SDK samples say "only the current frame".
prSuiteError getFrameDependencies(PrGPUFilterInstance*, const PrGPUFilterRenderParams*, csSDK_int32*,
                                  PrGPUFilterFrameDependency*) noexcept {
    return suiteError_NotImplemented;
}

/// No CPU pre-pass.
prSuiteError precompute(PrGPUFilterInstance*, const PrGPUFilterRenderParams*, csSDK_int32, PPixHand) noexcept {
    return suiteError_NotImplemented;
}

prSuiteError render(PrGPUFilterInstance* instanceData, const PrGPUFilterRenderParams* renderParams,
                    const PPixHand* inFrames, csSDK_size_t inFrameCount, PPixHand* outFrame) noexcept {
    try {
        // ---- argument checks --------------------------------------------
        if (!instanceData || !renderParams || !inFrames || !outFrame || inFrameCount < 1) {
            return suiteError_InvalidParms;
        }
        Instance* inst = static_cast<Instance*>(instanceData->ioPrivatePluginData);
        if (!inst || !inst->alive() || !inst->kernel || !inst->context) {
            return suiteError_InvalidParms;
        }

        const GpuFrame src = inspectFrame(*inst, inFrames[0]);
        const GpuFrame dst = inspectFrame(*inst, *outFrame);
        if (!src.valid || !dst.valid) {
            PluginLog::oncef("reframe/gpu/frame", PluginLog::Level::Error,
                             "reframe/gpu: unusable frame (src {}x{} valid={}, dst {}x{} valid={})", src.width,
                             src.height, src.valid, dst.width, dst.height, dst.valid);
            return suiteError_Fail;
        }
        // Once per process: what the GPU path is actually handed, and the two
        // clocks, so the clip-time -> media-frame mapping the direct renderer
        // needs can be checked against a real host.
        PluginLog::oncef("reframe/gpu/first-frame", PluginLog::Level::Info,
                         "reframe/gpu: first GPU frame - src {}x{} {}, dst {}x{} {}, clip time {}, sequence time {}, "
                         "quality {}, downsample {:.3f}x{:.3f}, ticks/frame {}, host stream {}",
                         src.width, src.height, src.isHalf ? "16f" : "32f", dst.width, dst.height,
                         dst.isHalf ? "16f" : "32f", static_cast<long long>(renderParams->inClipTime),
                         static_cast<long long>(renderParams->inSequenceTime),
                         static_cast<int>(renderParams->inQuality), renderParams->inDownsampleFactorX,
                         renderParams->inDownsampleFactorY, static_cast<long long>(renderParams->inRenderTicksPerFrame),
                         static_cast<const void*>(inst->stream));

        // The host hands us an output in the same format as the input; if it
        // ever did not, writing half into a float buffer would corrupt it.
        if (src.isHalf != dst.isHalf) {
            PluginLog::error("reframe/gpu: input and output pixel formats differ");
            return suiteError_Fail;
        }

        // ---- parameters --------------------------------------------------
        // Retry the probe if CreateInstance could not identify the host's
        // index space.  GetParam fails intermittently on a node the host has
        // only just built, and an instance that gave up at creation would
        // read the wrong controls for as long as it lived - the field
        // symptom being that playback animated (an instance whose probe had
        // got lucky) while scrubbing did not.  Reaching Render proves the
        // node is ready, so this is the moment a retry succeeds.
        if (!inst->paramMapProbed) {
            probeParams(*inst);
        }
        const Settings settings = readSettings(*inst, renderParams->inClipTime, renderParams->inRenderTicksPerFrame);

        // The frame we render into is the one the host allocated; its size
        // is the render size, which may differ from the input's.
        ConstFrameView srcView;
        srcView.base = src.data;
        srcView.rowBytes = src.rowBytes;
        srcView.width = src.width;
        srcView.height = src.height;
        srcView.layout = src.isHalf ? PixelLayout::Bgra16f : PixelLayout::Bgra32f;
        srcView.topDown = true;  // "GPU Frames always have origin top left"

        const KernelSetup setup = buildParams(settings, srcView, dst.width, dst.height, sequenceSize(*inst));
        if (!setup.valid) {
            PluginLog::oncef("reframe/gpu/setup", PluginLog::Level::Error,
                             "reframe/gpu: could not build the kernel parameters ({}x{} -> {}x{}): {}", src.width,
                             src.height, dst.width, dst.height, setupRejectName(setup.reject));
            return suiteError_Fail;
        }

        // ---- launch -------------------------------------------------------
        ContextScope scope(inst->context);
        if (!scope.ok()) {
            PluginLog::error("reframe/gpu: cuCtxPushCurrent failed at render time");
            return suiteError_Fail;
        }

        // ---- the direct path: straight from the fisheyes ----------------------
        // Sharper than sampling the equirect (one resampling instead of two,
        // at the fisheyes' own resolution) and independent of the equirect
        // size the importer was asked for.  Any failure falls through to the
        // equirect kernel below, which overwrites the whole output.
        if (!inst->directDisabled && inst->source.ok && inst->directTransfer >= 0 &&
            osv::reframe::direct::engine().ok()) {
            osv::reframe::direct::DirectRequest request;
            request.source = &inst->source;
            request.segment = inst->segment;
            request.clipTime = renderParams->inClipTime;
            request.transfer = inst->directTransfer;
            request.context = inst->context;
            request.kernel = directKernelFor(inst->deviceIndex, inst->context);
            request.settings = settings;
            request.output.data = dst.data;
            request.output.rowBytes = dst.rowBytes;
            request.output.width = dst.width;
            request.output.height = dst.height;
            request.output.isHalf = dst.isHalf;
            request.sequenceSize = sequenceSize(*inst);
            std::string reason;
            if (request.kernel && osv::reframe::direct::renderDirect(request, reason)) {
                PluginLog::oncef("reframe/direct/first", PluginLog::Level::Info,
                                 "reframe/direct: rendering straight from the fisheyes ({}x{} {})", dst.width,
                                 dst.height, dst.isHalf ? "16f" : "32f");
                instanceData->outIsRealtime = kPrTrue;
                return suiteError_NoError;
            }
            if (!request.kernel) {
                reason = "the fused kernel is not loaded";
            }
            // [WP-SETTINGS] A deliberate hand-over by the Source Settings rule
            // is not a failure: DirectPath logged it once for the change that
            // caused it, and a later change can make the clip eligible, so
            // the instance neither warns nor stops asking.
            if (!osv::reframe::direct::isPolicyFallback(reason)) {
                // Structural failures (the setup cannot express the view, the
                // engine cannot open the file, the ABI changed) will fail again
                // on every frame; stop trying for this instance.  Everything
                // else - a decode hiccup - may pass, so the next frame retries.
                const bool structural = reason.rfind("setup:", 0) == 0 ||
                                        reason.find("cannot open") != std::string::npos ||
                                        reason.find("layout") != std::string::npos ||
                                        reason.find("not loaded") != std::string::npos;
                if (structural) {
                    inst->directDisabled = true;
                }
                if (inst->directFailures < 5) {
                    ++inst->directFailures;
                    PluginLog::warn("reframe/direct: falling back to the equirect path for this frame{} - {}",
                                    structural ? " and this instance" : "", reason);
                }
            }
        }

        // buildParams() computed sourceRow0 as a HOST pointer arithmetic on
        // the device address; for a top-down frame that is the base itself,
        // which is what we pass. The kernel adds y * pitchBytes.
        const void* srcDevice = setup.sourceRow0;
        OsvReframeParams params = setup.params;
        OsvRgbaSource source = setup.source;
        void* dstDevice = dst.data;
        int dstRowBytes = dst.rowBytes;
        int dstIsHalf = dst.isHalf ? 1 : 0;

        void* args[] = {&params, &source, &srcDevice, &dstDevice, &dstRowBytes, &dstIsHalf};

        const unsigned gridX = (static_cast<unsigned>(dst.width) + kBlockDimX - 1u) / kBlockDimX;
        const unsigned gridY = (static_cast<unsigned>(dst.height) + kBlockDimY - 1u) / kBlockDimY;

        // ORDERING, on both sides of the kernel - the way Adobe's own CUDA
        // sample (GPUVideoFilter/Vignette/Vignette.cu) does it: launch on the
        // context's LEGACY default stream, then wait for it before handing
        // the frame back.
        //
        //  * Before: the legacy stream implicitly waits for all work already
        //    queued on the context's blocking streams, which is where the
        //    host uploads and converts our INPUT frame.  A launch on some
        //    other stream could start sampling an input that was still being
        //    written.
        //  * After: Render returning is the host's signal that the OUTPUT is
        //    ready.  The first real GPU session (the first ever, once the
        //    match-name binding was fixed) launched on the device's command
        //    queue and returned at once: the host consumed frames the kernel
        //    had not finished, and every row the kernel had not reached yet
        //    showed whatever stale VRAM the recycled buffer held - blocky
        //    garbage in the lower part of the view while panning.
        //
        // The wait costs the kernel's own run time (~0.3 ms for a 2560x1440
        // view, a few ms for a 6000x3000 frame) and nothing else: only this
        // stream is synchronised, not the whole context.
        const CUstream launchStream = CU_STREAM_LEGACY;
        CUresult r = cuLaunchKernel(inst->kernel, gridX, gridY, 1u, kBlockDimX, kBlockDimY, 1u, 0u, launchStream, args,
                                    nullptr);
        if (r != CUDA_SUCCESS) {
            PluginLog::error("reframe/gpu: {}", cudaMessage("cuLaunchKernel", r));
            return suiteError_Fail;
        }
        r = cuStreamSynchronize(launchStream);
        if (r != CUDA_SUCCESS) {
            // The kernel itself failed (a fault) or the context is broken; the
            // output cannot be trusted either way.
            PluginLog::error("reframe/gpu: {}", cudaMessage("cuStreamSynchronize", r));
            return suiteError_Fail;
        }

        instanceData->outIsRealtime = kPrTrue;
        return suiteError_NoError;
    } catch (...) {
        return suiteError_Fail;
    }
}

}  // namespace

// ===========================================================================
//  The exported entry point
//
//  Startup fills the function table and the match name; shutdown frees the
//  per-device modules.  ioIndex would be incremented if this module held
//  more than one GPU filter - it holds exactly one, so it is left alone and
//  a non-zero index is refused.
// ===========================================================================
extern "C" __declspec(dllexport) prSuiteError xGPUFilterEntry(csSDK_uint32 inHostInterfaceVersion,
                                                              csSDK_int32* ioIndex, prBool inStartup,
                                                              piSuitesPtr piSuites, PrGPUFilter* outFilter,
                                                              PrGPUFilterInfo* outFilterInfo) {
    try {
        // The host tells us which interface it speaks; we implement 2 and
        // nothing older, so an older host is declined cleanly.
        if (inHostInterfaceVersion < PrSDKGPUFilterInterfaceVersion2) {
            return suiteError_InvalidParms;
        }
        if (!ioIndex) {
            return suiteError_InvalidParms;
        }
        if (*ioIndex != 0) {
            // Exactly one GPU filter in this module.
            return suiteError_InvalidParms;
        }

        if (!inStartup) {
            // Shutdown: the contexts are still alive here, which is the only
            // safe moment to unload the modules.
            releaseKernels();
            PluginLog::info("reframe/gpu: shutdown");
            return suiteError_NoError;
        }

        if (!outFilter || !outFilterInfo) {
            return suiteError_InvalidParms;
        }

        // The log file is opened here rather than in DllMain: DllMain runs
        // under the loader lock and must not touch the file system.
        osv::premiere::PluginLog::init(L"Open360Reframe");

        outFilter->CreateInstance = &createInstance;
        outFilter->DisposeInstance = &disposeInstance;
        outFilter->GetFrameDependencies = &getFrameDependencies;
        outFilter->Precompute = &precompute;
        outFilter->Render = &render;

        outFilterInfo->outInterfaceVersion = PrSDKGPUFilterInterfaceVersion2;
        // outMatchName is left NULL, which makes the host bind this GPU
        // filter to the software effect declared by this module's own PiPL.
        //
        // It used to be set explicitly to OSV_REFRAME_MATCH_NAME, on the
        // belief that it was "the same string".  It is not: the header says
        // it "must be equal to a registered software filter", and Premiere
        // registers an After Effects-API effect under its PiPL match name
        // WITH an "AE." prefix - the SDK's own SDK_Segment_Utils.cpp compares
        // kVideoSegmentProperty_Effect_FilterMatchName against
        // "AE.ADBE Motion", and GoPro Reframe's GPU crashes are reported as
        // "AE.GoPro VR Reframe (GPUVideoFilter::CreateInstance)".  Our
        // explicit "OpenOSV.Open360Reframe" named a filter that does not
        // exist, so the GPU filter was bound to nothing: every recorded
        // Premiere session called xGPUFilterEntry at startup and never once
        // called CreateInstance, and the effect always rendered on the CPU
        // (the red render bar).  Adobe's GPUVideoFilter samples and the
        // shipping GoPro plug-in both leave this NULL; so does this one.
        outFilterInfo->outMatchName = PrSDKString();
        // The suites were only needed to allocate that string.
        (void)piSuites;

        PluginLog::info("reframe/gpu: startup, host interface version {}", inHostInterfaceVersion);
        return suiteError_NoError;
    } catch (...) {
        return suiteError_Fail;
    }
}
