// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 The OpenOSV Contributors
//
// GpuFilter.cpp - the xGPUFilterEntry side of Open 360 Reframe.
//
// Premiere binds a GPU renderer to a software effect BY MATCH NAME: the
// module exports xGPUFilterEntry, reports PrGPUFilterInfo with the same
// string EffectMain's PiPL carries, and from then on every frame the host
// can accelerate is routed here instead of to PF_Cmd_RENDER.
//
// Deliberate design choices, each with its reason:
//
//   * The module glue is written here rather than taken from the SDK's
//     GPUVideoFilter/Utils/PrGPUFilterModule.h.  That header pulls in
//     Boost.Preprocessor (through PrGPU/KernelSupport) and unconditionally
//     acquires PF_TransitionSuite, neither of which an effect needs; it is
//     also a C++ class hierarchy that would force our state into its shape.
//     The five function pointers of PrGPUFilter are trivial to fill by hand.
//
//   * CUDA is used STRICTLY through the driver API (cuda.h, nvcuda.dll).
//     The SDK guide ranks that first for compatibility (12.1.2) and it means
//     the .aex never loads a cudart DLL, so it cannot collide with the copy
//     Premiere itself ships.  The kernel comes from an embedded fatbin, not
//     from a linked device object, for the same reason.
//
//   * The host's CUcontext is pushed around every driver call.  The GPU
//     Device Suite says exclusive access is always held for a "full GPU
//     plug-in" and that the context is current on the render thread, but
//     CreateInstance is NOT documented to run on a render thread, and
//     pushing an already-current context is cheap and always correct.
//
//   * Modules are cached per device in a mutex-guarded static table, because
//     CreateInstance is called again on EVERY parameter change and loading a
//     fatbin per keyframe would dominate the render.
//
// Every extern "C" boundary catches (...): an exception unwinding into
// Premiere's C call stack is undefined behaviour and would take the host
// down with it.

#include "ReframeCpu.h"
#include "ReframeParams.h"

#include "PluginLog.h"

// Adobe headers are #pragma pack(push, 1); nothing of ours is declared while
// they are open.
#include "PrSDKGPUDeviceSuite.h"
#include "PrSDKGPUFilter.h"
#include "PrSDKMemoryManagerSuite.h"
#include "PrSDKPPix2Suite.h"
#include "PrSDKPPixSuite.h"
#include "PrSDKSequenceInfoSuite.h"
#include "PrSDKStringSuite.h"
#include "PrSDKVideoSegmentSuite.h"

#include <cuda.h>

#include <cstring>
#include <mutex>
#include <thread>
#include <new>
#include <string>

// ===========================================================================
//  The embedded fatbin
//
//  Generated by cmake/EmbedKernelScript.cmake from the fatbin nvcc produced
//  out of ReframeKernel.cu.  The generated translation unit defines these at
//  global scope with ordinary C++ linkage, so the declarations here are at
//  global scope too (an anonymous namespace would give them internal linkage
//  and the link would fail with an unresolved symbol).
// ===========================================================================
extern const unsigned char kOsvReframeFatbin[];
extern const std::size_t kOsvReframeFatbin_size;

namespace {

using osv::premiere::PluginLog;
using namespace osv::reframe;

/// Name the kernel is exported under (extern "C" in the .cu, so no
/// mangling).  A mismatch here is caught by the GPU test at load time.
constexpr const char* kKernelName = "osvReframeEquirectKernel";

/// Thread-block geometry.  16x16 is what every Adobe GPU sample uses and it
/// keeps a warp's 32 threads on two adjacent rows of the output, which is
/// the access pattern the equirect sampler likes.
constexpr unsigned kBlockDimX = 16;
constexpr unsigned kBlockDimY = 16;

/// Largest device table we keep.  Premiere enumerates at most a handful of
/// GPUs; 16 is generous and bounds the static state.
constexpr unsigned kMaxDevices = 16;

/// Largest sequence edge we will believe from the Sequence Info Suite.  See
/// the identical constant in EffectMain.cpp: a corrupt rectangle must become
/// "unknown", not a camera dimension.
constexpr long long kMaxSequenceEdge = 65536;

// ===========================================================================
//  Small helpers
// ===========================================================================

/// Turn a CUresult into something a log line can carry.
std::string cudaMessage(const char* what, CUresult result) {
    const char* name = nullptr;
    const char* text = nullptr;
    cuGetErrorName(result, &name);
    cuGetErrorString(result, &text);
    std::string s(what ? what : "cuda");
    s += ": ";
    s += name ? name : "CUDA_ERROR_UNKNOWN";
    if (text) {
        s += " (";
        s += text;
        s += ")";
    }
    return s;
}

/// RAII push/pop of a CUcontext.  Pushing the context that is already
/// current is legal and cheap; popping in the destructor guarantees the
/// thread is left exactly as Premiere handed it to us even on an early
/// return or an exception.
class ContextScope {
public:
    explicit ContextScope(CUcontext context) noexcept {
        if (!context) {
            return;
        }
        m_pushed = (cuCtxPushCurrent(context) == CUDA_SUCCESS);
    }
    ~ContextScope() {
        if (m_pushed) {
            CUcontext popped = nullptr;
            cuCtxPopCurrent(&popped);
        }
    }
    ContextScope(const ContextScope&) = delete;
    ContextScope& operator=(const ContextScope&) = delete;

    [[nodiscard]] bool ok() const noexcept { return m_pushed; }

private:
    bool m_pushed = false;
};

// ===========================================================================
//  Per-device module cache
//
//  cuModuleLoadFatBinary is expensive (it JITs for the device if no matching
//  cubin is present) and CreateInstance runs on every parameter change, so
//  one module per device is loaded once and kept until Shutdown.  The table
//  is keyed by the CUcontext as well as the device index: a host that
//  recreated its context would otherwise hand us a module belonging to a
//  destroyed context, which is undefined behaviour.
// ===========================================================================
struct DeviceModule {
    CUcontext context = nullptr;
    CUmodule module = nullptr;
    CUfunction kernel = nullptr;
    bool valid = false;
};

std::mutex g_moduleMutex;
DeviceModule g_modules[kMaxDevices];

/// Load (or fetch) the module for a device.  Caller must NOT hold the
/// context pushed - this function pushes it itself.  Returns nullptr on
/// failure, having logged the reason.
CUfunction acquireKernel(csSDK_uint32 deviceIndex, CUcontext context) noexcept {
    if (deviceIndex >= kMaxDevices || !context) {
        PluginLog::error("reframe/gpu: device index {} or context unusable", deviceIndex);
        return nullptr;
    }
    if (kOsvReframeFatbin_size == 0) {
        PluginLog::error("reframe/gpu: the embedded fatbin is empty - the build did not run nvcc");
        return nullptr;
    }

    std::lock_guard<std::mutex> lock(g_moduleMutex);
    DeviceModule& slot = g_modules[deviceIndex];
    if (slot.valid && slot.context == context && slot.kernel) {
        return slot.kernel;
    }

    // A stale entry (different context) is dropped without unloading: the
    // context it belonged to is gone, so cuModuleUnload would fail or worse.
    if (slot.valid && slot.context != context) {
        PluginLog::warn("reframe/gpu: device {} changed context, reloading the module", deviceIndex);
        slot = DeviceModule{};
    }

    ContextScope scope(context);
    if (!scope.ok()) {
        PluginLog::error("reframe/gpu: cuCtxPushCurrent failed for device {}", deviceIndex);
        return nullptr;
    }

    CUmodule module = nullptr;
    CUresult r = cuModuleLoadFatBinary(&module, kOsvReframeFatbin);
    if (r != CUDA_SUCCESS || !module) {
        PluginLog::error("reframe/gpu: {}", cudaMessage("cuModuleLoadFatBinary", r));
        return nullptr;
    }

    CUfunction kernel = nullptr;
    r = cuModuleGetFunction(&kernel, module, kKernelName);
    if (r != CUDA_SUCCESS || !kernel) {
        PluginLog::error("reframe/gpu: {}", cudaMessage("cuModuleGetFunction", r));
        cuModuleUnload(module);
        return nullptr;
    }

    slot.context = context;
    slot.module = module;
    slot.kernel = kernel;
    slot.valid = true;
    PluginLog::info("reframe/gpu: loaded the reframe kernel on device {} ({} bytes of fatbin)", deviceIndex,
                    kOsvReframeFatbin_size);
    return kernel;
}

/// Unload every cached module.  Called from the entry point's shutdown
/// phase, which is the only moment the host guarantees the contexts are
/// still alive and no render is in flight.
void releaseKernels() noexcept {
    std::lock_guard<std::mutex> lock(g_moduleMutex);
    for (DeviceModule& slot : g_modules) {
        if (slot.valid && slot.module && slot.context) {
            ContextScope scope(slot.context);
            if (scope.ok()) {
                cuModuleUnload(slot.module);
            }
        }
        slot = DeviceModule{};
    }
}

// ===========================================================================
//  Per-instance state (PrGPUFilterInstance::ioPrivatePluginData)
// ===========================================================================
struct Instance {
    /// Magic word so a corrupted or already-disposed pointer is detected
    /// rather than dereferenced.
    static constexpr std::uint32_t kMagic = 0x4F534756u;  // 'OSGV'
    std::uint32_t magic = kMagic;

    piSuitesPtr suites = nullptr;
    SPBasicSuite* basic = nullptr;

    // Suites.  Raw pointers with explicit releases in the destructor: the
    // RAII SuiteHandle in plugins/common is typed for the importer's set and
    // these are only ever held by one object with a well defined lifetime.
    const PrSDKGPUDeviceSuite* gpu = nullptr;
    const PrSDKPPixSuite* ppix = nullptr;
    const PrSDKVideoSegmentSuite* segment = nullptr;
    int segmentVersion = 0;
    const PrSDKSequenceInfoSuite* sequence = nullptr;
    int sequenceVersion = 0;

    csSDK_uint32 deviceIndex = 0;
    PrTimelineID timelineId = 0;
    csSDK_int32 nodeId = 0;

    CUcontext context = nullptr;
    CUstream stream = nullptr;
    CUfunction kernel = nullptr;

    /// AE index -> host GetParam index, discovered once in CreateInstance by
    /// probeParams().  Constructed with the static mapping so every read is
    /// well defined even if the probe never runs (no suite, a host that
    /// refuses GetParamCount, an exception on the way in).
    HostParamMap paramMap{};

    /// False until probeParams() has positively identified the host's index
    /// space.  The probe reads parameters through GetParam, which fails
    /// intermittently on a freshly created node, so a single failed attempt
    /// at CreateInstance must not condemn the instance to the static mapping
    /// for its whole life: Render retries while this is false.  Rendering a
    /// frame proves the node is ready, which is exactly when a retry works.
    bool paramMapProbed = false;

    Instance() noexcept { paramMap.setStatic(); }

    [[nodiscard]] bool alive() const noexcept { return magic == kMagic; }
};

/// Acquire a suite, returning nullptr instead of throwing.
template <class SuiteT>
const SuiteT* acquire(SPBasicSuite* basic, const char* name, int version) noexcept {
    if (!basic || !basic->AcquireSuite || !name) {
        return nullptr;
    }
    const void* suite = nullptr;
    if (basic->AcquireSuite(name, version, &suite) != kSPNoError || !suite) {
        return nullptr;
    }
    return static_cast<const SuiteT*>(suite);
}

/// Acquire the first version of a suite the host provides.  Used for the
/// Video Segment Suite (9 -> 8 -> 7 -> 6; only GetParam and GetNodeProperty
/// are used and both are v4 members) and the Sequence Info Suite.
template <class SuiteT>
const SuiteT* acquireFirst(SPBasicSuite* basic, const char* name, std::initializer_list<int> versions,
                           int* outVersion) noexcept {
    for (const int v : versions) {
        if (const SuiteT* suite = acquire<SuiteT>(basic, name, v)) {
            if (outVersion) {
                *outVersion = v;
            }
            return suite;
        }
    }
    if (outVersion) {
        *outVersion = 0;
    }
    return nullptr;
}

/// Release a suite if it was acquired.
void releaseSuite(SPBasicSuite* basic, const char* name, int version) noexcept {
    if (basic && basic->ReleaseSuite && name && version > 0) {
        basic->ReleaseSuite(name, version);
    }
}

// ===========================================================================
//  Reading the keyframed parameters
// ===========================================================================

/// One GetParam call.
///
/// `aeIndex` is the AE parameter index; the host index it maps to comes from
/// the instance's HostParamMap, which CreateInstance either probed from the
/// host or left at the static "AE index - 1" rule.  A control the host does
/// not expose maps to -1 and the read fails cleanly, so the caller uses that
/// control's default rather than a neighbour's value.
bool readParam(const Instance& inst, int aeIndex, PrTime time, PrParam* out) noexcept {
    if (!inst.segment || !inst.segment->GetParam || !out) {
        return false;
    }
    const int hostIndex = inst.paramMap[aeIndex];
    if (hostIndex < 0) {
        return false;
    }
    std::memset(out, 0, sizeof(*out));
    const prSuiteError err = inst.segment->GetParam(inst.nodeId, hostIndex, time, out);
    return err == suiteError_NoError;
}

/// Translate one PrParam variant into the dialect matchHostParams() speaks.
/// Anything we do not use maps to Unknown, which matches nothing.
[[nodiscard]] HostParamKind kindOf(const PrParam& p) noexcept {
    switch (p.mType) {
        case kPrParamType_Int32:   return HostParamKind::Int32;
        case kPrParamType_Float32: return HostParamKind::Float32;
        case kPrParamType_Float64: return HostParamKind::Float64;
        case kPrParamType_Bool:    return HostParamKind::Bool;
        default:                   return HostParamKind::Unknown;
    }
}

/// Discover the host's parameter index space, once per instance.
///
/// Asks GetParamCount how many entries there are, reads each one's TYPE at
/// time 0, and hands the resulting signature to matchHostParams().  On a
/// positive identification the instance's map is replaced; otherwise the
/// static map it was constructed with is kept.  Either way the function is
/// non-fatal - it only ever improves the mapping, never breaks it - and it
/// logs which of the two is in force so a log alone answers the question.
///
/// Cost: one GetParamCount plus at most kValueParamCount GetParam calls, all
/// at t = 0, on a code path Premiere runs when an effect is applied or a
/// parameter changes - not per frame.
void probeParams(Instance& inst) noexcept {
    if (!inst.segment || !inst.segment->GetParamCount || !inst.segment->GetParam) {
        PluginLog::oncef("reframe/gpu/probe-nosuite", PluginLog::Level::Warn,
                         "reframe/gpu: the Video Segment Suite has no GetParamCount/GetParam; "
                         "using the static parameter mapping");
        return;
    }

    csSDK_int32 hostCount = 0;
    if (inst.segment->GetParamCount(inst.nodeId, &hostCount) != suiteError_NoError) {
        PluginLog::oncef("reframe/gpu/probe-count", PluginLog::Level::Warn,
                         "reframe/gpu: GetParamCount failed; using the static parameter mapping");
        return;
    }

    // Read every entry the host admits to, but never more than our own list
    // can account for: a longer list is not ours and matchHostParams() would
    // refuse it anyway, so there is no reason to pay for the extra calls.
    // The array is sized by the same constant, so the bound is structural.
    HostParamKind kinds[kValueParamCount] = {};
    const int probeCount = (hostCount > kValueParamCount) ? kValueParamCount : static_cast<int>(hostCount);
    std::string dump;
    dump.reserve(256);
    for (int i = 0; i < probeCount; ++i) {
        PrParam p{};
        // GetParam on a freshly created node fails INTERMITTENTLY: observed
        // on a live host (26.2.2) failing for a different subset of indices
        // on every CreateInstance, most often the angle controls, while the
        // same indices read fine moments later.  Treating one failure as a
        // type would poison the signature and send the whole effect back to
        // the static mapping - which is exactly what happened in the field:
        // playback (a lucky instance) animated while scrubbing (an unlucky
        // one) did not.  A few immediate retries cost nothing and turn an
        // intermittent read into a reliable one.
        constexpr int kReadAttempts = 8;
        prSuiteError readErr = suiteError_Fail;
        for (int attempt = 0; attempt < kReadAttempts; ++attempt) {
            std::memset(&p, 0, sizeof(p));
            readErr = inst.segment->GetParam(inst.nodeId, i, 0, &p);
            if (readErr == suiteError_NoError && kindOf(p) != HostParamKind::Unknown) {
                break;
            }
            // Yield rather than spin: whatever the host is still finishing
            // needs a moment, not CPU contention from this thread.
            std::this_thread::yield();
        }
        if (readErr != suiteError_NoError) {
            kinds[i] = HostParamKind::Unknown;
            dump += std::format("[{}]=<err> ", i);
            continue;
        }
        kinds[i] = kindOf(p);
        // The value is logged purely so a human reading the diagnostic can
        // sanity-check the identification; nothing here depends on it.
        switch (p.mType) {
            case kPrParamType_Float32: dump += std::format("[{}]f32:{:.3f} ", i, p.mFloat32); break;
            case kPrParamType_Float64: dump += std::format("[{}]f64:{:.3f} ", i, p.mFloat64); break;
            case kPrParamType_Int32:   dump += std::format("[{}]i32:{} ", i, p.mInt32); break;
            case kPrParamType_Bool:    dump += std::format("[{}]bool:{} ", i, p.mBool ? 1 : 0); break;
            default:                   dump += std::format("[{}]type{} ", i, static_cast<int>(p.mType)); break;
        }
    }

    // The one-time dump: the ground truth this whole mechanism was built
    // from.  Logged whatever the outcome, because it is just as useful when
    // the probe SUCCEEDS (it shows which controls the host hid) as when it
    // fails (it shows what to teach the matcher next).
    PluginLog::oncef("reframe/gpu/paramdump", PluginLog::Level::Info,
                     "reframe/gpu: host parameter dump at t=0 ({} of {} entries, we added {}): {}", probeCount,
                     hostCount, OSV_REFRAME_PARAM_COUNT, dump);

    HostParamMap probed{};
    if (!matchHostParams(kinds, probeCount, &probed)) {
        PluginLog::oncef("reframe/gpu/probe-nomatch", PluginLog::Level::Error,
                         "reframe/gpu: the host reports {} parameters and their types do not match this effect's "
                         "signature; falling back to the static mapping (AE index - 1), which may read the wrong "
                         "control",
                         hostCount);
        return;
    }

    inst.paramMap = probed;
    inst.paramMapProbed = true;
    PluginLog::oncef("reframe/gpu/probe-ok", PluginLog::Level::Info,
                     "reframe/gpu: probed the host parameter mapping from {} entries - "
                     "resolution={} preset={} pan={} tilt={} roll={} fov={} distortion={} "
                     "srcPan={} srcTilt={} srcRoll={} smooth={} (-1 = not exposed by the host)",
                     hostCount, probed[kIndexOutputResolution], probed[kIndexPreset], probed[kIndexPan],
                     probed[kIndexTilt], probed[kIndexRoll], probed[kIndexFov], probed[kIndexDistortion],
                     probed[kIndexSourcePan], probed[kIndexSourceTilt], probed[kIndexSourceRoll],
                     probed[kIndexSmooth]);
}

/// An angle control: PF_ADD_ANGLE arrives as mFloat32 degrees.  Other types
/// are accepted defensively (a host that changed its mind about the union
/// member must not silently give us zero).
double readAngle(const Instance& inst, int aeIndex, PrTime time, double fallback) noexcept {
    PrParam p{};
    if (!readParam(inst, aeIndex, time, &p)) {
        return fallback;
    }
    switch (p.mType) {
        case kPrParamType_Float32:
            return static_cast<double>(p.mFloat32);
        case kPrParamType_Float64:
            return p.mFloat64;
        case kPrParamType_Int32:
            return static_cast<double>(p.mInt32);
        default:
            return fallback;
    }
}

/// A float slider: PF_ADD_FLOAT_SLIDERX arrives as mFloat64.
double readFloat(const Instance& inst, int aeIndex, PrTime time, double fallback) noexcept {
    PrParam p{};
    if (!readParam(inst, aeIndex, time, &p)) {
        return fallback;
    }
    switch (p.mType) {
        case kPrParamType_Float64:
            return p.mFloat64;
        case kPrParamType_Float32:
            return static_cast<double>(p.mFloat32);
        default:
            return fallback;
    }
}

/// A popup: mInt32, 1-based.
int readPopup(const Instance& inst, int aeIndex, PrTime time, int fallback) noexcept {
    PrParam p{};
    if (!readParam(inst, aeIndex, time, &p)) {
        return fallback;
    }
    switch (p.mType) {
        case kPrParamType_Int32:
            return p.mInt32;
        case kPrParamType_Int16:
            return static_cast<int>(p.mInt16);
        case kPrParamType_Int8:
            return static_cast<int>(p.mInt8);
        default:
            return fallback;
    }
}

/// A checkbox: mBool.
bool readBool(const Instance& inst, int aeIndex, PrTime time, bool fallback) noexcept {
    PrParam p{};
    if (!readParam(inst, aeIndex, time, &p)) {
        return fallback;
    }
    switch (p.mType) {
        case kPrParamType_Bool:
            return p.mBool != 0;
        case kPrParamType_Int32:
            return p.mInt32 != 0;
        default:
            return fallback;
    }
}

/// Read every control at `time`, applying the "Smooth Keyframes" average
/// over t-1, t and t+1 frames to the six angle dials when it is on.
///
/// Averaging the ANGLES (not the frames) is what makes the smoothing cheap:
/// it needs no extra input frames, so GetFrameDependencies can keep saying
/// "only the current frame", and it produces the same numbers as the CPU
/// path, which does the same three-sample average through PF_CHECKOUT_PARAM.
Settings readSettings(const Instance& inst, PrTime clipTime, PrTime ticksPerFrame) noexcept {
    Settings s;
    s.resolution =
        sanitiseResolution(readPopup(inst, kIndexOutputResolution, clipTime, OSV_REFRAME_RESOLUTION_DEFAULT));
    s.preset = sanitisePreset(readPopup(inst, kIndexPreset, clipTime, OSV_REFRAME_PRESET_DEFAULT));
    s.fovDeg = readFloat(inst, kIndexFov, clipTime, OSV_REFRAME_FOV_DEFAULT);
    s.distortion = readFloat(inst, kIndexDistortion, clipTime, OSV_REFRAME_DISTORTION_DEFAULT);
    s.smoothKeyframes = readBool(inst, kIndexSmooth, clipTime, false);

    // The six angles, either sampled once or averaged over three frames.
    const int angleIndices[6] = {kIndexPan,       kIndexTilt,       kIndexRoll,
                                 kIndexSourcePan, kIndexSourceTilt, kIndexSourceRoll};
    double angles[6] = {0, 0, 0, 0, 0, 0};

    // Smoothing needs a frame duration; without one (a host that could not
    // tell us) it degrades to no smoothing rather than to a wrong average.
    const bool smooth = s.smoothKeyframes && ticksPerFrame > 0;
    for (int i = 0; i < 6; ++i) {
        const double centre = readAngle(inst, angleIndices[i], clipTime, 0.0);
        if (!smooth) {
            angles[i] = centre;
            continue;
        }
        // Clamp the neighbours to non-negative clip time: asking before the
        // clip start returns the first keyframe on a real host, but a
        // negative PrTime is not something every host is happy with.
        const PrTime before = (clipTime > ticksPerFrame) ? (clipTime - ticksPerFrame) : 0;
        const PrTime after = clipTime + ticksPerFrame;
        const double prev = readAngle(inst, angleIndices[i], before, centre);
        const double next = readAngle(inst, angleIndices[i], after, centre);
        angles[i] = (prev + centre + next) / 3.0;
    }

    s.panDeg = angles[0];
    s.tiltDeg = angles[1];
    s.rollDeg = angles[2];
    s.sourcePanDeg = angles[3];
    s.sourceTiltDeg = angles[4];
    s.sourceRollDeg = angles[5];
    return s;
}

/// Pixel size of the sequence, or an invalid size when the suite cannot tell
/// us (the caller then falls back to the output frame's own size).
///
/// The GPU instance already holds the timeline id and the suite, so unlike
/// the CPU path this needs no acquire / release dance.
SizePx sequenceSize(const Instance& inst) noexcept {
    if (!inst.sequence || !inst.sequence->GetFrameRect) {
        return SizePx{};
    }
    prRect rect{};
    if (inst.sequence->GetFrameRect(inst.timelineId, &rect) != suiteError_NoError) {
        return SizePx{};
    }
    // Host-supplied, therefore validated: an inverted or absurd rectangle is
    // reported as "unknown" rather than carried into the camera.
    const long long w = static_cast<long long>(rect.right) - static_cast<long long>(rect.left);
    const long long h = static_cast<long long>(rect.bottom) - static_cast<long long>(rect.top);
    if (w <= 0 || h <= 0 || w > kMaxSequenceEdge || h > kMaxSequenceEdge) {
        return SizePx{};
    }
    return SizePx{static_cast<int>(w), static_cast<int>(h)};
}

// ===========================================================================
//  PPix inspection
// ===========================================================================

/// Everything we need to know about one GPU frame.
struct GpuFrame {
    void* data = nullptr;
    std::int32_t rowBytes = 0;
    int width = 0;
    int height = 0;
    bool isHalf = false;
    bool valid = false;
};

/// Query a GPU PPix through the PPix and GPU Device suites.
GpuFrame inspectFrame(const Instance& inst, PPixHand hand) noexcept {
    GpuFrame f;
    if (!hand || !inst.ppix || !inst.gpu) {
        return f;
    }
    if (!inst.ppix->GetBounds || !inst.ppix->GetRowBytes || !inst.ppix->GetPixelFormat || !inst.gpu->GetGPUPPixData) {
        return f;
    }

    void* data = nullptr;
    if (inst.gpu->GetGPUPPixData(hand, &data) != suiteError_NoError || !data) {
        return f;
    }
    csSDK_int32 rowBytes = 0;
    if (inst.ppix->GetRowBytes(hand, &rowBytes) != suiteError_NoError || rowBytes <= 0) {
        return f;
    }
    prRect bounds{};
    if (inst.ppix->GetBounds(hand, &bounds) != suiteError_NoError) {
        return f;
    }
    PrPixelFormat format = PrPixelFormat_Invalid;
    if (inst.ppix->GetPixelFormat(hand, &format) != suiteError_NoError) {
        return f;
    }
    if (format != PrPixelFormat_GPU_BGRA_4444_32f && format != PrPixelFormat_GPU_BGRA_4444_16f) {
        // "Result must be in the same pixel format as the input"
        // (PrSDKGPUFilter.h) and only these two GPU formats exist.
        return f;
    }

    f.data = data;
    f.rowBytes = static_cast<std::int32_t>(rowBytes);
    f.width = static_cast<int>(bounds.right - bounds.left);
    f.height = static_cast<int>(bounds.bottom - bounds.top);
    f.isHalf = (format == PrPixelFormat_GPU_BGRA_4444_16f);
    // A pitch that cannot hold one row means the header is wrong; refuse it
    // rather than walk off the allocation.
    const std::size_t bpp = f.isHalf ? 8u : 16u;
    f.valid = f.width > 0 && f.height > 0 &&
              static_cast<std::size_t>(f.rowBytes) >= static_cast<std::size_t>(f.width) * bpp;
    return f;
}

// ===========================================================================
//  PrGPUFilter callbacks
// ===========================================================================

prSuiteError createInstance(PrGPUFilterInstance* io) noexcept {
    try {
        if (!io || !io->piSuites || !io->piSuites->utilFuncs || !io->piSuites->utilFuncs->getSPBasicSuite) {
            return suiteError_InvalidParms;
        }
        SPBasicSuite* basic = io->piSuites->utilFuncs->getSPBasicSuite();
        if (!basic) {
            return suiteError_InvalidParms;
        }

        Instance* inst = new (std::nothrow) Instance();
        if (!inst) {
            return suiteError_OutOfMemory;
        }
        inst->suites = io->piSuites;
        inst->basic = basic;
        inst->deviceIndex = io->inDeviceIndex;
        inst->timelineId = io->inTimelineID;
        inst->nodeId = io->inNodeID;

        // ---- the device -------------------------------------------------
        inst->gpu = acquire<PrSDKGPUDeviceSuite>(basic, kPrSDKGPUDeviceSuite, kPrSDKGPUDeviceSuiteVersion);
        if (!inst->gpu || !inst->gpu->GetDeviceInfo) {
            PluginLog::warn("reframe/gpu: no GPU Device Suite; rendering in software");
            delete inst;
            return suiteError_Fail;
        }

        PrGPUDeviceInfo info{};
        if (inst->gpu->GetDeviceInfo(kPrSDKGPUDeviceSuiteVersion, io->inDeviceIndex, &info) != suiteError_NoError) {
            PluginLog::warn("reframe/gpu: GetDeviceInfo failed for device {}", io->inDeviceIndex);
            releaseSuite(basic, kPrSDKGPUDeviceSuite, kPrSDKGPUDeviceSuiteVersion);
            delete inst;
            return suiteError_Fail;
        }

        // CUDA only.  OpenCL was dropped by Premiere in 15.4, Metal is Mac
        // and DirectX is still unreleased for third parties; returning an
        // error here makes the host render this node in software, which is
        // exactly the documented fallback (PrSDKGPUFilter.h:167-170).
        if (info.outDeviceFramework != PrGPUDeviceFramework_CUDA) {
            PluginLog::info("reframe/gpu: device {} is not CUDA (framework {}); using the CPU path",
                            io->inDeviceIndex, static_cast<int>(info.outDeviceFramework));
            releaseSuite(basic, kPrSDKGPUDeviceSuite, kPrSDKGPUDeviceSuiteVersion);
            delete inst;
            return suiteError_Fail;
        }
        if (!info.outMeetsMinimumRequirementsForAcceleration) {
            PluginLog::info("reframe/gpu: device {} does not meet the acceleration minimum; using the CPU path",
                            io->inDeviceIndex);
            releaseSuite(basic, kPrSDKGPUDeviceSuite, kPrSDKGPUDeviceSuiteVersion);
            delete inst;
            return suiteError_Fail;
        }

        inst->context = static_cast<CUcontext>(info.outContextHandle);
        inst->stream = static_cast<CUstream>(info.outCommandQueueHandle);
        if (!inst->context) {
            PluginLog::warn("reframe/gpu: the host reported a CUDA device with no context");
            releaseSuite(basic, kPrSDKGPUDeviceSuite, kPrSDKGPUDeviceSuiteVersion);
            delete inst;
            return suiteError_Fail;
        }

        // ---- the kernel -------------------------------------------------
        inst->kernel = acquireKernel(io->inDeviceIndex, inst->context);
        if (!inst->kernel) {
            releaseSuite(basic, kPrSDKGPUDeviceSuite, kPrSDKGPUDeviceSuiteVersion);
            delete inst;
            return suiteError_Fail;
        }

        // ---- the remaining suites ---------------------------------------
        inst->ppix = acquire<PrSDKPPixSuite>(basic, kPrSDKPPixSuite, kPrSDKPPixSuiteVersion);
        if (!inst->ppix) {
            PluginLog::warn("reframe/gpu: no PPix Suite; rendering in software");
            releaseSuite(basic, kPrSDKGPUDeviceSuite, kPrSDKGPUDeviceSuiteVersion);
            delete inst;
            return suiteError_Fail;
        }

        // Only GetParam is used and it exists since v4; acquire the newest
        // the host has so a future host does not silently give us an old
        // table, but never fail over a missing high version.
        inst->segment = acquireFirst<PrSDKVideoSegmentSuite>(
            basic, kPrSDKVideoSegmentSuite,
            {kPrSDKVideoSegmentSuiteVersion9, kPrSDKVideoSegmentSuiteVersion8, kPrSDKVideoSegmentSuiteVersion7,
             kPrSDKVideoSegmentSuiteVersion6},
            &inst->segmentVersion);
        if (!inst->segment) {
            PluginLog::warn("reframe/gpu: no Video Segment Suite; parameters cannot be read, rendering in software");
            releaseSuite(basic, kPrSDKPPixSuite, kPrSDKPPixSuiteVersion);
            releaseSuite(basic, kPrSDKGPUDeviceSuite, kPrSDKGPUDeviceSuiteVersion);
            delete inst;
            return suiteError_Fail;
        }

        // Optional: without it "Match Sequence" falls back to 16:9.
        inst->sequence = acquireFirst<PrSDKSequenceInfoSuite>(basic, kPrSDKSequenceInfoSuite,
                                                              {kPrSDKSequenceInfoSuiteVersion, 8, 7, 6, 5},
                                                              &inst->sequenceVersion);

        // Discover the host's parameter index space, once per instance.
        //
        // gpuParamIndex() encodes the documented rule, "AE index - 1"
        // (PrGPUFilterModule.h:153), which assumes the host's GetParam index
        // space is the list After Effects built, group markers included.
        // Premiere Pro 26.2 disproves that: this effect adds 15 parameters
        // (11 controls + 4 group markers) and GetParamCount answers 8 - the
        // markers are dropped AND the three controls inside the collapsed
        // "Source" group are not exposed.  Under the static rule every read
        // past the first group landed on a neighbouring control, FOV came
        // back as garbage and the render bailed out entirely.
        //
        // probeParams() asks the host what it really has and identifies each
        // control by its PrParam type, so the mapping is measured rather than
        // assumed.  It is deliberately non-fatal: a host it cannot identify
        // leaves the static mapping in place, which is exactly the behaviour
        // that existed before, and says so in the log.
        probeParams(*inst);

        io->ioPrivatePluginData = inst;
        // Reframing a 6K equirect into an HD frame is a couple of samples
        // per output pixel on the GPU; it plays back in real time.
        io->outIsRealtime = kPrTrue;

        PluginLog::info("reframe/gpu: instance on device {} (video segment v{}, sequence info v{})",
                        io->inDeviceIndex, inst->segmentVersion, inst->sequenceVersion);
        return suiteError_NoError;
    } catch (...) {
        // An exception must never cross back into Premiere's C stack.
        return suiteError_Fail;
    }
}

prSuiteError disposeInstance(PrGPUFilterInstance* io) noexcept {
    try {
        if (!io) {
            return suiteError_InvalidParms;
        }
        Instance* inst = static_cast<Instance*>(io->ioPrivatePluginData);
        io->ioPrivatePluginData = nullptr;
        if (!inst) {
            return suiteError_NoError;  // never created, or disposed twice
        }
        if (!inst->alive()) {
            PluginLog::error("reframe/gpu: DisposeInstance on a corrupt instance pointer");
            return suiteError_InvalidParms;
        }

        // Release exactly what was acquired, in reverse order.  The module
        // cache is NOT touched here: other instances on the same device
        // still use it and it is freed in the entry point's shutdown.
        SPBasicSuite* basic = inst->basic;
        if (inst->sequence) {
            releaseSuite(basic, kPrSDKSequenceInfoSuite, inst->sequenceVersion);
        }
        if (inst->segment) {
            releaseSuite(basic, kPrSDKVideoSegmentSuite, inst->segmentVersion);
        }
        if (inst->ppix) {
            releaseSuite(basic, kPrSDKPPixSuite, kPrSDKPPixSuiteVersion);
        }
        if (inst->gpu) {
            releaseSuite(basic, kPrSDKGPUDeviceSuite, kPrSDKGPUDeviceSuiteVersion);
        }
        inst->magic = 0;
        delete inst;
        return suiteError_NoError;
    } catch (...) {
        return suiteError_Fail;
    }
}

/// We never need a frame other than the one at the current time: the
/// smoothing averages PARAMETERS, not pixels.  Returning NotImplemented is
/// how the SDK samples say "only the current frame".
prSuiteError getFrameDependencies(PrGPUFilterInstance*, const PrGPUFilterRenderParams*, csSDK_int32*,
                                  PrGPUFilterFrameDependency*) noexcept {
    return suiteError_NotImplemented;
}

/// No CPU pre-pass.
prSuiteError precompute(PrGPUFilterInstance*, const PrGPUFilterRenderParams*, csSDK_int32, PPixHand) noexcept {
    return suiteError_NotImplemented;
}

prSuiteError render(PrGPUFilterInstance* instanceData, const PrGPUFilterRenderParams* renderParams,
                    const PPixHand* inFrames, csSDK_size_t inFrameCount, PPixHand* outFrame) noexcept {
    try {
        // ---- argument checks --------------------------------------------
        if (!instanceData || !renderParams || !inFrames || !outFrame || inFrameCount < 1) {
            return suiteError_InvalidParms;
        }
        Instance* inst = static_cast<Instance*>(instanceData->ioPrivatePluginData);
        if (!inst || !inst->alive() || !inst->kernel || !inst->context) {
            return suiteError_InvalidParms;
        }

        const GpuFrame src = inspectFrame(*inst, inFrames[0]);
        const GpuFrame dst = inspectFrame(*inst, *outFrame);
        if (!src.valid || !dst.valid) {
            PluginLog::oncef("reframe/gpu/frame", PluginLog::Level::Error,
                             "reframe/gpu: unusable frame (src {}x{} valid={}, dst {}x{} valid={})", src.width,
                             src.height, src.valid, dst.width, dst.height, dst.valid);
            return suiteError_Fail;
        }
        // The host hands us an output in the same format as the input; if it
        // ever did not, writing half into a float buffer would corrupt it.
        if (src.isHalf != dst.isHalf) {
            PluginLog::error("reframe/gpu: input and output pixel formats differ");
            return suiteError_Fail;
        }

        // ---- parameters --------------------------------------------------
        // Retry the probe if CreateInstance could not identify the host's
        // index space.  GetParam fails intermittently on a node the host has
        // only just built, and an instance that gave up at creation would
        // read the wrong controls for as long as it lived - the field
        // symptom being that playback animated (an instance whose probe had
        // got lucky) while scrubbing did not.  Reaching Render proves the
        // node is ready, so this is the moment a retry succeeds.
        if (!inst->paramMapProbed) {
            probeParams(*inst);
        }
        const Settings settings = readSettings(*inst, renderParams->inClipTime, renderParams->inRenderTicksPerFrame);

        // The frame we render into is the one the host allocated; its size
        // is the render size, which may differ from the input's.
        ConstFrameView srcView;
        srcView.base = src.data;
        srcView.rowBytes = src.rowBytes;
        srcView.width = src.width;
        srcView.height = src.height;
        srcView.layout = src.isHalf ? PixelLayout::Bgra16f : PixelLayout::Bgra32f;
        srcView.topDown = true;  // "GPU Frames always have origin top left"

        const KernelSetup setup = buildParams(settings, srcView, dst.width, dst.height, sequenceSize(*inst));
        if (!setup.valid) {
            PluginLog::oncef("reframe/gpu/setup", PluginLog::Level::Error,
                             "reframe/gpu: could not build the kernel parameters ({}x{} -> {}x{}): {}", src.width,
                             src.height, dst.width, dst.height, setupRejectName(setup.reject));
            return suiteError_Fail;
        }

        // ---- launch -------------------------------------------------------
        ContextScope scope(inst->context);
        if (!scope.ok()) {
            PluginLog::error("reframe/gpu: cuCtxPushCurrent failed at render time");
            return suiteError_Fail;
        }

        // buildParams() computed sourceRow0 as a HOST pointer arithmetic on
        // the device address; for a top-down frame that is the base itself,
        // which is what we pass. The kernel adds y * pitchBytes.
        const void* srcDevice = setup.sourceRow0;
        OsvReframeParams params = setup.params;
        OsvRgbaSource source = setup.source;
        void* dstDevice = dst.data;
        int dstRowBytes = dst.rowBytes;
        int dstIsHalf = dst.isHalf ? 1 : 0;

        void* args[] = {&params, &source, &srcDevice, &dstDevice, &dstRowBytes, &dstIsHalf};

        const unsigned gridX = (static_cast<unsigned>(dst.width) + kBlockDimX - 1u) / kBlockDimX;
        const unsigned gridY = (static_cast<unsigned>(dst.height) + kBlockDimY - 1u) / kBlockDimY;

        // Launch on the host's own stream so our work is correctly ordered
        // against the asynchronous operations that may still be outstanding
        // on the input frame.  No synchronisation: the host owns the stream
        // and will sequence the download itself.
        const CUresult r = cuLaunchKernel(inst->kernel, gridX, gridY, 1u, kBlockDimX, kBlockDimY, 1u, 0u, inst->stream,
                                          args, nullptr);
        if (r != CUDA_SUCCESS) {
            PluginLog::error("reframe/gpu: {}", cudaMessage("cuLaunchKernel", r));
            return suiteError_Fail;
        }

        instanceData->outIsRealtime = kPrTrue;
        return suiteError_NoError;
    } catch (...) {
        return suiteError_Fail;
    }
}

}  // namespace

// ===========================================================================
//  The exported entry point
//
//  Startup fills the function table and the match name; shutdown frees the
//  per-device modules.  ioIndex would be incremented if this module held
//  more than one GPU filter - it holds exactly one, so it is left alone and
//  a non-zero index is refused.
// ===========================================================================
extern "C" __declspec(dllexport) prSuiteError xGPUFilterEntry(csSDK_uint32 inHostInterfaceVersion,
                                                              csSDK_int32* ioIndex, prBool inStartup,
                                                              piSuitesPtr piSuites, PrGPUFilter* outFilter,
                                                              PrGPUFilterInfo* outFilterInfo) {
    try {
        // The host tells us which interface it speaks; we implement 2 and
        // nothing older, so an older host is declined cleanly.
        if (inHostInterfaceVersion < PrSDKGPUFilterInterfaceVersion2) {
            return suiteError_InvalidParms;
        }
        if (!ioIndex) {
            return suiteError_InvalidParms;
        }
        if (*ioIndex != 0) {
            // Exactly one GPU filter in this module.
            return suiteError_InvalidParms;
        }

        if (!inStartup) {
            // Shutdown: the contexts are still alive here, which is the only
            // safe moment to unload the modules.
            releaseKernels();
            PluginLog::info("reframe/gpu: shutdown");
            return suiteError_NoError;
        }

        if (!outFilter || !outFilterInfo) {
            return suiteError_InvalidParms;
        }

        // The log file is opened here rather than in DllMain: DllMain runs
        // under the loader lock and must not touch the file system.
        osv::premiere::PluginLog::init(L"Open360Reframe");

        outFilter->CreateInstance = &createInstance;
        outFilter->DisposeInstance = &disposeInstance;
        outFilter->GetFrameDependencies = &getFrameDependencies;
        outFilter->Precompute = &precompute;
        outFilter->Render = &render;

        outFilterInfo->outInterfaceVersion = PrSDKGPUFilterInterfaceVersion2;
        // Leaving outMatchName null would make the host use the module's
        // PiPL match name, which is the same string - but being explicit
        // means the binding cannot depend on the resource being found, and
        // the test can read the value back.
        outFilterInfo->outMatchName = PrSDKString();
        if (piSuites && piSuites->utilFuncs && piSuites->utilFuncs->getSPBasicSuite) {
            SPBasicSuite* basic = piSuites->utilFuncs->getSPBasicSuite();
            if (const PrSDKStringSuite* strings =
                    acquire<PrSDKStringSuite>(basic, kPrSDKStringSuite, kPrSDKStringSuiteVersion)) {
                if (strings->AllocateFromUTF8) {
                    // prUTF8Char is an unsigned char typedef; the literal is
                    // pure ASCII so the reinterpretation is exact.
                    strings->AllocateFromUTF8(reinterpret_cast<const prUTF8Char*>(OSV_REFRAME_MATCH_NAME),
                                              &outFilterInfo->outMatchName);
                }
                releaseSuite(basic, kPrSDKStringSuite, kPrSDKStringSuiteVersion);
            }
        }

        PluginLog::info("reframe/gpu: startup, host interface version {}", inHostInterfaceVersion);
        return suiteError_NoError;
    } catch (...) {
        return suiteError_Fail;
    }
}
