// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 The OpenOSV Contributors
//
// ReframeMetal.mm - the Metal side of the effect's GPU path (ReframeMetal.h).
//
// Built with ARC.  The Metal objects Premiere hands over (device, queue,
// buffers) arrive as opaque pointers and are bridged WITHOUT taking
// ownership: the host keeps them alive for the duration of the call, and a
// __bridge cast neither retains nor releases.  The pipelines this file
// creates are its own and live in the per-device table until
// releaseDevices().

#import <Foundation/Foundation.h>
#import <Metal/Metal.h>

#include "ReframeMetal.h"

#include "PluginLog.h"

#include <algorithm>
#include <cstdint>
#include <mutex>

// The effect's Metal library, generated by cmake/EmbedKernel.cmake from the
// assembled source (and its ahead-of-time metallib when the build had the
// Metal compiler).
extern const unsigned char osv_reframe_metal_source[];
extern const size_t osv_reframe_metal_source_size;
#if defined(OSV_REFRAME_HAVE_METALLIB)
extern const unsigned char osv_reframe_metal_lib[];
extern const size_t osv_reframe_metal_lib_size;
#endif

namespace osv::reframe::metal {

namespace {

using premiere::PluginLog;

/// Kernel name in ReframeKernel.metal.
constexpr const char* kKernelName = "osvReframeEquirectKernel";

/// Largest device table (Premiere enumerates a handful of GPUs at most).
constexpr unsigned kMaxDevices = 16;

/// Largest frame edge accepted (the same bound the CPU path applies).
constexpr int kMaxEdge = 32768;

/// One device's pipeline.  Keyed by the device object as well as the index,
/// so a host that hands a slot a different device gets a fresh pipeline
/// instead of one compiled for another GPU.
struct DeviceSlot {
    id<MTLDevice> device = nil;
    id<MTLComputePipelineState> pipeline = nil;
};

struct Table {
    std::mutex mutex;
    DeviceSlot slots[kMaxDevices];
    bool precompiled = false;
};

/// The table, created on first use and never destroyed by a static
/// destructor (a host may still render while the process exits).
Table& table() noexcept {
    static Table* t = new Table();
    return *t;
}

std::string utf8(NSString* s) {
    if (s == nil) {
        return {};
    }
    const char* c = [s UTF8String];
    return c ? std::string(c) : std::string();
}

/// Build the library for `device`: the embedded metallib first, the embedded
/// source (fast math off) when there is none or it does not load.
id<MTLLibrary> buildLibrary(id<MTLDevice> device, bool& precompiled, std::string& error) {
    NSError* nsError = nil;
#if defined(OSV_REFRAME_HAVE_METALLIB)
    if (osv_reframe_metal_lib_size > 0) {
        dispatch_data_t data = dispatch_data_create(osv_reframe_metal_lib, osv_reframe_metal_lib_size, nullptr,
                                                    DISPATCH_DATA_DESTRUCTOR_DEFAULT);
        id<MTLLibrary> library = data != nullptr ? [device newLibraryWithData:data error:&nsError] : nil;
        if (library != nil) {
            precompiled = true;
            return library;
        }
        PluginLog::warn("reframe/metal: the embedded metallib did not load ({}); compiling the source",
                        utf8([nsError localizedDescription]));
        nsError = nil;
    }
#endif
    NSString* source = [[NSString alloc] initWithBytes:osv_reframe_metal_source
                                                length:osv_reframe_metal_source_size
                                              encoding:NSUTF8StringEncoding];
    if (source == nil) {
        error = "the embedded Metal source is not valid UTF-8";
        return nil;
    }
    MTLCompileOptions* options = [[MTLCompileOptions alloc] init];
    options.languageVersion = MTLLanguageVersion2_4;
#if defined(__MAC_15_0) && __MAC_OS_X_VERSION_MAX_ALLOWED >= __MAC_15_0
    if (@available(macOS 15.0, *)) {
        options.mathMode = MTLMathModeSafe;
        options.mathFloatingPointFunctions = MTLMathFloatingPointFunctionsPrecise;
    } else {
        options.fastMathEnabled = NO;
    }
#else
    options.fastMathEnabled = NO;
#endif
    id<MTLLibrary> library = [device newLibraryWithSource:source options:options error:&nsError];
    if (library == nil) {
        error = "Metal kernel build failed: " + utf8([nsError localizedDescription]);
        return nil;
    }
    precompiled = false;
    return library;
}

/// The pipeline for a slot, building it when the slot is empty or holds a
/// different device.  Caller holds the table mutex.
id<MTLComputePipelineState> pipelineLocked(Table& t, unsigned deviceIndex, id<MTLDevice> device, std::string& error) {
    DeviceSlot& slot = t.slots[deviceIndex];
    if (slot.pipeline != nil && slot.device == device) {
        return slot.pipeline;
    }
    if (slot.pipeline != nil) {
        PluginLog::warn("reframe/metal: device slot {} now holds another GPU; rebuilding its pipeline", deviceIndex);
    }
    slot = DeviceSlot{};

    bool precompiled = false;
    id<MTLLibrary> library = buildLibrary(device, precompiled, error);
    if (library == nil) {
        return nil;
    }
    id<MTLFunction> function = [library newFunctionWithName:[NSString stringWithUTF8String:kKernelName]];
    if (function == nil) {
        error = std::string("the Metal library has no ") + kKernelName;
        return nil;
    }
    NSError* nsError = nil;
    id<MTLComputePipelineState> pipeline = [device newComputePipelineStateWithFunction:function error:&nsError];
    if (pipeline == nil) {
        error = "cannot build the reframe pipeline: " + utf8([nsError localizedDescription]);
        return nil;
    }
    slot.device = device;
    slot.pipeline = pipeline;
    t.precompiled = precompiled;
    PluginLog::info("reframe/metal: pipeline ready on device {} ({}, {} library, {} threads per SIMD group)",
                    deviceIndex, utf8([device name]), precompiled ? "precompiled" : "run-time compiled",
                    static_cast<unsigned long>([pipeline threadExecutionWidth]));
    return pipeline;
}

}  // namespace

bool prepareDevice(unsigned deviceIndex, void* devicePtr, std::string& error) noexcept {
    try {
        if (deviceIndex >= kMaxDevices || devicePtr == nullptr) {
            error = "device slot or device unusable";
            return false;
        }
        @autoreleasepool {
            id<MTLDevice> device = (__bridge id<MTLDevice>)devicePtr;
            Table& t = table();
            std::lock_guard<std::mutex> lock(t.mutex);
            return pipelineLocked(t, deviceIndex, device, error) != nil;
        }
    } catch (...) {
        error = "unexpected failure preparing the device";
        return false;
    }
}

bool renderFrame(unsigned deviceIndex, const FrameRequest& r, std::string& error) noexcept {
    try {
        // ---- validation: everything the kernel indexes with ----------------
        if (deviceIndex >= kMaxDevices || !r.device || !r.queue || !r.sourceBuffer || !r.outputBuffer) {
            error = "missing device, queue or frame";
            return false;
        }
        if (r.outputWidth <= 0 || r.outputHeight <= 0 || r.outputWidth > kMaxEdge || r.outputHeight > kMaxEdge ||
            r.params.outW != r.outputWidth || r.params.outH != r.outputHeight) {
            error = "output size does not match the parameters";
            return false;
        }
        const std::size_t outBpp = r.outputIsHalf ? 8u : 16u;
        if (r.outputRowBytes <= 0 ||
            static_cast<std::size_t>(r.outputRowBytes) < static_cast<std::size_t>(r.outputWidth) * outBpp) {
            error = "output pitch cannot hold a row";
            return false;
        }
        if (r.source.w <= 0 || r.source.h <= 0 || r.source.w > kMaxEdge || r.source.h > kMaxEdge ||
            r.source.pitchBytes <= 0) {
            error = "source layout unusable";
            return false;
        }
        const std::size_t srcBpp = r.source.isHalf ? 8u : 16u;
        if (static_cast<std::size_t>(r.source.pitchBytes) < static_cast<std::size_t>(r.source.w) * srcBpp) {
            error = "source pitch cannot hold a row";
            return false;
        }

        @autoreleasepool {
            id<MTLDevice> device = (__bridge id<MTLDevice>)r.device;
            id<MTLCommandQueue> queue = (__bridge id<MTLCommandQueue>)r.queue;
            id<MTLBuffer> source = (__bridge id<MTLBuffer>)r.sourceBuffer;
            id<MTLBuffer> output = (__bridge id<MTLBuffer>)r.outputBuffer;

            // The buffers must hold what the kernel will touch.
            const std::size_t srcNeed =
                r.sourceOffset + static_cast<std::size_t>(r.source.pitchBytes) * static_cast<std::size_t>(r.source.h);
            const std::size_t dstNeed =
                static_cast<std::size_t>(r.outputRowBytes) * static_cast<std::size_t>(r.outputHeight);
            if ([source length] < srcNeed || [output length] < dstNeed) {
                error = "a frame buffer is smaller than its layout";
                return false;
            }

            id<MTLComputePipelineState> pipeline = nil;
            {
                Table& t = table();
                std::lock_guard<std::mutex> lock(t.mutex);
                pipeline = pipelineLocked(t, deviceIndex, device, error);
            }
            if (pipeline == nil) {
                return false;
            }

            id<MTLCommandBuffer> commands = [queue commandBuffer];
            id<MTLComputeCommandEncoder> encoder = commands != nil ? [commands computeCommandEncoder] : nil;
            if (encoder == nil) {
                error = "cannot create a command buffer on the host's queue";
                return false;
            }
            const int rowBytes = r.outputRowBytes;
            const int isHalf = r.outputIsHalf ? 1 : 0;
            [encoder setComputePipelineState:pipeline];
            [encoder setBytes:&r.params length:sizeof(OsvReframeParams) atIndex:0];
            [encoder setBytes:&r.source length:sizeof(OsvRgbaSource) atIndex:1];
            [encoder setBuffer:source offset:r.sourceOffset atIndex:2];
            [encoder setBuffer:output offset:0 atIndex:3];
            [encoder setBytes:&rowBytes length:sizeof(rowBytes) atIndex:4];
            [encoder setBytes:&isHalf length:sizeof(isHalf) atIndex:5];

            // One SIMD group wide, as many rows as the pipeline allows up to
            // 16 (the SDK sample's shape); the grid is rounded up and the
            // kernel guards the tail.
            const NSUInteger width = std::max<NSUInteger>(1, [pipeline threadExecutionWidth]);
            const NSUInteger height =
                std::clamp<NSUInteger>([pipeline maxTotalThreadsPerThreadgroup] / width, 1, 16);
            const MTLSize group = MTLSizeMake(width, height, 1);
            const MTLSize groups = MTLSizeMake((static_cast<NSUInteger>(r.outputWidth) + width - 1) / width,
                                               (static_cast<NSUInteger>(r.outputHeight) + height - 1) / height, 1);
            [encoder dispatchThreadgroups:groups threadsPerThreadgroup:group];
            [encoder endEncoding];

            // The host's queue orders this after the work that produced the
            // input; waiting makes Render's return mean "output complete".
            [commands commit];
            [commands waitUntilCompleted];
            if ([commands status] != MTLCommandBufferStatusCompleted) {
                error = "the reframe kernel failed: " + utf8([[commands error] localizedDescription]);
                return false;
            }
            return true;
        }
    } catch (...) {
        error = "unexpected failure rendering the frame";
        return false;
    }
}

void releaseDevices() noexcept {
    try {
        Table& t = table();
        std::lock_guard<std::mutex> lock(t.mutex);
        for (DeviceSlot& slot : t.slots) {
            slot = DeviceSlot{};
        }
    } catch (...) {
        // Releasing references cannot usefully fail; nothing to report.
    }
}

bool usesPrecompiledLibrary() noexcept {
    try {
        Table& t = table();
        std::lock_guard<std::mutex> lock(t.mutex);
        return t.precompiled;
    } catch (...) {
        return false;
    }
}

}  // namespace osv::reframe::metal
