// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 The OpenOSV Contributors
//
// OpenCL backend host code: device enumeration, run-time compilation of the
// embedded kernel sources, buffer management and the launch/readback.

#include "osv/render/OpenClRenderer.h"
#include "osv/core/Log.h"

#include <CL/cl.h>

#include <algorithm>
#include <cstring>
#include <format>
#include <mutex>
#include <vector>

// Embedded sources generated by cmake/EmbedKernel.cmake.  The generator
// stores the bytes as `unsigned char` (a file may be binary; 0x80..0xFF do
// not fit a signed char) and publishes a `<symbol>_text` pointer alias for
// text consumers such as clCreateProgramWithSource.
extern const char* const osv_cl_preamble_text;
extern const size_t osv_cl_preamble_size;
extern const char* const osv_cl_colormath_text;
extern const size_t osv_cl_colormath_size;
extern const char* const osv_cl_kernel_h_text;
extern const size_t osv_cl_kernel_h_size;
extern const char* const osv_cl_kernel_cl_text;
extern const size_t osv_cl_kernel_cl_size;

namespace osv::render {

namespace {

std::string clMessage(const char* what, cl_int err) { return std::format("{}: OpenCL error {}", what, static_cast<int>(err)); }

/// One enumerated device.
struct DeviceEntry {
    cl_platform_id platform = nullptr;
    cl_device_id device = nullptr;
    bool isGpu = false;
    std::string name;
};

/// Enumerate every device of every platform, GPUs first.
std::vector<DeviceEntry> enumerateDevices() {
    std::vector<DeviceEntry> result;
    cl_uint platformCount = 0;
    if (clGetPlatformIDs(0, nullptr, &platformCount) != CL_SUCCESS || platformCount == 0) {
        return result;
    }
    std::vector<cl_platform_id> platforms(platformCount);
    if (clGetPlatformIDs(platformCount, platforms.data(), nullptr) != CL_SUCCESS) {
        return result;
    }
    for (cl_platform_id platform : platforms) {
        cl_uint deviceCount = 0;
        if (clGetDeviceIDs(platform, CL_DEVICE_TYPE_ALL, 0, nullptr, &deviceCount) != CL_SUCCESS || deviceCount == 0) {
            continue;
        }
        std::vector<cl_device_id> devices(deviceCount);
        if (clGetDeviceIDs(platform, CL_DEVICE_TYPE_ALL, deviceCount, devices.data(), nullptr) != CL_SUCCESS) {
            continue;
        }
        for (cl_device_id dev : devices) {
            DeviceEntry e;
            e.platform = platform;
            e.device = dev;
            cl_device_type type = 0;
            clGetDeviceInfo(dev, CL_DEVICE_TYPE, sizeof(type), &type, nullptr);
            e.isGpu = (type & CL_DEVICE_TYPE_GPU) != 0;
            char buffer[256] = {};
            clGetDeviceInfo(dev, CL_DEVICE_NAME, sizeof(buffer) - 1, buffer, nullptr);
            std::string name = buffer;
            char version[128] = {};
            clGetDeviceInfo(dev, CL_DEVICE_VERSION, sizeof(version) - 1, version, nullptr);
            e.name = name + " (" + version + ")";
            result.push_back(std::move(e));
        }
    }
    std::stable_sort(result.begin(), result.end(), [](const DeviceEntry& a, const DeviceEntry& b) {
        return a.isGpu && !b.isGpu;
    });
    return result;
}

/// A device buffer that only grows.
struct ClBuffer {
    cl_mem mem = nullptr;
    std::size_t bytes = 0;

    Status ensure(cl_context ctx, std::size_t needed, cl_mem_flags flags) {
        if (mem && needed <= bytes) {
            return okStatus();
        }
        release();
        cl_int err = CL_SUCCESS;
        mem = clCreateBuffer(ctx, flags, needed, nullptr, &err);
        if (err != CL_SUCCESS || !mem) {
            mem = nullptr;
            return failStatus(ErrorCode::Gpu, clMessage("clCreateBuffer", err));
        }
        bytes = needed;
        return okStatus();
    }

    void release() noexcept {
        if (mem) {
            clReleaseMemObject(mem);
            mem = nullptr;
        }
        bytes = 0;
    }
};

}  // namespace

struct OpenClRenderer::Impl {
    DeviceEntry entry;
    cl_context context = nullptr;
    cl_command_queue queue = nullptr;
    cl_program program = nullptr;
    cl_kernel kernel = nullptr;
    std::string buildLog;
    ClBuffer y[2], u[2], v[2];
    ClBuffer seam;
    ClBuffer warp;
    ClBuffer out;
    std::mutex mutex;

    ~Impl() {
        if (queue) {
            clFinish(queue);
        }
        for (int i = 0; i < 2; ++i) {
            y[i].release();
            u[i].release();
            v[i].release();
        }
        seam.release();
        warp.release();
        out.release();
        if (kernel) {
            clReleaseKernel(kernel);
        }
        if (program) {
            clReleaseProgram(program);
        }
        if (queue) {
            clReleaseCommandQueue(queue);
        }
        if (context) {
            clReleaseContext(context);
        }
    }

    /// Compile the embedded sources for this device.
    Status buildProgram() {
        const char* sources[4] = {osv_cl_preamble_text, osv_cl_colormath_text, osv_cl_kernel_h_text,
                                  osv_cl_kernel_cl_text};
        const size_t lengths[4] = {osv_cl_preamble_size, osv_cl_colormath_size, osv_cl_kernel_h_size,
                                   osv_cl_kernel_cl_size};
        cl_int err = CL_SUCCESS;
        program = clCreateProgramWithSource(context, 4, sources, lengths, &err);
        if (err != CL_SUCCESS || !program) {
            return failStatus(ErrorCode::Gpu, clMessage("clCreateProgramWithSource", err));
        }
        // Strict floating point: correctly rounded divide/sqrt, no relaxed math,
        // no fused contraction (matches /fp:precise and -fmad=false).
        const char* options = "-cl-std=CL1.2 -cl-fp32-correctly-rounded-divide-sqrt -cl-single-precision-constant";
        err = clBuildProgram(program, 1, &entry.device, options, nullptr, nullptr);
        // Always capture the log; warnings are useful even on success.
        size_t logSize = 0;
        clGetProgramBuildInfo(program, entry.device, CL_PROGRAM_BUILD_LOG, 0, nullptr, &logSize);
        if (logSize > 1) {
            std::string logText(logSize, '\0');
            clGetProgramBuildInfo(program, entry.device, CL_PROGRAM_BUILD_LOG, logSize, logText.data(), nullptr);
            buildLog = logText.c_str();
        }
        if (err != CL_SUCCESS) {
            return failStatus(ErrorCode::Gpu, "OpenCL kernel build failed:\n" + buildLog);
        }
        kernel = clCreateKernel(program, "osvReframe", &err);
        if (err != CL_SUCCESS || !kernel) {
            return failStatus(ErrorCode::Gpu, clMessage("clCreateKernel", err));
        }
        return okStatus();
    }

    /// Upload one host plane into the lens buffers and bind them.  Returns
    /// the descriptor integers for the kernel arguments.
    Status uploadPlane(int lens, const OsvPlane& host, cl_uint& argIndex) {
        // Luma: copy tightly packed rows (stride == width) so the device
        // stride is simply the width.
        const std::size_t rowBytes = static_cast<std::size_t>(host.w) * sizeof(osv_u16);
        OSV_TRY(y[lens].ensure(context, rowBytes * static_cast<std::size_t>(host.h), CL_MEM_READ_ONLY));
        const size_t hostOrigin[3] = {0, 0, 0};
        const size_t region[3] = {rowBytes, static_cast<size_t>(host.h), 1};
        cl_int err = clEnqueueWriteBufferRect(queue, y[lens].mem, CL_FALSE, hostOrigin, hostOrigin, region, rowBytes,
                                              0, static_cast<size_t>(host.strideY) * sizeof(osv_u16), 0, host.y, 0,
                                              nullptr, nullptr);
        if (err != CL_SUCCESS) {
            return failStatus(ErrorCode::Gpu, clMessage("upload luma", err));
        }
        int strideY = host.w;
        int strideC = 0;
        if (host.chromaInterleaved) {
            const std::size_t cRow = static_cast<std::size_t>(host.cw) * 2 * sizeof(osv_u16);
            OSV_TRY(u[lens].ensure(context, cRow * static_cast<std::size_t>(host.ch), CL_MEM_READ_ONLY));
            const size_t cRegion[3] = {cRow, static_cast<size_t>(host.ch), 1};
            err = clEnqueueWriteBufferRect(queue, u[lens].mem, CL_FALSE, hostOrigin, hostOrigin, cRegion, cRow, 0,
                                           static_cast<size_t>(host.strideC) * sizeof(osv_u16), 0, host.u, 0,
                                           nullptr, nullptr);
            if (err != CL_SUCCESS) {
                return failStatus(ErrorCode::Gpu, clMessage("upload chroma", err));
            }
            strideC = host.cw * 2;
        } else {
            const std::size_t cRow = static_cast<std::size_t>(host.cw) * sizeof(osv_u16);
            OSV_TRY(u[lens].ensure(context, cRow * static_cast<std::size_t>(host.ch), CL_MEM_READ_ONLY));
            OSV_TRY(v[lens].ensure(context, cRow * static_cast<std::size_t>(host.ch), CL_MEM_READ_ONLY));
            const size_t cRegion[3] = {cRow, static_cast<size_t>(host.ch), 1};
            err = clEnqueueWriteBufferRect(queue, u[lens].mem, CL_FALSE, hostOrigin, hostOrigin, cRegion, cRow, 0,
                                           static_cast<size_t>(host.strideC) * sizeof(osv_u16), 0, host.u, 0,
                                           nullptr, nullptr);
            if (err != CL_SUCCESS) {
                return failStatus(ErrorCode::Gpu, clMessage("upload Cb", err));
            }
            err = clEnqueueWriteBufferRect(queue, v[lens].mem, CL_FALSE, hostOrigin, hostOrigin, cRegion, cRow, 0,
                                           static_cast<size_t>(host.strideC) * sizeof(osv_u16), 0, host.v, 0,
                                           nullptr, nullptr);
            if (err != CL_SUCCESS) {
                return failStatus(ErrorCode::Gpu, clMessage("upload Cr", err));
            }
            strideC = host.cw;
        }

        // Kernel arguments for this lens: y, u, v, w, h, cw, ch, sy, sc, bs, il.
        // For interleaved chroma the v buffer is the same object as u; the
        // kernel adds +1 through OsvPlane::v == u + 1 ... except that OpenCL
        // buffers cannot be offset by pointer arithmetic on the host, so we
        // pass the same buffer and set v = u + 1 inside the kernel wrapper.
        cl_mem vMem = host.chromaInterleaved ? u[lens].mem : v[lens].mem;
        const int ints[8] = {host.w, host.h, host.cw, host.ch, strideY, strideC, host.bitShift,
                             host.chromaInterleaved};
        err = clSetKernelArg(kernel, argIndex++, sizeof(cl_mem), &y[lens].mem);
        err |= clSetKernelArg(kernel, argIndex++, sizeof(cl_mem), &u[lens].mem);
        err |= clSetKernelArg(kernel, argIndex++, sizeof(cl_mem), &vMem);
        for (int k = 0; k < 8; ++k) {
            err |= clSetKernelArg(kernel, argIndex++, sizeof(int), &ints[k]);
        }
        if (err != CL_SUCCESS) {
            return failStatus(ErrorCode::Gpu, clMessage("clSetKernelArg (plane)", err));
        }
        return okStatus();
    }
};

OpenClRenderer::OpenClRenderer() : m_impl(std::make_unique<Impl>()) {}
OpenClRenderer::~OpenClRenderer() = default;

int OpenClRenderer::deviceCount() { return static_cast<int>(enumerateDevices().size()); }

bool OpenClRenderer::available(std::string* reason) {
    if (enumerateDevices().empty()) {
        if (reason) {
            *reason = "no OpenCL platforms/devices found";
        }
        return false;
    }
    return true;
}

std::string OpenClRenderer::deviceName(int deviceIndex) {
    const auto devices = enumerateDevices();
    if (deviceIndex < 0 || deviceIndex >= static_cast<int>(devices.size())) {
        return "unknown";
    }
    return devices[static_cast<std::size_t>(deviceIndex)].name;
}

const std::string& OpenClRenderer::buildLog() const noexcept { return m_impl->buildLog; }

Result<std::unique_ptr<OpenClRenderer>> OpenClRenderer::create(int deviceIndex) {
    const auto devices = enumerateDevices();
    if (devices.empty()) {
        return Error{ErrorCode::Gpu, "OpenCL unavailable: no devices"};
    }
    if (deviceIndex < 0 || deviceIndex >= static_cast<int>(devices.size())) {
        return Error{ErrorCode::InvalidArgument, "OpenCL device index out of range"};
    }
    std::unique_ptr<OpenClRenderer> r(new OpenClRenderer());
    Impl& impl = *r->m_impl;
    impl.entry = devices[static_cast<std::size_t>(deviceIndex)];

    cl_int err = CL_SUCCESS;
    const cl_context_properties props[] = {CL_CONTEXT_PLATFORM,
                                           reinterpret_cast<cl_context_properties>(impl.entry.platform), 0};
    impl.context = clCreateContext(props, 1, &impl.entry.device, nullptr, nullptr, &err);
    if (err != CL_SUCCESS || !impl.context) {
        return Error{ErrorCode::Gpu, clMessage("clCreateContext", err)};
    }
#if defined(CL_VERSION_2_0)
    impl.queue = clCreateCommandQueueWithProperties(impl.context, impl.entry.device, nullptr, &err);
#else
    impl.queue = clCreateCommandQueue(impl.context, impl.entry.device, 0, &err);
#endif
    if (err != CL_SUCCESS || !impl.queue) {
        return Error{ErrorCode::Gpu, clMessage("clCreateCommandQueue", err)};
    }
    OSV_TRY(impl.buildProgram());
    log::debug("OpenClRenderer: using {}", impl.entry.name);
    return std::move(r);
}

Result<ImageRGBAf> OpenClRenderer::render(const RenderJob& job) {
    if (!job.valid()) {
        return Error{ErrorCode::InvalidArgument, "OpenClRenderer: invalid render job"};
    }
    // CUDA device addresses mean nothing to an OpenCL context.
    if (job.planesOnDevice[0] || job.planesOnDevice[1]) {
        return Error{ErrorCode::InvalidArgument, "OpenClRenderer: the lens frames are CUDA device frames"};
    }
    Impl& impl = *m_impl;
    std::lock_guard<std::mutex> lock(impl.mutex);

    cl_uint arg = 0;
    cl_int err = clSetKernelArg(impl.kernel, arg++, sizeof(OsvRenderParams), &job.params);
    if (err != CL_SUCCESS) {
        return Error{ErrorCode::Gpu, clMessage("clSetKernelArg (params)", err)};
    }
    for (int i = 0; i < 2; ++i) {
        OSV_TRY(impl.uploadPlane(i, job.planes[static_cast<std::size_t>(i)], arg));
    }

    // Seam table: an empty table still needs a valid buffer object.
    const std::size_t seamBytes = std::max<std::size_t>(job.seamShiftDeg.size(), 1) * sizeof(float);
    OSV_TRY(impl.seam.ensure(impl.context, seamBytes, CL_MEM_READ_ONLY));
    if (!job.seamShiftDeg.empty()) {
        err = clEnqueueWriteBuffer(impl.queue, impl.seam.mem, CL_FALSE, 0, job.seamShiftDeg.size() * sizeof(float),
                                   job.seamShiftDeg.data(), 0, nullptr, nullptr);
        if (err != CL_SUCCESS) {
            return Error{ErrorCode::Gpu, clMessage("upload seam table", err)};
        }
    }
    err = clSetKernelArg(impl.kernel, arg++, sizeof(cl_mem), &impl.seam.mem);

    // 2-D parallax warp grid.  Like the seam table, an empty grid still needs
    // a valid buffer object bound - OpenCL rejects a null __global argument -
    // and params.warpEnabled is what actually decides whether it is read.
    const std::size_t warpBytes = std::max<std::size_t>(job.warpGrid.size(), 1) * sizeof(float);
    OSV_TRY(impl.warp.ensure(impl.context, warpBytes, CL_MEM_READ_ONLY));
    if (!job.warpGrid.empty()) {
        cl_int werr = clEnqueueWriteBuffer(impl.queue, impl.warp.mem, CL_FALSE, 0,
                                           job.warpGrid.size() * sizeof(float), job.warpGrid.data(), 0, nullptr,
                                           nullptr);
        if (werr != CL_SUCCESS) {
            return Error{ErrorCode::Gpu, clMessage("upload warp grid", werr)};
        }
    }
    err |= clSetKernelArg(impl.kernel, arg++, sizeof(cl_mem), &impl.warp.mem);

    // Output buffer (tightly packed float4 rows).
    OSV_TRY_ASSIGN(ImageRGBAf image, ImageRGBAf::create(static_cast<std::uint32_t>(job.params.outW),
                                                        static_cast<std::uint32_t>(job.params.outH)));
    const std::size_t outBytes = image.data.size() * sizeof(float);
    OSV_TRY(impl.out.ensure(impl.context, outBytes, CL_MEM_WRITE_ONLY));
    const int outPitchFloats = job.params.outW * 4;
    err |= clSetKernelArg(impl.kernel, arg++, sizeof(cl_mem), &impl.out.mem);
    err |= clSetKernelArg(impl.kernel, arg++, sizeof(int), &outPitchFloats);
    if (err != CL_SUCCESS) {
        return Error{ErrorCode::Gpu, clMessage("clSetKernelArg (output)", err)};
    }

    // Launch with a 16x16 work-group and a global size rounded up (the kernel
    // guards the edges).
    const size_t local[2] = {16, 16};
    const size_t global[2] = {(static_cast<size_t>(job.params.outW) + 15) / 16 * 16,
                              (static_cast<size_t>(job.params.outH) + 15) / 16 * 16};
    err = clEnqueueNDRangeKernel(impl.queue, impl.kernel, 2, nullptr, global, local, 0, nullptr, nullptr);
    if (err != CL_SUCCESS) {
        return Error{ErrorCode::Gpu, clMessage("clEnqueueNDRangeKernel", err)};
    }
    err = clEnqueueReadBuffer(impl.queue, impl.out.mem, CL_TRUE, 0, outBytes, image.data.data(), 0, nullptr, nullptr);
    if (err != CL_SUCCESS) {
        return Error{ErrorCode::Gpu, clMessage("clEnqueueReadBuffer", err)};
    }
    return image;
}

}  // namespace osv::render
