// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 The OpenOSV Contributors
//
// Metal backend host code: device enumeration, the kernel library (embedded
// metallib or a run-time compile of the embedded source), shared-storage
// buffers and the dispatch / readback.  The structure follows the OpenCL
// backend line for line, so the two can be read side by side.
//
// Built with ARC (-fobjc-arc): every Metal object below is a strong reference
// that is released when its owner (Impl, or a local) goes away.

#import <Foundation/Foundation.h>
#import <Metal/Metal.h>

#include "osv/render/MetalRenderer.h"
#include "osv/core/Log.h"
#include "osv/render/SeamTools.h"

#include <algorithm>
#include <cstring>
#include <mutex>
#include <string>
#include <vector>

// The library source (and, when the build had the Metal compiler, the
// ahead-of-time metallib) generated by cmake/EmbedKernel.cmake.
extern const unsigned char osv_metal_source[];
extern const size_t osv_metal_source_size;
#if defined(OSV_METAL_HAVE_METALLIB)
extern const unsigned char osv_metal_lib[];
extern const size_t osv_metal_lib_size;
#endif

namespace osv::render {

namespace {

// ---------------------------------------------------------------------------
//  Buffer indices of kernel.metal (keep in step with its header comment).
// ---------------------------------------------------------------------------
constexpr NSUInteger kBufParams = 0;
constexpr NSUInteger kBufPlane[2][4] = {{1, 2, 3, 4}, {5, 6, 7, 8}};  // y, u, v, descriptor
constexpr NSUInteger kBufSeam = 9;
constexpr NSUInteger kBufWarp = 10;
constexpr NSUInteger kBufBlendSeam = 11;
constexpr NSUInteger kBufPhoto = 12;
constexpr NSUInteger kBufSeamLow = 13;
constexpr NSUInteger kBufOut = 14;
constexpr NSUInteger kBufOutPitch = 15;
// osvSeamLowDecimate writes its output to buffer 9; osvSeamLowBlur takes
// params, src, dst, horizontal at 0..3.
constexpr NSUInteger kBufDecimateOut = 9;

/// UTF-8 copy of an NSString (empty for nil).
std::string utf8(NSString* s) {
    if (s == nil) {
        return {};
    }
    const char* c = [s UTF8String];
    return c ? std::string(c) : std::string();
}

/// Every Metal device: the system default first (the GPU a Mac drives its
/// displays with, and the one Premiere renders on by default), then the rest
/// in the order Metal lists them.
NSArray<id<MTLDevice>>* enumerateDevices() {
    NSMutableArray<id<MTLDevice>>* list = [NSMutableArray array];
    id<MTLDevice> preferred = MTLCreateSystemDefaultDevice();
    if (preferred != nil) {
        [list addObject:preferred];
    }
    NSArray<id<MTLDevice>>* all = MTLCopyAllDevices();
    for (id<MTLDevice> d in all) {
        if (d != nil && ![list containsObject:d]) {
            [list addObject:d];
        }
    }
    return list;
}

/// A shared-storage buffer that only grows (the CPU writes, the GPU reads,
/// or the other way round, through the same memory on Apple Silicon).
struct MtlBuffer {
    id<MTLBuffer> buffer = nil;
    std::size_t bytes = 0;

    Status ensure(id<MTLDevice> device, std::size_t needed) {
        if (needed == 0) {
            needed = sizeof(float);  // Metal refuses a zero-length buffer
        }
        if (buffer != nil && needed <= bytes) {
            return okStatus();
        }
        buffer = nil;
        bytes = 0;
        if (device == nil) {
            return failStatus(ErrorCode::Gpu, "Metal: no device");
        }
        if (needed > static_cast<std::size_t>([device maxBufferLength])) {
            return failStatus(ErrorCode::Gpu, "Metal: buffer of " + std::to_string(needed) +
                                                  " bytes exceeds the device's maximum");
        }
        buffer = [device newBufferWithLength:needed options:MTLResourceStorageModeShared];
        if (buffer == nil) {
            return failStatus(ErrorCode::Gpu, "Metal: cannot allocate " + std::to_string(needed) + " bytes");
        }
        bytes = needed;
        return okStatus();
    }

    /// Host pointer to the contents (shared storage), or nullptr.
    [[nodiscard]] void* contents() const noexcept { return buffer != nil ? [buffer contents] : nullptr; }
};

/// Copy `rows` rows of `rowBytes` each from a strided host plane into a
/// tightly packed buffer.
Status copyRows(MtlBuffer& dst, const void* src, std::size_t rowBytes, std::size_t srcPitchBytes, std::size_t rows) {
    if (!src || rowBytes == 0 || rows == 0 || srcPitchBytes < rowBytes) {
        return failStatus(ErrorCode::InvalidArgument, "Metal: bad plane geometry");
    }
    auto* out = static_cast<unsigned char*>(dst.contents());
    if (!out || dst.bytes < rowBytes * rows) {
        return failStatus(ErrorCode::Internal, "Metal: plane buffer too small");
    }
    const auto* in = static_cast<const unsigned char*>(src);
    if (srcPitchBytes == rowBytes) {
        std::memcpy(out, in, rowBytes * rows);
        return okStatus();
    }
    for (std::size_t r = 0; r < rows; ++r) {
        std::memcpy(out + r * rowBytes, in + r * srcPitchBytes, rowBytes);
    }
    return okStatus();
}

/// Threads per threadgroup for a 2-D (or 2-D x lens) dispatch of `pipeline`:
/// one SIMD group wide, as many rows as the pipeline allows up to 8.
MTLSize threadgroupFor(id<MTLComputePipelineState> pipeline) {
    const NSUInteger width = std::max<NSUInteger>(1, [pipeline threadExecutionWidth]);
    const NSUInteger maxThreads = std::max<NSUInteger>(width, [pipeline maxTotalThreadsPerThreadgroup]);
    const NSUInteger height = std::clamp<NSUInteger>(maxThreads / width, 1, 8);
    return MTLSizeMake(width, height, 1);
}

/// Threadgroups covering a w x h (x depth) grid; the kernels guard the edges,
/// so no non-uniform threadgroup support is needed.
MTLSize groupsFor(MTLSize group, NSUInteger w, NSUInteger h, NSUInteger depth) {
    return MTLSizeMake((w + group.width - 1) / group.width, (h + group.height - 1) / group.height, depth);
}

}  // namespace

struct MetalRenderer::Impl {
    id<MTLDevice> device = nil;
    id<MTLCommandQueue> queue = nil;
    id<MTLLibrary> library = nil;
    id<MTLComputePipelineState> stitch = nil;
    id<MTLComputePipelineState> lowDecimate = nil;  // [WP-SEAMTOOLS] seam low band, stage 1
    id<MTLComputePipelineState> lowBlur = nil;      // [WP-SEAMTOOLS] seam low band, stages 2 and 3
    std::string deviceName;
    std::string buildLog;
    bool precompiled = false;
    MtlBuffer params;
    MtlBuffer y[2], u[2], v[2];
    MtlBuffer seam;
    MtlBuffer warp;
    MtlBuffer blendSeam;       // [WP-SEAM] carved blend-seam table
    MtlBuffer photo;           // [WP-PHOTO] photometric seam table
    MtlBuffer seamLow;         // [WP-SEAMTOOLS] seam smoothing low band
    MtlBuffer seamLowScratch;  // [WP-SEAMTOOLS] its blur's middle pass
    MtlBuffer out;
    /// The eight descriptor integers of each uploaded lens (w, h, cw, ch,
    /// strideY, strideC, bitShift, interleaved), bound with setBytes.
    int planeInts[2][8] = {};
    std::mutex mutex;

    /// Build the library: the embedded metallib when there is one and the
    /// device takes it, otherwise the embedded source with fast math off.
    Status buildLibrary() {
        NSError* error = nil;
#if defined(OSV_METAL_HAVE_METALLIB)
        if (osv_metal_lib_size > 0) {
            dispatch_data_t data = dispatch_data_create(osv_metal_lib, osv_metal_lib_size, nullptr,
                                                        DISPATCH_DATA_DESTRUCTOR_DEFAULT);
            if (data != nullptr) {
                library = [device newLibraryWithData:data error:&error];
            }
            if (library != nil) {
                precompiled = true;
                return okStatus();
            }
            log::debug("MetalRenderer: the embedded metallib did not load ({}); compiling the source",
                       utf8([error localizedDescription]));
            error = nil;
        }
#endif
        NSString* source = [[NSString alloc] initWithBytes:osv_metal_source
                                                    length:osv_metal_source_size
                                                  encoding:NSUTF8StringEncoding];
        if (source == nil) {
            return failStatus(ErrorCode::Internal, "Metal: the embedded kernel source is not valid UTF-8");
        }
        MTLCompileOptions* options = [[MTLCompileOptions alloc] init];
        options.languageVersion = MTLLanguageVersion2_4;
        // IEEE division / sqrt and no reassociation: the numerical policy of
        // every backend (the transcendentals are metal::precise already).
#if defined(__MAC_15_0) && __MAC_OS_X_VERSION_MAX_ALLOWED >= __MAC_15_0
        if (@available(macOS 15.0, *)) {
            options.mathMode = MTLMathModeSafe;
            options.mathFloatingPointFunctions = MTLMathFloatingPointFunctionsPrecise;
        } else {
            options.fastMathEnabled = NO;
        }
#else
        options.fastMathEnabled = NO;
#endif
        library = [device newLibraryWithSource:source options:options error:&error];
        // Warnings arrive through `error` even on success: keep them.
        if (error != nil) {
            buildLog = utf8([error localizedDescription]);
        }
        if (library == nil) {
            return failStatus(ErrorCode::Gpu, "Metal kernel build failed:\n" + buildLog);
        }
        return okStatus();
    }

    /// One compute pipeline for a kernel function of the library.
    Status makePipeline(const char* functionName, id<MTLComputePipelineState> __strong& pipeline) {
        NSString* name = [NSString stringWithUTF8String:functionName];
        id<MTLFunction> function = [library newFunctionWithName:name];
        if (function == nil) {
            return failStatus(ErrorCode::Gpu, std::string("Metal: kernel function ") + functionName + " is missing");
        }
        NSError* error = nil;
        pipeline = [device newComputePipelineStateWithFunction:function error:&error];
        if (pipeline == nil) {
            return failStatus(ErrorCode::Gpu, std::string("Metal: cannot build the pipeline for ") + functionName +
                                                  ": " + utf8([error localizedDescription]));
        }
        return okStatus();
    }

    /// Copy one host plane into the lens buffers (tightly packed rows) and
    /// record its descriptor integers.
    Status uploadPlane(int lens, const OsvPlane& host) {
        if (!host.y || !host.u || host.w <= 0 || host.h <= 0 || host.cw <= 0 || host.ch <= 0 || host.strideY < host.w) {
            return failStatus(ErrorCode::InvalidArgument, "Metal: lens plane is not usable");
        }
        const std::size_t rowBytes = static_cast<std::size_t>(host.w) * sizeof(osv_u16);
        OSV_TRY(y[lens].ensure(device, rowBytes * static_cast<std::size_t>(host.h)));
        OSV_TRY(copyRows(y[lens], host.y, rowBytes, static_cast<std::size_t>(host.strideY) * sizeof(osv_u16),
                         static_cast<std::size_t>(host.h)));
        int strideC = 0;
        if (host.chromaInterleaved) {
            // CbCr pairs: one buffer; the kernel wrapper derives Cr = Cb + 1.
            const std::size_t cRow = static_cast<std::size_t>(host.cw) * 2 * sizeof(osv_u16);
            OSV_TRY(u[lens].ensure(device, cRow * static_cast<std::size_t>(host.ch)));
            OSV_TRY(copyRows(u[lens], host.u, cRow, static_cast<std::size_t>(host.strideC) * sizeof(osv_u16),
                             static_cast<std::size_t>(host.ch)));
            strideC = host.cw * 2;
        } else {
            if (!host.v) {
                return failStatus(ErrorCode::InvalidArgument, "Metal: planar chroma without a Cr plane");
            }
            const std::size_t cRow = static_cast<std::size_t>(host.cw) * sizeof(osv_u16);
            OSV_TRY(u[lens].ensure(device, cRow * static_cast<std::size_t>(host.ch)));
            OSV_TRY(v[lens].ensure(device, cRow * static_cast<std::size_t>(host.ch)));
            OSV_TRY(copyRows(u[lens], host.u, cRow, static_cast<std::size_t>(host.strideC) * sizeof(osv_u16),
                             static_cast<std::size_t>(host.ch)));
            OSV_TRY(copyRows(v[lens], host.v, cRow, static_cast<std::size_t>(host.strideC) * sizeof(osv_u16),
                             static_cast<std::size_t>(host.ch)));
            strideC = host.cw;
        }
        const int ints[8] = {host.w, host.h, host.cw, host.ch, host.w, strideC, host.bitShift, host.chromaInterleaved};
        std::memcpy(planeInts[lens], ints, sizeof(ints));
        return okStatus();
    }

    /// Bind lens `lens`'s plane buffers and descriptor on `encoder`.  For
    /// interleaved chroma the v slot gets the u buffer (never read through).
    void bindPlane(id<MTLComputeCommandEncoder> encoder, int lens) {
        const NSUInteger* slots = kBufPlane[lens];
        id<MTLBuffer> vBuffer = planeInts[lens][7] ? u[lens].buffer : v[lens].buffer;
        [encoder setBuffer:y[lens].buffer offset:0 atIndex:slots[0]];
        [encoder setBuffer:u[lens].buffer offset:0 atIndex:slots[1]];
        [encoder setBuffer:vBuffer offset:0 atIndex:slots[2]];
        [encoder setBytes:planeInts[lens] length:sizeof(planeInts[lens]) atIndex:slots[3]];
    }

    /// Upload a float table into `buffer`, or one zero float when the table
    /// is empty (the kernel always gets a valid buffer; params decide whether
    /// it is read).
    Status uploadTable(MtlBuffer& buffer, const std::vector<float>& table) {
        OSV_TRY(buffer.ensure(device, std::max<std::size_t>(table.size(), 1) * sizeof(float)));
        auto* dst = static_cast<float*>(buffer.contents());
        if (!dst) {
            return failStatus(ErrorCode::Internal, "Metal: table buffer has no contents");
        }
        if (table.empty()) {
            dst[0] = 0.0f;
        } else {
            std::memcpy(dst, table.data(), table.size() * sizeof(float));
        }
        return okStatus();
    }

    /// [WP-SEAMTOOLS] Encode the seam low band build into `encoder`:
    /// decimate into seamLow, blur along x into the scratch buffer, along y
    /// back into seamLow.  A serial compute encoder runs dispatches in order,
    /// so the stitch encoded after them reads the finished table.
    Status encodeSeamLow(id<MTLComputeCommandEncoder> encoder, const OsvRenderParams& p, std::size_t floats) {
        OSV_TRY(seamLowScratch.ensure(device, floats * sizeof(float)));
        const NSUInteger w = static_cast<NSUInteger>(p.seamLowW);
        const NSUInteger h = static_cast<NSUInteger>(p.seamLowH);
        // ---- stage 1: decimate ------------------------------------------------
        [encoder setComputePipelineState:lowDecimate];
        [encoder setBuffer:params.buffer offset:0 atIndex:kBufParams];
        bindPlane(encoder, 0);
        bindPlane(encoder, 1);
        [encoder setBuffer:seamLow.buffer offset:0 atIndex:kBufDecimateOut];
        const MTLSize decimateGroup = threadgroupFor(lowDecimate);
        [encoder dispatchThreadgroups:groupsFor(decimateGroup, w, h, 2) threadsPerThreadgroup:decimateGroup];
        // ---- stages 2 and 3: the separable blur --------------------------------
        [encoder setComputePipelineState:lowBlur];
        const MTLSize blurGroup = threadgroupFor(lowBlur);
        const auto blurPass = [&](id<MTLBuffer> src, id<MTLBuffer> dst, int horizontal) {
            [encoder setBuffer:params.buffer offset:0 atIndex:0];
            [encoder setBuffer:src offset:0 atIndex:1];
            [encoder setBuffer:dst offset:0 atIndex:2];
            [encoder setBytes:&horizontal length:sizeof(horizontal) atIndex:3];
            [encoder dispatchThreadgroups:groupsFor(blurGroup, w, h, 2) threadsPerThreadgroup:blurGroup];
        };
        blurPass(seamLow.buffer, seamLowScratch.buffer, 1);
        blurPass(seamLowScratch.buffer, seamLow.buffer, 0);
        return okStatus();
    }
};

MetalRenderer::MetalRenderer() : m_impl(std::make_unique<Impl>()) {}
MetalRenderer::~MetalRenderer() = default;

int MetalRenderer::deviceCount() {
    @autoreleasepool {
        return static_cast<int>([enumerateDevices() count]);
    }
}

bool MetalRenderer::available(std::string* reason) {
    if (deviceCount() <= 0) {
        if (reason) {
            *reason = "no Metal device found";
        }
        return false;
    }
    return true;
}

std::string MetalRenderer::deviceName(int deviceIndex) {
    @autoreleasepool {
        NSArray<id<MTLDevice>>* devices = enumerateDevices();
        if (deviceIndex < 0 || deviceIndex >= static_cast<int>([devices count])) {
            return "unknown";
        }
        return utf8([devices[static_cast<NSUInteger>(deviceIndex)] name]);
    }
}

const std::string& MetalRenderer::buildLog() const noexcept { return m_impl->buildLog; }

bool MetalRenderer::usesPrecompiledLibrary() const noexcept { return m_impl->precompiled; }

Result<std::unique_ptr<MetalRenderer>> MetalRenderer::create(int deviceIndex) {
    @autoreleasepool {
        NSArray<id<MTLDevice>>* devices = enumerateDevices();
        if ([devices count] == 0) {
            return Error{ErrorCode::Gpu, "Metal unavailable: no devices"};
        }
        if (deviceIndex < 0 || deviceIndex >= static_cast<int>([devices count])) {
            return Error{ErrorCode::InvalidArgument, "Metal device index out of range"};
        }
        std::unique_ptr<MetalRenderer> r(new MetalRenderer());
        Impl& impl = *r->m_impl;
        impl.device = devices[static_cast<NSUInteger>(deviceIndex)];
        impl.deviceName = utf8([impl.device name]);
        impl.queue = [impl.device newCommandQueue];
        if (impl.queue == nil) {
            return Error{ErrorCode::Gpu, "Metal: cannot create a command queue on " + impl.deviceName};
        }
        OSV_TRY(impl.buildLibrary());
        OSV_TRY(impl.makePipeline("osvReframe", impl.stitch));
        OSV_TRY(impl.makePipeline("osvSeamLowDecimate", impl.lowDecimate));
        OSV_TRY(impl.makePipeline("osvSeamLowBlur", impl.lowBlur));
        log::debug("MetalRenderer: using {} ({} library)", impl.deviceName,
                   impl.precompiled ? "precompiled" : "run-time compiled");
        return std::move(r);
    }
}

Result<ImageRGBAf> MetalRenderer::render(const RenderJob& job) {
    if (!job.valid()) {
        return Error{ErrorCode::InvalidArgument, "MetalRenderer: invalid render job"};
    }
    // CUDA device addresses mean nothing to a Metal device.
    if (job.planesOnDevice[0] || job.planesOnDevice[1]) {
        return Error{ErrorCode::InvalidArgument, "MetalRenderer: the lens frames are CUDA device frames"};
    }
    Impl& impl = *m_impl;
    std::lock_guard<std::mutex> lock(impl.mutex);
    @autoreleasepool {
        // ---- inputs -------------------------------------------------------------
        OSV_TRY(impl.params.ensure(impl.device, sizeof(OsvRenderParams)));
        std::memcpy(impl.params.contents(), &job.params, sizeof(OsvRenderParams));
        for (int i = 0; i < 2; ++i) {
            OSV_TRY(impl.uploadPlane(i, job.planes[static_cast<std::size_t>(i)]));
        }
        OSV_TRY(impl.uploadTable(impl.seam, job.seamShiftDeg));
        OSV_TRY(impl.uploadTable(impl.warp, job.warpGrid));
        OSV_TRY(impl.uploadTable(impl.blendSeam, job.blendSeam));  // [WP-SEAM]
        OSV_TRY(impl.uploadTable(impl.photo, job.photoField));     // [WP-PHOTO]

        // [WP-SEAMTOOLS] The seam smoothing's low band, built on the GPU from
        // the planes just uploaded when smoothing is on with a carved seam;
        // otherwise a one-float buffer that the shader never reads.
        const std::size_t lowFloats =
            (job.params.seamSmoothEnabled && job.params.blendSeamEnabled && !job.blendSeam.empty())
                ? seamLowTableFloats(job.params)
                : 0;
        OSV_TRY(impl.seamLow.ensure(impl.device, std::max<std::size_t>(lowFloats, 1) * sizeof(float)));

        // ---- output -------------------------------------------------------------
        OSV_TRY_ASSIGN(ImageRGBAf image, ImageRGBAf::create(static_cast<std::uint32_t>(job.params.outW),
                                                            static_cast<std::uint32_t>(job.params.outH)));
        const std::size_t outBytes = image.data.size() * sizeof(float);
        OSV_TRY(impl.out.ensure(impl.device, outBytes));
        const int outPitchFloats = job.params.outW * 4;

        // ---- encode ---------------------------------------------------------------
        id<MTLCommandBuffer> commands = [impl.queue commandBuffer];
        if (commands == nil) {
            return Error{ErrorCode::Gpu, "Metal: cannot create a command buffer"};
        }
        id<MTLComputeCommandEncoder> encoder = [commands computeCommandEncoder];
        if (encoder == nil) {
            return Error{ErrorCode::Gpu, "Metal: cannot create a compute encoder"};
        }
        if (lowFloats > 0) {
            OSV_TRY(impl.encodeSeamLow(encoder, job.params, lowFloats));
        }
        [encoder setComputePipelineState:impl.stitch];
        [encoder setBuffer:impl.params.buffer offset:0 atIndex:kBufParams];
        impl.bindPlane(encoder, 0);
        impl.bindPlane(encoder, 1);
        [encoder setBuffer:impl.seam.buffer offset:0 atIndex:kBufSeam];
        [encoder setBuffer:impl.warp.buffer offset:0 atIndex:kBufWarp];
        [encoder setBuffer:impl.blendSeam.buffer offset:0 atIndex:kBufBlendSeam];
        [encoder setBuffer:impl.photo.buffer offset:0 atIndex:kBufPhoto];
        [encoder setBuffer:impl.seamLow.buffer offset:0 atIndex:kBufSeamLow];
        [encoder setBuffer:impl.out.buffer offset:0 atIndex:kBufOut];
        [encoder setBytes:&outPitchFloats length:sizeof(outPitchFloats) atIndex:kBufOutPitch];
        const MTLSize group = threadgroupFor(impl.stitch);
        [encoder dispatchThreadgroups:groupsFor(group, static_cast<NSUInteger>(job.params.outW),
                                                static_cast<NSUInteger>(job.params.outH), 1)
                threadsPerThreadgroup:group];
        [encoder endEncoding];

        // ---- run and read back -------------------------------------------------------
        [commands commit];
        [commands waitUntilCompleted];
        if ([commands status] != MTLCommandBufferStatusCompleted) {
            return Error{ErrorCode::Gpu, "Metal: the render failed: " + utf8([[commands error] localizedDescription])};
        }
        std::memcpy(image.data.data(), impl.out.contents(), outBytes);
        return image;
    }
}

}  // namespace osv::render
