#Requires -Version 5.1
<#
.SYNOPSIS
    Regenerates the shipped .cube LUTs in <repo>\luts from the built osvtool.

.DESCRIPTION
    The files in <repo>\luts are committed to git, but they are BUILD OUTPUT:
    every table is produced by `osvtool lut`, which bakes the same
    OsvColorParams pipeline the renderer uses into a 65^3 table, and the
    README.txt beside them is written by this script.  They are in the
    repository so a user can point Lumetri or Resolve at them without
    building anything, not because they are source.

    One set serves both cameras.  DJI ships the same D-Log M LUT for the Osmo
    360 and the Pocket 3, and the osmo360 curve is fitted to it, so the set
    is labelled DJI_Osmo and baked with that curve:

        luts\
          Rec2100_PQ\    DJI_Osmo_DLogM_to_Rec2100_PQ_<style>.cube   (5 styles)
          Rec2100_HLG\   DJI_Osmo_DLogM_to_Rec2100_HLG_<style>.cube  (5 styles)
          Rec709\        DJI_Osmo_DLogM_to_Rec709_<look>.cube        (2 looks)
          README.txt     which file to use

    The five HDR styles are Source Settings' "Transfer Function (HDR)"
    (osvtool lut --tone), the two Rec.709 looks its "Look (Rec. 709 only)"
    (--look); see docs/COLOR.md.

    Never hand-edit a file in luts\.  Change the curve or the pipeline, run
    this script, and commit what it produces.  tests/unit/test_cube.cpp
    regenerates every table and compares it against the committed copy, so a
    curve change that is not followed by a re-run fails the build rather than
    silently shipping a stale table.

    Reproducibility: the only inputs are the osvtool binary and the arguments
    below.  osvtool writes fixed six-decimal text with no timestamp, ordering
    or locale dependence, so two runs of the same binary produce byte-identical
    files and a diff is always a real change.

.PARAMETER OsvTool
    Path to osvtool.exe.  When omitted the script picks the newest
    <repo>\build\*\bin\osvtool.exe, so an ordinary build needs no arguments.

.PARAMETER OutDir
    Where to write the set.  Defaults to <repo>\luts.

.PARAMETER Size
    Grid points per axis.  Defaults to 65, which is what is committed.  65^3
    is the largest size Premiere's Lumetri and Resolve both load comfortably
    and keeps the trilinear error below the quantisation of a 10-bit signal.

.PARAMETER Fit
    D-Log M curve to bake.  Defaults to osmo360, the project default: the
    curve fitted to DJI's own D-Log M LUT, which is the same file for the
    Osmo 360 and the Pocket 3 (see docs/COLOR.md).

.PARAMETER Check
    Regenerates into a temporary folder and compares against OutDir instead of
    writing.  Exits non-zero when any file differs, so CI can assert that the
    committed LUTs match the current curve.

.EXAMPLE
    scripts\gen_luts.ps1
    Regenerates the whole set in <repo>\luts.

.EXAMPLE
    scripts\gen_luts.ps1 -Check
    Verifies the committed set is what the current build produces.

.NOTES
    Output is plain ASCII: the Windows console still defaults to a legacy code
    page on many machines.
#>
[CmdletBinding()]
param(
    [string] $OsvTool,
    [string] $OutDir,
    [int]    $Size = 65,
    [string] $Fit = 'osmo360',
    [switch] $Check
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$OutputEncoding = [System.Text.Encoding]::ASCII

$repoRoot = Split-Path -Parent $PSScriptRoot
if (-not $OutDir) { $OutDir = Join-Path $repoRoot 'luts' }

# ---------------------------------------------------------------------------
#  The set of shipped LUTs.
#
#  One entry per table: its folder, its file name, the osvtool arguments that
#  select it, and its TITLE.  The TITLE is written into the file and is what
#  an NLE may show in its LUT list, so it names OpenOSV (these are OUR
#  tables, generated by OUR generator from OUR fitted curve - no vendor LUT
#  data is redistributed, see NOTICE), the output, the style and the two
#  cameras, because a .cube carries no other provenance.
#
#  Every entry names its --look and --tone explicitly, so no file can change
#  if a library default ever moves.  The HDR tables ignore the look and the
#  Rec.709 tables ignore the tone.
#
#  tests/unit/test_cube.cpp holds the same list (folder, name, transfer,
#  look, tone, title) and must be kept in step with it.
# ---------------------------------------------------------------------------
$script:Cameras = 'DJI Osmo 360 / Pocket 3'
$script:HdrStyles = @(
    @{ Suffix = 'ACES2_Bright';               Tone = 'aces-bright';    Label = 'ACES 2 Bright (outdoor)' }
    @{ Suffix = 'ACES2_Detailed';             Tone = 'aces-detailed';  Label = 'ACES 2 Detailed (indoor)' }
    @{ Suffix = 'BT2408_DeepBlacks_Natural';  Tone = 'bt2408-natural'; Label = 'BT.2408 Deep Blacks + Natural' }
    @{ Suffix = 'BT2408_DeepBlacks_Punchy';   Tone = 'bt2408-punchy';  Label = 'BT.2408 Deep Blacks + Punchy' }
    @{ Suffix = 'BT2408_Neutral';             Tone = 'bt2408-neutral'; Label = 'BT.2408 Neutral' }
)
$script:Luts = @()
foreach ($output in @(
        @{ Dir = 'Rec2100_PQ';  Transfer = 'pq';  Name = 'Rec2100_PQ';  Title = 'Rec.2100 PQ' }
        @{ Dir = 'Rec2100_HLG'; Transfer = 'hlg'; Name = 'Rec2100_HLG'; Title = 'Rec.2100 HLG' })) {
    foreach ($style in $script:HdrStyles) {
        $script:Luts += @{
            Dir      = $output.Dir
            Name     = "DJI_Osmo_DLogM_to_$($output.Name)_$($style.Suffix).cube"
            Transfer = $output.Transfer
            Look     = 'dji'
            Tone     = $style.Tone
            Title    = "OpenOSV D-Log M to $($output.Title), $($style.Label) - $($script:Cameras)"
        }
    }
}
$script:Luts += @{
    Dir = 'Rec709'; Name = 'DJI_Osmo_DLogM_to_Rec709_DJI_Look.cube'; Transfer = '709'; Look = 'dji'
    Tone = 'aces-bright'; Title = "OpenOSV D-Log M to Rec.709, DJI look - $($script:Cameras)"
}
$script:Luts += @{
    Dir = 'Rec709'; Name = 'DJI_Osmo_DLogM_to_Rec709_OpenOSV_Standard.cube'; Transfer = '709'; Look = 'standard'
    Tone = 'aces-bright'; Title = "OpenOSV D-Log M to Rec.709, OpenOSV standard - $($script:Cameras)"
}

# ---------------------------------------------------------------------------
#  README.txt: which file to use.  Written with LF line endings like the
#  tables (.gitattributes keeps both byte-exact), and compared by -Check.
# ---------------------------------------------------------------------------
$script:ReadmeName = 'README.txt'
$script:ReadmeText = @'
OpenOSV LUTs for DJI D-Log M (Osmo 360 and Pocket 3)
====================================================

Apply these ONLY to raw D-Log M footage, never on top of a clip that is
already converted (an OpenOSV PQ / HLG / Rec.709 output, or DJI's own LUT).

Pick the folder that matches your timeline:
  Rec2100_PQ\    HDR10 / PQ timelines
  Rec2100_HLG\   HLG timelines
  Rec709\        SDR timelines

HDR styles (the same five as OpenOSV's "Transfer Function (HDR)"):
  ACES2_Bright                 the default. Good for outdoor.
  ACES2_Detailed               good for indoor: more highlight detail, darker.
  BT2408_DeepBlacks_Natural    BT.2408 brightness, deep blacks, true saturation.
  BT2408_DeepBlacks_Punchy     the same, with more colour.
  BT2408_Neutral               the plain BT.2408 rendering of OpenOSV 0.2.0.

Rec.709:
  DJI_Look                     DJI's own Rec.709 look. The default.
  OpenOSV_Standard             OpenOSV's neutral Rec.709 rendering.

One set fits both cameras: DJI ships the same D-Log M LUT for the Osmo 360
and the Pocket 3, and these tables use OpenOSV's curve fitted to it.
Generated by scripts\gen_luts.ps1 (osvtool lut). Apache-2.0.
'@

function Write-Step { param([string] $Message) Write-Host "==> $Message" }
function Write-Info { param([string] $Message) Write-Host "    $Message" }

# ---------------------------------------------------------------------------
#  Locate osvtool: the newest build\*\bin\osvtool.exe that actually exists.
# ---------------------------------------------------------------------------
function Find-OsvTool {
    $buildRoot = Join-Path $repoRoot 'build'
    if (-not (Test-Path -LiteralPath $buildRoot -PathType Container)) {
        throw "No -OsvTool given and '$buildRoot' does not exist. Build osvtool first (see docs/BUILDING.md)."
    }
    $candidates = Get-ChildItem -LiteralPath $buildRoot -Directory -ErrorAction SilentlyContinue |
        ForEach-Object { Join-Path $_.FullName 'bin\osvtool.exe' } |
        Where-Object { Test-Path -LiteralPath $_ -PathType Leaf } |
        Sort-Object { (Get-Item -LiteralPath $_).LastWriteTimeUtc } -Descending
    if (-not $candidates) {
        throw "No osvtool.exe found under '$buildRoot'. Build it, or pass -OsvTool <path>."
    }
    return [string]($candidates | Select-Object -First 1)
}

# ---------------------------------------------------------------------------
#  Generate one LUT into <Directory>\<Dir>\<Name>.  Throws on a non-zero exit
#  so a partial set is never left behind looking complete.
# ---------------------------------------------------------------------------
function New-Lut {
    param(
        [string]    $Tool,
        [hashtable] $Spec,
        [string]    $Directory
    )
    $folder = Join-Path $Directory $Spec.Dir
    if (-not (Test-Path -LiteralPath $folder -PathType Container)) {
        New-Item -ItemType Directory -Path $folder -Force | Out-Null
    }
    $path = Join-Path $folder $Spec.Name
    # 2>&1 so a failure message from the tool reaches the transcript rather
    # than the void; the output is only printed when the exit code is bad.
    $output = & $Tool lut --fit $Fit --look $Spec.Look --tone $Spec.Tone --out-transfer $Spec.Transfer `
        --size $Size --title $Spec.Title $path 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-Host ($output -join [Environment]::NewLine)
        throw "osvtool lut failed for '$($Spec.Name)' with exit code $LASTEXITCODE."
    }
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        throw "osvtool reported success but '$path' was not written."
    }
    # The grey anchor osvtool prints is the one number worth echoing: it is
    # what a user checks in their NLE to confirm the LUT loaded correctly.
    $anchor = @($output | Where-Object { $_ -match 'grey 0\.40' }) | Select-Object -First 1
    return [string]$anchor
}

# ---------------------------------------------------------------------------
#  Write README.txt into <Directory>, LF line endings, plain ASCII.
# ---------------------------------------------------------------------------
function New-Readme {
    param([string] $Directory)
    if (-not (Test-Path -LiteralPath $Directory -PathType Container)) {
        New-Item -ItemType Directory -Path $Directory -Force | Out-Null
    }
    $text = ($script:ReadmeText -replace "`r`n", "`n")
    if (-not $text.EndsWith("`n")) { $text += "`n" }
    [System.IO.File]::WriteAllText((Join-Path $Directory $script:ReadmeName), $text,
        (New-Object System.Text.ASCIIEncoding))
}

# ---------------------------------------------------------------------------
#  Byte comparison of one committed file against a fresh one; returns a
#  description of the difference, or '' when they are identical.
# ---------------------------------------------------------------------------
function Compare-Generated {
    param([string] $Committed, [string] $Fresh, [string] $Label)
    if (-not (Test-Path -LiteralPath $Committed -PathType Leaf)) {
        return "${Label}: missing from $OutDir"
    }
    # Byte comparison, not a text one: the point is that the committed file
    # IS the generator's output.
    $a = [System.IO.File]::ReadAllBytes($Committed)
    $b = [System.IO.File]::ReadAllBytes($Fresh)
    if ($a.Length -ne $b.Length) {
        return "${Label}: $($a.Length) bytes committed, $($b.Length) bytes generated"
    }
    if (@(Compare-Object $a $b -SyncWindow 0).Count -ne 0) {
        return "${Label}: contents differ"
    }
    return ''
}

try {
    if (-not $OsvTool) {
        $OsvTool = Find-OsvTool
        Write-Step "Using the newest build: $OsvTool"
    }
    if (-not (Test-Path -LiteralPath $OsvTool -PathType Leaf)) {
        throw "osvtool not found at '$OsvTool'."
    }
    if ($Size -lt 2 -or $Size -gt 256) {
        throw "-Size must be in [2, 256] (got $Size)."
    }

    if ($Check) {
        # ---- verification mode -------------------------------------------
        if (-not (Test-Path -LiteralPath $OutDir -PathType Container)) {
            throw "Nothing to check: '$OutDir' does not exist."
        }
        $temp = Join-Path ([System.IO.Path]::GetTempPath()) ("osv_luts_" + [System.Guid]::NewGuid().ToString('N'))
        New-Item -ItemType Directory -Path $temp -Force | Out-Null
        try {
            Write-Step "Checking $OutDir against a fresh generation"
            $differences = @()
            foreach ($spec in $script:Luts) {
                New-Lut -Tool $OsvTool -Spec $spec -Directory $temp | Out-Null
                $relative = Join-Path $spec.Dir $spec.Name
                $problem = Compare-Generated -Committed (Join-Path $OutDir $relative) `
                    -Fresh (Join-Path $temp $relative) -Label $relative
                if ($problem) { $differences += $problem } else { Write-Info ("{0,-72} ok" -f $relative) }
            }
            New-Readme -Directory $temp
            $problem = Compare-Generated -Committed (Join-Path $OutDir $script:ReadmeName) `
                -Fresh (Join-Path $temp $script:ReadmeName) -Label $script:ReadmeName
            if ($problem) { $differences += $problem } else { Write-Info ("{0,-72} ok" -f $script:ReadmeName) }
            # A table in the folder that the set no longer names (a renamed
            # or retired file) would ship stale: report it too.
            $expected = @($script:Luts | ForEach-Object { (Join-Path $_.Dir $_.Name).ToLowerInvariant() })
            $root = (Resolve-Path -LiteralPath $OutDir).Path.TrimEnd('\') + '\'
            foreach ($cube in @(Get-ChildItem -LiteralPath $OutDir -Recurse -File -Filter '*.cube')) {
                $relative = $cube.FullName.Substring($root.Length).ToLowerInvariant()
                if ($expected -notcontains $relative) {
                    $differences += "${relative}: not part of the set; delete it"
                }
            }
            if ($differences.Count -gt 0) {
                Write-Host ''
                Write-Step 'The committed LUTs are NOT what this build produces'
                foreach ($d in $differences) { Write-Info $d }
                Write-Host ''
                Write-Info 'Run scripts\gen_luts.ps1 (no -Check) and commit the result.'
                exit 1
            }
            Write-Host ''
            Write-Info 'All committed LUTs match the current build.'
            exit 0
        }
        finally {
            Remove-Item -LiteralPath $temp -Recurse -Force -ErrorAction SilentlyContinue
        }
    }

    # ---- generation mode --------------------------------------------------
    if (-not (Test-Path -LiteralPath $OutDir -PathType Container)) {
        New-Item -ItemType Directory -Path $OutDir -Force | Out-Null
    }
    Write-Step "Writing $($script:Luts.Count) LUT(s) and $($script:ReadmeName) into $OutDir"
    Write-Info "curve: $Fit    size: ${Size}^3"
    Write-Host ''
    foreach ($spec in $script:Luts) {
        $anchor = New-Lut -Tool $OsvTool -Spec $spec -Directory $OutDir
        $relative = Join-Path $spec.Dir $spec.Name
        $bytes = (Get-Item -LiteralPath (Join-Path $OutDir $relative)).Length
        Write-Info ("{0,-72} {1,10:N0} bytes" -f $relative, $bytes)
        if ($anchor) { Write-Info ("    " + $anchor.Trim()) }
    }
    New-Readme -Directory $OutDir
    Write-Info $script:ReadmeName
    Write-Host ''
    Write-Step 'These files are build output'
    Write-Info 'Commit them, but never edit them by hand: re-run this script.'
    exit 0
}
catch {
    Write-Host ''
    Write-Host "ERROR: $($_.Exception.Message)"
    exit 1
}
