#Requires -Version 5.1
<#
.SYNOPSIS
    Regenerates the shipped .cube LUTs in <repo>\luts from the built osvtool.

.DESCRIPTION
    The files in <repo>\luts are committed to git, but they are BUILD OUTPUT:
    every one of them is produced by `osvtool lut`, which bakes the same
    OsvColorParams pipeline the renderer uses into a 65^3 table.  They are in
    the repository so a user can point Lumetri at them without building
    anything, not because they are source.

    Never hand-edit a file in luts\.  Change the curve or the pipeline, run
    this script, and commit what it produces.  tests/unit/test_cube.cpp
    regenerates one of them and compares it against the committed copy, so a
    curve change that is not followed by a re-run fails the build rather than
    silently shipping a stale table.

    Reproducibility: the only inputs are the osvtool binary and the arguments
    below.  osvtool writes fixed six-decimal text with no timestamp, ordering
    or locale dependence, so two runs of the same binary produce byte-identical
    files and a diff is always a real change.

.PARAMETER OsvTool
    Path to osvtool.exe.  When omitted the script picks the newest
    <repo>\build\*\bin\osvtool.exe, so an ordinary build needs no arguments.

.PARAMETER OutDir
    Where to write the .cube files.  Defaults to <repo>\luts.

.PARAMETER Size
    Grid points per axis.  Defaults to 65, which is what is committed.  65^3
    is the largest size Premiere's Lumetri and Resolve both load comfortably
    and keeps the trilinear error below the quantisation of a 10-bit signal.

.PARAMETER Fit
    D-Log M curve to bake.  Defaults to osmo360, the project default (the
    curve fitted to DJI's own Osmo 360 reference; see docs/COLOR.md).

.PARAMETER Check
    Regenerates into a temporary folder and compares against OutDir instead of
    writing.  Exits non-zero when any file differs, so CI can assert that the
    committed LUTs match the current curve.

.EXAMPLE
    scripts\gen_luts.ps1
    Regenerates all three LUTs in <repo>\luts.

.EXAMPLE
    scripts\gen_luts.ps1 -Check
    Verifies the committed LUTs are what the current build produces.

.NOTES
    Output is plain ASCII: the Windows console still defaults to a legacy code
    page on many machines.
#>
[CmdletBinding()]
param(
    [string] $OsvTool,
    [string] $OutDir,
    [int]    $Size = 65,
    [string] $Fit = 'osmo360',
    [switch] $Check
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$OutputEncoding = [System.Text.Encoding]::ASCII

$repoRoot = Split-Path -Parent $PSScriptRoot
if (-not $OutDir) { $OutDir = Join-Path $repoRoot 'luts' }

# ---------------------------------------------------------------------------
#  The set of shipped LUTs.
#
#  One entry per delivery target.  The TITLE is written into the file and is
#  what an NLE shows in its LUT list, so it names OpenOSV (these are OUR
#  tables, generated by OUR generator from OUR fitted curve - no vendor LUT
#  data is redistributed, see NOTICE) and the curve that produced it, because
#  a .cube carries no other provenance.
#
#  Rec.709 is shipped alongside the two HDR tables for two reasons: it is the
#  SDR delivery path, and it is the one directly comparable to DJI's own
#  D-Log M -> Rec.709 LUT, which is how the curve was validated.  It carries
#  the DJI Studio look (include/osv/color/Look.h, the Rec.709 default), which
#  its title says; `--look dji` is passed explicitly so the file cannot change
#  if the library's default ever moves.  The HDR tables ignore the look.
# ---------------------------------------------------------------------------
$script:Luts = @(
    @{ Name = 'OpenOSV_Osmo360_DLogM_to_Rec2100_PQ.cube';  Transfer = 'pq';
       Title = 'OpenOSV Osmo 360 D-Log M to Rec.2100 PQ (osmo360 curve)' }
    @{ Name = 'OpenOSV_Osmo360_DLogM_to_Rec2100_HLG.cube'; Transfer = 'hlg';
       Title = 'OpenOSV Osmo 360 D-Log M to Rec.2100 HLG (osmo360 curve)' }
    @{ Name = 'OpenOSV_Osmo360_DLogM_to_Rec709.cube';      Transfer = '709';
       Title = 'OpenOSV Osmo 360 D-Log M to Rec.709 (osmo360 curve, DJI Studio look)' }
)

function Write-Step { param([string] $Message) Write-Host "==> $Message" }
function Write-Info { param([string] $Message) Write-Host "    $Message" }

# ---------------------------------------------------------------------------
#  Locate osvtool: the newest build\*\bin\osvtool.exe that actually exists.
# ---------------------------------------------------------------------------
function Find-OsvTool {
    $buildRoot = Join-Path $repoRoot 'build'
    if (-not (Test-Path -LiteralPath $buildRoot -PathType Container)) {
        throw "No -OsvTool given and '$buildRoot' does not exist. Build osvtool first (see docs/BUILDING.md)."
    }
    $candidates = Get-ChildItem -LiteralPath $buildRoot -Directory -ErrorAction SilentlyContinue |
        ForEach-Object { Join-Path $_.FullName 'bin\osvtool.exe' } |
        Where-Object { Test-Path -LiteralPath $_ -PathType Leaf } |
        Sort-Object { (Get-Item -LiteralPath $_).LastWriteTimeUtc } -Descending
    if (-not $candidates) {
        throw "No osvtool.exe found under '$buildRoot'. Build it, or pass -OsvTool <path>."
    }
    return [string]($candidates | Select-Object -First 1)
}

# ---------------------------------------------------------------------------
#  Generate one LUT.  Throws on a non-zero exit so a partial set is never
#  left behind looking complete.
# ---------------------------------------------------------------------------
function New-Lut {
    param(
        [string]    $Tool,
        [hashtable] $Spec,
        [string]    $Directory
    )
    $path = Join-Path $Directory $Spec.Name
    # 2>&1 so a failure message from the tool reaches the transcript rather
    # than the void; the output is only printed when the exit code is bad.
    $output = & $Tool lut --fit $Fit --look dji --out-transfer $Spec.Transfer --size $Size --title $Spec.Title $path 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-Host ($output -join [Environment]::NewLine)
        throw "osvtool lut failed for '$($Spec.Name)' with exit code $LASTEXITCODE."
    }
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        throw "osvtool reported success but '$path' was not written."
    }
    # The grey anchor osvtool prints is the one number worth echoing: it is
    # what a user checks in their NLE to confirm the LUT loaded correctly.
    $anchor = @($output | Where-Object { $_ -match 'grey 0\.40' }) | Select-Object -First 1
    return [string]$anchor
}

try {
    if (-not $OsvTool) {
        $OsvTool = Find-OsvTool
        Write-Step "Using the newest build: $OsvTool"
    }
    if (-not (Test-Path -LiteralPath $OsvTool -PathType Leaf)) {
        throw "osvtool not found at '$OsvTool'."
    }
    if ($Size -lt 2 -or $Size -gt 256) {
        throw "-Size must be in [2, 256] (got $Size)."
    }

    if ($Check) {
        # ---- verification mode -------------------------------------------
        if (-not (Test-Path -LiteralPath $OutDir -PathType Container)) {
            throw "Nothing to check: '$OutDir' does not exist."
        }
        $temp = Join-Path ([System.IO.Path]::GetTempPath()) ("osv_luts_" + [System.Guid]::NewGuid().ToString('N'))
        New-Item -ItemType Directory -Path $temp -Force | Out-Null
        try {
            Write-Step "Checking $OutDir against a fresh generation"
            $differences = @()
            foreach ($spec in $script:Luts) {
                New-Lut -Tool $OsvTool -Spec $spec -Directory $temp | Out-Null
                $committed = Join-Path $OutDir $spec.Name
                $fresh     = Join-Path $temp   $spec.Name
                if (-not (Test-Path -LiteralPath $committed -PathType Leaf)) {
                    $differences += "$($spec.Name): missing from $OutDir"
                    continue
                }
                # Byte comparison, not a text one: the point is that the
                # committed file IS the generator's output.
                $a = [System.IO.File]::ReadAllBytes($committed)
                $b = [System.IO.File]::ReadAllBytes($fresh)
                if ($a.Length -ne $b.Length) {
                    $differences += "$($spec.Name): $($a.Length) bytes committed, $($b.Length) bytes generated"
                }
                elseif (@(Compare-Object $a $b -SyncWindow 0).Count -ne 0) {
                    $differences += "$($spec.Name): contents differ"
                }
                else {
                    Write-Info ("{0,-46} ok" -f $spec.Name)
                }
            }
            if ($differences.Count -gt 0) {
                Write-Host ''
                Write-Step 'The committed LUTs are NOT what this build produces'
                foreach ($d in $differences) { Write-Info $d }
                Write-Host ''
                Write-Info 'Run scripts\gen_luts.ps1 (no -Check) and commit the result.'
                exit 1
            }
            Write-Host ''
            Write-Info 'All committed LUTs match the current build.'
            exit 0
        }
        finally {
            Remove-Item -LiteralPath $temp -Recurse -Force -ErrorAction SilentlyContinue
        }
    }

    # ---- generation mode --------------------------------------------------
    if (-not (Test-Path -LiteralPath $OutDir -PathType Container)) {
        New-Item -ItemType Directory -Path $OutDir -Force | Out-Null
    }
    Write-Step "Writing $($script:Luts.Count) LUT(s) into $OutDir"
    Write-Info "curve: $Fit    size: ${Size}^3"
    Write-Host ''
    foreach ($spec in $script:Luts) {
        $anchor = New-Lut -Tool $OsvTool -Spec $spec -Directory $OutDir
        $bytes = (Get-Item -LiteralPath (Join-Path $OutDir $spec.Name)).Length
        Write-Info ("{0,-46} {1,10:N0} bytes" -f $spec.Name, $bytes)
        if ($anchor) { Write-Info ("    " + $anchor.Trim()) }
    }
    Write-Host ''
    Write-Step 'These files are build output'
    Write-Info 'Commit them, but never edit them by hand: re-run this script.'
    exit 0
}
catch {
    Write-Host ''
    Write-Host "ERROR: $($_.Exception.Message)"
    exit 1
}
