# =============================================================================
#  EmbedKernelScript.cmake  (invoked with -P by EmbedKernel.cmake)
#
#  Inputs: -DINPUT=<file> -DOUTPUT=<cpp> -DSYMBOL=<identifier>
#  Reads INPUT as raw bytes and writes a C++ source defining a NUL-terminated
#  char array plus its size.
# =============================================================================
if(NOT INPUT OR NOT OUTPUT OR NOT SYMBOL)
  message(FATAL_ERROR "EmbedKernelScript.cmake needs INPUT, OUTPUT and SYMBOL")
endif()

file(READ "${INPUT}" _hex HEX)
string(LENGTH "${_hex}" _hexlen)
math(EXPR _bytes "${_hexlen} / 2")

# "0a1b2c" -> "0x0a,0x1b,0x2c,"
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _list "${_hex}")
# Break the initialiser into lines of 24 bytes for readability / compiler comfort.
string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){24})" "\\1\n  " _list "${_list}")

# The element type is `unsigned char`, not `char`.
#
# This file may hold arbitrary BYTES, not just text: a CUDA fatbin is full of
# values above 0x7F, and 0x80..0xFF are not representable in a (signed) char
# on MSVC.  Initialising a char array with them raises C4309 / C4838 (a
# narrowing conversion), and writing `(char)0xFF` instead raises C4310 - all
# three are errors under OSV_WARNINGS_AS_ERRORS.  `unsigned char` is the type
# a byte buffer should have had all along and every value fits it exactly.
#
# Text consumers (the OpenCL backend hands the symbol to
# clCreateProgramWithSource, which wants a const char*) get a second,
# zero-cost symbol: a pointer alias that does the reinterpretation once, in
# generated code, instead of at every call site.
file(WRITE "${OUTPUT}"
"// Generated by EmbedKernelScript.cmake from ${INPUT}. Do not edit.
//
// ${SYMBOL}       the raw bytes (NUL terminated, so it is also a valid C string
//                 when the input was text)
// ${SYMBOL}_size  the number of bytes, NOT counting the terminator
// ${SYMBOL}_text  the same bytes as a const char*, for text consumers
#include <cstddef>
extern const unsigned char ${SYMBOL}[];
extern const size_t ${SYMBOL}_size;
extern const char* const ${SYMBOL}_text;
const unsigned char ${SYMBOL}[] = {
  ${_list}0x00 };
const size_t ${SYMBOL}_size = ${_bytes};
const char* const ${SYMBOL}_text = reinterpret_cast<const char*>(${SYMBOL});
")
