# =============================================================================
#  EmbedKernelScript.cmake  (invoked with -P by EmbedKernel.cmake)
#
#  Inputs: -DINPUT=<file> -DOUTPUT=<cpp> -DSYMBOL=<identifier>
#  Reads INPUT as raw bytes and writes a C++ source defining a NUL-terminated
#  char array plus its size.
# =============================================================================
if(NOT INPUT OR NOT OUTPUT OR NOT SYMBOL)
  message(FATAL_ERROR "EmbedKernelScript.cmake needs INPUT, OUTPUT and SYMBOL")
endif()

file(READ "${INPUT}" _hex HEX)
string(LENGTH "${_hex}" _hexlen)
math(EXPR _bytes "${_hexlen} / 2")

# "0a1b2c" -> "0x0a,0x1b,0x2c,"
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _list "${_hex}")
# Break the initialiser into lines of 24 bytes for readability / compiler comfort.
string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){24})" "\\1\n  " _list "${_list}")

file(WRITE "${OUTPUT}"
"// Generated by EmbedKernelScript.cmake from ${INPUT}. Do not edit.
#include <cstddef>
extern const char ${SYMBOL}[];
extern const size_t ${SYMBOL}_size;
const char ${SYMBOL}[] = {
  ${_list}0x00 };
const size_t ${SYMBOL}_size = ${_bytes};
")
