# =============================================================================
#  OsvMetalConcat.cmake  (cmake -P script, run by osv_metal_library)
#
#  Concatenates the Metal library's parts into one source file, in order:
#
#      -DINPUTS=<file>?<file>?...   ('?' separated: never part of a path on
#                                    the platforms this runs on, and not a
#                                    shell metacharacter the way ';' and '|'
#                                    are inside a generated command line)
#      -DOUTPUT=<file.metal>
#
#  Each part is preceded by a one-line comment naming it, so a compiler
#  message's line number can be traced back to the file it came from.  The
#  output is rewritten only when its content changed, so an unrelated
#  rebuild does not recompile the metallib.
# =============================================================================
if(NOT INPUTS OR NOT OUTPUT)
  message(FATAL_ERROR "OsvMetalConcat.cmake needs INPUTS and OUTPUT")
endif()

string(REPLACE "?" ";" _inputs "${INPUTS}")
set(_text "/* Generated by cmake/OsvMetalConcat.cmake. Do not edit. */\n")
foreach(_in IN LISTS _inputs)
  if(NOT EXISTS "${_in}")
    message(FATAL_ERROR "OsvMetalConcat: input '${_in}' does not exist")
  endif()
  get_filename_component(_name "${_in}" NAME)
  file(READ "${_in}" _part)
  string(APPEND _text "\n/* ===== ${_name} ===== */\n" "${_part}" "\n")
endforeach()

set(_old "")
if(EXISTS "${OUTPUT}")
  file(READ "${OUTPUT}" _old)
endif()
if(NOT _old STREQUAL _text)
  file(WRITE "${OUTPUT}" "${_text}")
endif()
